// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package projectdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 保存项目 connector 和 Git transport 使用的加密 credential；不保存明文。
type ProjectSecret struct {
	// 应用生成的 UUIDv7 secret 引用标识，可安全出现在配置响应中。
	ID pgtype.UUID
	// credential 所属项目，跨项目引用由组合外键拒绝。
	ProjectID pgtype.UUID
	// 项目内唯一的 credential 显示名称。
	Name string
	// credential 的用途类型，用于限制可引用位置和加密关联数据。
	Kind string
	// AES-256-GCM 输出的密文与 authentication tag，不得进入 API、日志或审计。
	Ciphertext []byte
	// 每次写入随机生成的 96-bit GCM nonce，不得作为 API 字段返回。
	Nonce []byte
	// 加密该值的部署密钥版本，用于未来受控轮换。
	KeyVersion int32
	// credential metadata 或加密值的单调递增版本号。
	Version int64
	// credential 首次创建时的 PostgreSQL 时钟时间。
	CreatedAt pgtype.Timestamptz
	// credential 最近一次替换或 metadata 变化时的 PostgreSQL 时钟时间。
	UpdatedAt pgtype.Timestamptz
}
