// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package projectdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects (id, project_key, name, description)
VALUES ($1, $2, $3, $4)
RETURNING id, project_key, name, description, version, created_at, updated_at
`

type CreateProjectParams struct {
	ProjectID   pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
}

type CreateProjectRow struct {
	ID          pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ProjectID,
		arg.ProjectKey,
		arg.Name,
		arg.Description,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectSecret = `-- name: CreateProjectSecret :one
WITH created_secret AS (
    INSERT INTO project_secrets (id, project_id, name, kind, ciphertext, nonce, key_version)
    VALUES ($1, $2, $3, $4,
            $5, $6, $7)
    RETURNING id, project_id, name, kind, key_version, version, created_at, updated_at
)
SELECT id, project_id, name, kind, key_version, version, created_at, updated_at
FROM created_secret
`

type CreateProjectSecretParams struct {
	SecretID   pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Kind       string
	Ciphertext []byte
	Nonce      []byte
	KeyVersion int32
}

type CreateProjectSecretRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Kind       string
	KeyVersion int32
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateProjectSecret(ctx context.Context, arg CreateProjectSecretParams) (CreateProjectSecretRow, error) {
	row := q.db.QueryRow(ctx, createProjectSecret,
		arg.SecretID,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyVersion,
	)
	var i CreateProjectSecretRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.KeyVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProject = `-- name: GetProject :one
SELECT id, project_key, name, description, version, created_at, updated_at
FROM projects
WHERE project_key = $1
`

type GetProjectRow struct {
	ID          pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetProject(ctx context.Context, projectKey string) (GetProjectRow, error) {
	row := q.db.QueryRow(ctx, getProject, projectKey)
	var i GetProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectConfiguration = `-- name: GetProjectConfiguration :one
SELECT e.id AS environment_id, e.environment_key, e.name AS environment_name, e.service,
       e.version AS environment_version,
       r.id AS repository_id, r.remote_url, r.scm_provider, r.transport,
       r.credential_secret_id AS repository_credential_secret_id,
       r.production_branch, r.deployed_commit, r.version AS repository_version,
       s.id AS source_id, s.kind AS source_kind,
       s.credential_secret_id AS source_credential_secret_id, s.config AS source_config,
       s.capabilities AS source_capabilities, s.enabled AS source_enabled, s.version AS source_version,
       t.id AS trigger_id, t.kind AS trigger_kind,
       t.signing_secret_id, t.config AS trigger_config, t.enabled AS trigger_enabled,
       t.version AS trigger_version,
       t.ingress_token_hash, t.ingress_token_ciphertext, t.ingress_token_nonce,
       l.id AS llm_id, l.provider AS llm_provider, l.base_url AS llm_base_url,
       l.credential_secret_id AS llm_credential_secret_id, l.model AS llm_model,
       l.version AS llm_version
FROM project_environments AS e
JOIN project_repositories AS r ON r.project_id = e.project_id
JOIN project_sources AS s ON s.project_id = e.project_id AND s.environment_id = e.id
JOIN project_triggers AS t ON t.project_id = e.project_id AND t.environment_id = e.id
LEFT JOIN project_llm_providers AS l ON l.project_id = e.project_id
WHERE e.project_id = $1
ORDER BY e.created_at
LIMIT 1
`

type GetProjectConfigurationRow struct {
	EnvironmentID                pgtype.UUID
	EnvironmentKey               string
	EnvironmentName              string
	Service                      *string
	EnvironmentVersion           int64
	RepositoryID                 pgtype.UUID
	RemoteUrl                    string
	ScmProvider                  string
	Transport                    string
	RepositoryCredentialSecretID pgtype.UUID
	ProductionBranch             string
	DeployedCommit               string
	RepositoryVersion            int64
	SourceID                     pgtype.UUID
	SourceKind                   string
	SourceCredentialSecretID     pgtype.UUID
	SourceConfig                 []byte
	SourceCapabilities           []string
	SourceEnabled                bool
	SourceVersion                int64
	TriggerID                    pgtype.UUID
	TriggerKind                  string
	SigningSecretID              pgtype.UUID
	TriggerConfig                []byte
	TriggerEnabled               bool
	TriggerVersion               int64
	IngressTokenHash             []byte
	IngressTokenCiphertext       []byte
	IngressTokenNonce            []byte
	LlmID                        pgtype.UUID
	LlmProvider                  *string
	LlmBaseUrl                   *string
	LlmCredentialSecretID        pgtype.UUID
	LlmModel                     *string
	LlmVersion                   *int64
}

func (q *Queries) GetProjectConfiguration(ctx context.Context, projectID pgtype.UUID) (GetProjectConfigurationRow, error) {
	row := q.db.QueryRow(ctx, getProjectConfiguration, projectID)
	var i GetProjectConfigurationRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentKey,
		&i.EnvironmentName,
		&i.Service,
		&i.EnvironmentVersion,
		&i.RepositoryID,
		&i.RemoteUrl,
		&i.ScmProvider,
		&i.Transport,
		&i.RepositoryCredentialSecretID,
		&i.ProductionBranch,
		&i.DeployedCommit,
		&i.RepositoryVersion,
		&i.SourceID,
		&i.SourceKind,
		&i.SourceCredentialSecretID,
		&i.SourceConfig,
		&i.SourceCapabilities,
		&i.SourceEnabled,
		&i.SourceVersion,
		&i.TriggerID,
		&i.TriggerKind,
		&i.SigningSecretID,
		&i.TriggerConfig,
		&i.TriggerEnabled,
		&i.TriggerVersion,
		&i.IngressTokenHash,
		&i.IngressTokenCiphertext,
		&i.IngressTokenNonce,
		&i.LlmID,
		&i.LlmProvider,
		&i.LlmBaseUrl,
		&i.LlmCredentialSecretID,
		&i.LlmModel,
		&i.LlmVersion,
	)
	return i, err
}

const getProjectEnvironment = `-- name: GetProjectEnvironment :one
SELECT id, environment_key, name, service, version
FROM project_environments
WHERE project_id = $1
ORDER BY created_at
LIMIT 1
`

type GetProjectEnvironmentRow struct {
	ID             pgtype.UUID
	EnvironmentKey string
	Name           string
	Service        *string
	Version        int64
}

func (q *Queries) GetProjectEnvironment(ctx context.Context, projectID pgtype.UUID) (GetProjectEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, getProjectEnvironment, projectID)
	var i GetProjectEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentKey,
		&i.Name,
		&i.Service,
		&i.Version,
	)
	return i, err
}

const getProjectLLMProvider = `-- name: GetProjectLLMProvider :one
SELECT id, provider, base_url, credential_secret_id, model, version
FROM project_llm_providers
WHERE project_id = $1
LIMIT 1
`

type GetProjectLLMProviderRow struct {
	ID                 pgtype.UUID
	Provider           string
	BaseUrl            string
	CredentialSecretID pgtype.UUID
	Model              string
	Version            int64
}

func (q *Queries) GetProjectLLMProvider(ctx context.Context, projectID pgtype.UUID) (GetProjectLLMProviderRow, error) {
	row := q.db.QueryRow(ctx, getProjectLLMProvider, projectID)
	var i GetProjectLLMProviderRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BaseUrl,
		&i.CredentialSecretID,
		&i.Model,
		&i.Version,
	)
	return i, err
}

const getProjectRemediationPolicy = `-- name: GetProjectRemediationPolicy :one
SELECT agent_loop_mode, agent_loop_policy_version
FROM projects
WHERE id = $1
`

type GetProjectRemediationPolicyRow struct {
	AgentLoopMode          string
	AgentLoopPolicyVersion int64
}

func (q *Queries) GetProjectRemediationPolicy(ctx context.Context, projectID pgtype.UUID) (GetProjectRemediationPolicyRow, error) {
	row := q.db.QueryRow(ctx, getProjectRemediationPolicy, projectID)
	var i GetProjectRemediationPolicyRow
	err := row.Scan(&i.AgentLoopMode, &i.AgentLoopPolicyVersion)
	return i, err
}

const getProjectRepository = `-- name: GetProjectRepository :one
SELECT id, remote_url, scm_provider, transport, credential_secret_id,
       production_branch, deployed_commit, version
FROM project_repositories
WHERE project_id = $1
LIMIT 1
`

type GetProjectRepositoryRow struct {
	ID                 pgtype.UUID
	RemoteUrl          string
	ScmProvider        string
	Transport          string
	CredentialSecretID pgtype.UUID
	ProductionBranch   string
	DeployedCommit     string
	Version            int64
}

func (q *Queries) GetProjectRepository(ctx context.Context, projectID pgtype.UUID) (GetProjectRepositoryRow, error) {
	row := q.db.QueryRow(ctx, getProjectRepository, projectID)
	var i GetProjectRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.RemoteUrl,
		&i.ScmProvider,
		&i.Transport,
		&i.CredentialSecretID,
		&i.ProductionBranch,
		&i.DeployedCommit,
		&i.Version,
	)
	return i, err
}

const getProjectSecret = `-- name: GetProjectSecret :one
SELECT id, project_id, name, kind, ciphertext, nonce, key_version, version, created_at, updated_at
FROM project_secrets
WHERE project_id = $1 AND id = $2
`

type GetProjectSecretParams struct {
	ProjectID pgtype.UUID
	SecretID  pgtype.UUID
}

func (q *Queries) GetProjectSecret(ctx context.Context, arg GetProjectSecretParams) (ProjectSecret, error) {
	row := q.db.QueryRow(ctx, getProjectSecret, arg.ProjectID, arg.SecretID)
	var i ProjectSecret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSource = `-- name: GetProjectSource :one
SELECT id, kind, credential_secret_id, config, capabilities, enabled, version
FROM project_sources
WHERE project_id = $1
LIMIT 1
`

type GetProjectSourceRow struct {
	ID                 pgtype.UUID
	Kind               string
	CredentialSecretID pgtype.UUID
	Config             []byte
	Capabilities       []string
	Enabled            bool
	Version            int64
}

func (q *Queries) GetProjectSource(ctx context.Context, projectID pgtype.UUID) (GetProjectSourceRow, error) {
	row := q.db.QueryRow(ctx, getProjectSource, projectID)
	var i GetProjectSourceRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CredentialSecretID,
		&i.Config,
		&i.Capabilities,
		&i.Enabled,
		&i.Version,
	)
	return i, err
}

const getProjectTrigger = `-- name: GetProjectTrigger :one
SELECT id, kind, signing_secret_id, config, enabled, version,
       ingress_token_hash, ingress_token_ciphertext, ingress_token_nonce
FROM project_triggers
WHERE project_id = $1
LIMIT 1
`

type GetProjectTriggerRow struct {
	ID                     pgtype.UUID
	Kind                   string
	SigningSecretID        pgtype.UUID
	Config                 []byte
	Enabled                bool
	Version                int64
	IngressTokenHash       []byte
	IngressTokenCiphertext []byte
	IngressTokenNonce      []byte
}

func (q *Queries) GetProjectTrigger(ctx context.Context, projectID pgtype.UUID) (GetProjectTriggerRow, error) {
	row := q.db.QueryRow(ctx, getProjectTrigger, projectID)
	var i GetProjectTriggerRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SigningSecretID,
		&i.Config,
		&i.Enabled,
		&i.Version,
		&i.IngressTokenHash,
		&i.IngressTokenCiphertext,
		&i.IngressTokenNonce,
	)
	return i, err
}

const listProjectSecrets = `-- name: ListProjectSecrets :many
SELECT id, project_id, name, kind, key_version, version, created_at, updated_at,
       COUNT(*) OVER() AS total_count
FROM project_secrets
WHERE project_id = $1
ORDER BY name
`

type ListProjectSecretsRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Kind       string
	KeyVersion int32
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	TotalCount int64
}

func (q *Queries) ListProjectSecrets(ctx context.Context, projectID pgtype.UUID) ([]ListProjectSecretsRow, error) {
	rows, err := q.db.Query(ctx, listProjectSecrets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectSecretsRow
	for rows.Next() {
		var i ListProjectSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.KeyVersion,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjects = `-- name: ListProjects :many
SELECT id, project_key, name, description, version, created_at, updated_at,
       COUNT(*) OVER() AS total_count
FROM projects
ORDER BY name, project_key
LIMIT $1
`

type ListProjectsRow struct {
	ID          pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	TotalCount  int64
}

func (q *Queries) ListProjects(ctx context.Context, resultLimit int32) ([]ListProjectsRow, error) {
	rows, err := q.db.Query(ctx, listProjects, resultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsRow
	for rows.Next() {
		var i ListProjectsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupWebhookToken = `-- name: LookupWebhookToken :one
SELECT trigger.project_id, source.id AS source_id, trigger.id AS trigger_id,
       trigger.config AS trigger_config
FROM project_triggers AS trigger
JOIN project_sources AS source
    ON source.project_id = trigger.project_id
   AND source.environment_id = trigger.environment_id
WHERE trigger.ingress_token_hash = $1
  AND trigger.kind = 'signed_webhook'
  AND trigger.enabled
  AND source.enabled
`

type LookupWebhookTokenRow struct {
	ProjectID     pgtype.UUID
	SourceID      pgtype.UUID
	TriggerID     pgtype.UUID
	TriggerConfig []byte
}

func (q *Queries) LookupWebhookToken(ctx context.Context, ingressTokenHash []byte) (LookupWebhookTokenRow, error) {
	row := q.db.QueryRow(ctx, lookupWebhookToken, ingressTokenHash)
	var i LookupWebhookTokenRow
	err := row.Scan(
		&i.ProjectID,
		&i.SourceID,
		&i.TriggerID,
		&i.TriggerConfig,
	)
	return i, err
}

const updateProjectName = `-- name: UpdateProjectName :one
WITH existing_project AS (
    SELECT projects.id, projects.project_key, projects.name, projects.description, projects.version, projects.created_at
    FROM projects
    WHERE projects.id = $1
), changed_project AS (
    UPDATE projects
    SET name = $2,
        version = projects.version + 1,
        updated_at = clock_timestamp()
    WHERE projects.id = $1
    RETURNING id, project_key, name, description, version, created_at, updated_at
), synchronized_environment AS (
    UPDATE project_environments
    SET name = $2,
        version = project_environments.version + 1,
        updated_at = clock_timestamp()
    FROM existing_project
    WHERE project_environments.project_id = existing_project.id
      AND project_environments.name = existing_project.name
)
SELECT id, project_key, name, description, version, created_at, updated_at
FROM changed_project
`

type UpdateProjectNameParams struct {
	ProjectID pgtype.UUID
	Name      string
}

type UpdateProjectNameRow struct {
	ID          pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (UpdateProjectNameRow, error) {
	row := q.db.QueryRow(ctx, updateProjectName, arg.ProjectID, arg.Name)
	var i UpdateProjectNameRow
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectSecret = `-- name: UpdateProjectSecret :one
WITH changed_secret AS (
    UPDATE project_secrets
    SET name = $1,
        ciphertext = $2,
        nonce = $3,
        key_version = $4,
        version = project_secrets.version + 1,
        updated_at = clock_timestamp()
    WHERE project_secrets.project_id = $5 AND project_secrets.id = $6
    RETURNING id, project_id, name, kind, key_version, version, created_at, updated_at
)
SELECT changed_secret.id, changed_secret.project_id, changed_secret.name, changed_secret.kind,
       changed_secret.key_version, changed_secret.version, changed_secret.created_at, changed_secret.updated_at
FROM changed_secret
`

type UpdateProjectSecretParams struct {
	Name       string
	Ciphertext []byte
	Nonce      []byte
	KeyVersion int32
	ProjectID  pgtype.UUID
	SecretID   pgtype.UUID
}

type UpdateProjectSecretRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Kind       string
	KeyVersion int32
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateProjectSecret(ctx context.Context, arg UpdateProjectSecretParams) (UpdateProjectSecretRow, error) {
	row := q.db.QueryRow(ctx, updateProjectSecret,
		arg.Name,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyVersion,
		arg.ProjectID,
		arg.SecretID,
	)
	var i UpdateProjectSecretRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.KeyVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookToken = `-- name: UpdateWebhookToken :one
WITH changed_trigger AS (
    UPDATE project_triggers
    SET ingress_token_hash = $1,
        ingress_token_ciphertext = $2,
        ingress_token_nonce = $3,
        version = project_triggers.version + 1,
        updated_at = clock_timestamp()
    WHERE project_triggers.project_id = $4
      AND project_triggers.kind = 'signed_webhook'
    RETURNING id, project_id, version
)
SELECT id, version
FROM changed_trigger
`

type UpdateWebhookTokenParams struct {
	IngressTokenHash       []byte
	IngressTokenCiphertext []byte
	IngressTokenNonce      []byte
	ProjectID              pgtype.UUID
}

type UpdateWebhookTokenRow struct {
	ID      pgtype.UUID
	Version int64
}

func (q *Queries) UpdateWebhookToken(ctx context.Context, arg UpdateWebhookTokenParams) (UpdateWebhookTokenRow, error) {
	row := q.db.QueryRow(ctx, updateWebhookToken,
		arg.IngressTokenHash,
		arg.IngressTokenCiphertext,
		arg.IngressTokenNonce,
		arg.ProjectID,
	)
	var i UpdateWebhookTokenRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const upsertProjectConfiguration = `-- name: UpsertProjectConfiguration :one
WITH changed_environment AS (
    INSERT INTO project_environments (id, project_id, environment_key, name, service)
    VALUES ($1, $2, $3,
            $4, $5)
    ON CONFLICT (project_id) DO UPDATE
    SET environment_key = EXCLUDED.environment_key,
        name = EXCLUDED.name,
        service = EXCLUDED.service,
        version = project_environments.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, environment_key, name, service, version
), changed_repository AS (
    INSERT INTO project_repositories (
        id, project_id, remote_url, scm_provider, transport, credential_secret_id,
        production_branch, deployed_commit
    ) VALUES (
        $6, $2, $7,
        $8, $9,
        $10, $11,
        $12
    )
    ON CONFLICT (project_id) DO UPDATE
    SET remote_url = EXCLUDED.remote_url,
        scm_provider = EXCLUDED.scm_provider,
        transport = EXCLUDED.transport,
        credential_secret_id = EXCLUDED.credential_secret_id,
        production_branch = EXCLUDED.production_branch,
        deployed_commit = EXCLUDED.deployed_commit,
        version = project_repositories.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, remote_url, scm_provider, transport, credential_secret_id,
              production_branch, deployed_commit, version
), changed_source AS (
    INSERT INTO project_sources (
        id, project_id, environment_id, kind, credential_secret_id,
        config, capabilities, enabled
    )
    SELECT $13, $2, changed_environment.id,
           $14, $15,
           $16, $17, $18
    FROM changed_environment
    ON CONFLICT (project_id) DO UPDATE
    SET environment_id = EXCLUDED.environment_id,
        kind = EXCLUDED.kind,
        credential_secret_id = EXCLUDED.credential_secret_id,
        config = EXCLUDED.config,
        capabilities = EXCLUDED.capabilities,
        enabled = EXCLUDED.enabled,
        version = project_sources.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, kind, credential_secret_id, config, capabilities, enabled, version
), changed_trigger AS (
    INSERT INTO project_triggers (
        id, project_id, environment_id, kind, signing_secret_id, config, enabled,
        ingress_token_hash, ingress_token_ciphertext, ingress_token_nonce
    )
    SELECT $19, $2, changed_environment.id,
           $20, $21,
           $22, $23,
           $24, $25, $26
    FROM changed_environment
    ON CONFLICT (project_id) DO UPDATE
    SET environment_id = EXCLUDED.environment_id,
        kind = EXCLUDED.kind,
        signing_secret_id = EXCLUDED.signing_secret_id,
        config = EXCLUDED.config,
        enabled = EXCLUDED.enabled,
        ingress_token_hash = EXCLUDED.ingress_token_hash,
        ingress_token_ciphertext = EXCLUDED.ingress_token_ciphertext,
        ingress_token_nonce = EXCLUDED.ingress_token_nonce,
        version = project_triggers.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, kind, signing_secret_id, config, enabled, version,
              ingress_token_hash, ingress_token_ciphertext, ingress_token_nonce
), changed_llm AS (
    INSERT INTO project_llm_providers (
        id, project_id, provider, base_url, credential_secret_id, model
    ) VALUES (
        $27, $2, $28,
        $29, $30, $31
    )
    ON CONFLICT (project_id) DO UPDATE
    SET provider = EXCLUDED.provider,
        base_url = EXCLUDED.base_url,
        credential_secret_id = EXCLUDED.credential_secret_id,
        model = EXCLUDED.model,
        version = project_llm_providers.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, provider, base_url, credential_secret_id, model, version
)
SELECT changed_environment.id AS environment_id,
       changed_environment.environment_key, changed_environment.name AS environment_name,
       changed_environment.service, changed_environment.version AS environment_version,
       changed_repository.id AS repository_id, changed_repository.remote_url,
       changed_repository.scm_provider, changed_repository.transport,
       changed_repository.credential_secret_id AS repository_credential_secret_id,
       changed_repository.production_branch, changed_repository.deployed_commit,
       changed_repository.version AS repository_version,
       changed_source.id AS source_id, changed_source.kind AS source_kind,
       changed_source.credential_secret_id AS source_credential_secret_id,
       changed_source.config AS source_config, changed_source.capabilities AS source_capabilities,
       changed_source.enabled AS source_enabled, changed_source.version AS source_version,
       changed_trigger.id AS trigger_id, changed_trigger.kind AS trigger_kind, changed_trigger.signing_secret_id,
       changed_trigger.config AS trigger_config, changed_trigger.enabled AS trigger_enabled,
       changed_trigger.version AS trigger_version,
       changed_trigger.ingress_token_hash, changed_trigger.ingress_token_ciphertext,
       changed_trigger.ingress_token_nonce,
       changed_llm.id AS llm_id, changed_llm.provider AS llm_provider,
       changed_llm.base_url AS llm_base_url,
       changed_llm.credential_secret_id AS llm_credential_secret_id,
       changed_llm.model AS llm_model, changed_llm.version AS llm_version
FROM changed_environment, changed_repository, changed_source, changed_trigger, changed_llm
`

type UpsertProjectConfigurationParams struct {
	EnvironmentID                pgtype.UUID
	ProjectID                    pgtype.UUID
	EnvironmentKey               string
	EnvironmentName              string
	Service                      *string
	RepositoryID                 pgtype.UUID
	RemoteUrl                    string
	ScmProvider                  string
	RepositoryTransport          string
	RepositoryCredentialSecretID pgtype.UUID
	ProductionBranch             string
	DeployedCommit               string
	SourceID                     pgtype.UUID
	SourceKind                   string
	SourceCredentialSecretID     pgtype.UUID
	SourceConfig                 []byte
	SourceCapabilities           []string
	SourceEnabled                bool
	TriggerID                    pgtype.UUID
	TriggerKind                  string
	SigningSecretID              pgtype.UUID
	TriggerConfig                []byte
	TriggerEnabled               bool
	IngressTokenHash             []byte
	IngressTokenCiphertext       []byte
	IngressTokenNonce            []byte
	LlmID                        pgtype.UUID
	LlmProvider                  string
	LlmBaseUrl                   string
	LlmCredentialSecretID        pgtype.UUID
	LlmModel                     string
}

type UpsertProjectConfigurationRow struct {
	EnvironmentID                pgtype.UUID
	EnvironmentKey               string
	EnvironmentName              string
	Service                      *string
	EnvironmentVersion           int64
	RepositoryID                 pgtype.UUID
	RemoteUrl                    string
	ScmProvider                  string
	Transport                    string
	RepositoryCredentialSecretID pgtype.UUID
	ProductionBranch             string
	DeployedCommit               string
	RepositoryVersion            int64
	SourceID                     pgtype.UUID
	SourceKind                   string
	SourceCredentialSecretID     pgtype.UUID
	SourceConfig                 []byte
	SourceCapabilities           []string
	SourceEnabled                bool
	SourceVersion                int64
	TriggerID                    pgtype.UUID
	TriggerKind                  string
	SigningSecretID              pgtype.UUID
	TriggerConfig                []byte
	TriggerEnabled               bool
	TriggerVersion               int64
	IngressTokenHash             []byte
	IngressTokenCiphertext       []byte
	IngressTokenNonce            []byte
	LlmID                        pgtype.UUID
	LlmProvider                  string
	LlmBaseUrl                   string
	LlmCredentialSecretID        pgtype.UUID
	LlmModel                     string
	LlmVersion                   int64
}

func (q *Queries) UpsertProjectConfiguration(ctx context.Context, arg UpsertProjectConfigurationParams) (UpsertProjectConfigurationRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectConfiguration,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.EnvironmentKey,
		arg.EnvironmentName,
		arg.Service,
		arg.RepositoryID,
		arg.RemoteUrl,
		arg.ScmProvider,
		arg.RepositoryTransport,
		arg.RepositoryCredentialSecretID,
		arg.ProductionBranch,
		arg.DeployedCommit,
		arg.SourceID,
		arg.SourceKind,
		arg.SourceCredentialSecretID,
		arg.SourceConfig,
		arg.SourceCapabilities,
		arg.SourceEnabled,
		arg.TriggerID,
		arg.TriggerKind,
		arg.SigningSecretID,
		arg.TriggerConfig,
		arg.TriggerEnabled,
		arg.IngressTokenHash,
		arg.IngressTokenCiphertext,
		arg.IngressTokenNonce,
		arg.LlmID,
		arg.LlmProvider,
		arg.LlmBaseUrl,
		arg.LlmCredentialSecretID,
		arg.LlmModel,
	)
	var i UpsertProjectConfigurationRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentKey,
		&i.EnvironmentName,
		&i.Service,
		&i.EnvironmentVersion,
		&i.RepositoryID,
		&i.RemoteUrl,
		&i.ScmProvider,
		&i.Transport,
		&i.RepositoryCredentialSecretID,
		&i.ProductionBranch,
		&i.DeployedCommit,
		&i.RepositoryVersion,
		&i.SourceID,
		&i.SourceKind,
		&i.SourceCredentialSecretID,
		&i.SourceConfig,
		&i.SourceCapabilities,
		&i.SourceEnabled,
		&i.SourceVersion,
		&i.TriggerID,
		&i.TriggerKind,
		&i.SigningSecretID,
		&i.TriggerConfig,
		&i.TriggerEnabled,
		&i.TriggerVersion,
		&i.IngressTokenHash,
		&i.IngressTokenCiphertext,
		&i.IngressTokenNonce,
		&i.LlmID,
		&i.LlmProvider,
		&i.LlmBaseUrl,
		&i.LlmCredentialSecretID,
		&i.LlmModel,
		&i.LlmVersion,
	)
	return i, err
}

const upsertProjectEnvironment = `-- name: UpsertProjectEnvironment :one
WITH changed_environment AS (
    INSERT INTO project_environments (id, project_id, environment_key, name, service)
    VALUES ($1, $2, $3,
            $4, $5)
    ON CONFLICT (project_id) DO UPDATE
    SET environment_key = EXCLUDED.environment_key,
        name = EXCLUDED.name,
        service = EXCLUDED.service,
        version = project_environments.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, environment_key, name, service, version
)
SELECT id, environment_key, name, service, version
FROM changed_environment
`

type UpsertProjectEnvironmentParams struct {
	EnvironmentID   pgtype.UUID
	ProjectID       pgtype.UUID
	EnvironmentKey  string
	EnvironmentName string
	Service         *string
}

type UpsertProjectEnvironmentRow struct {
	ID             pgtype.UUID
	EnvironmentKey string
	Name           string
	Service        *string
	Version        int64
}

func (q *Queries) UpsertProjectEnvironment(ctx context.Context, arg UpsertProjectEnvironmentParams) (UpsertProjectEnvironmentRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectEnvironment,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.EnvironmentKey,
		arg.EnvironmentName,
		arg.Service,
	)
	var i UpsertProjectEnvironmentRow
	err := row.Scan(
		&i.ID,
		&i.EnvironmentKey,
		&i.Name,
		&i.Service,
		&i.Version,
	)
	return i, err
}

const upsertProjectLLMProvider = `-- name: UpsertProjectLLMProvider :one
WITH changed_llm AS (
    INSERT INTO project_llm_providers (
        id, project_id, provider, base_url, credential_secret_id, model
    ) VALUES (
        $1, $2, $3,
        $4, $5, $6
    )
    ON CONFLICT (project_id) DO UPDATE
    SET provider = EXCLUDED.provider,
        base_url = EXCLUDED.base_url,
        credential_secret_id = EXCLUDED.credential_secret_id,
        model = EXCLUDED.model,
        version = project_llm_providers.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, provider, base_url, credential_secret_id, model, version
)
SELECT id, provider, base_url, credential_secret_id, model, version
FROM changed_llm
`

type UpsertProjectLLMProviderParams struct {
	LlmID                 pgtype.UUID
	ProjectID             pgtype.UUID
	LlmProvider           string
	LlmBaseUrl            string
	LlmCredentialSecretID pgtype.UUID
	LlmModel              string
}

type UpsertProjectLLMProviderRow struct {
	ID                 pgtype.UUID
	Provider           string
	BaseUrl            string
	CredentialSecretID pgtype.UUID
	Model              string
	Version            int64
}

func (q *Queries) UpsertProjectLLMProvider(ctx context.Context, arg UpsertProjectLLMProviderParams) (UpsertProjectLLMProviderRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectLLMProvider,
		arg.LlmID,
		arg.ProjectID,
		arg.LlmProvider,
		arg.LlmBaseUrl,
		arg.LlmCredentialSecretID,
		arg.LlmModel,
	)
	var i UpsertProjectLLMProviderRow
	err := row.Scan(
		&i.ID,
		&i.Provider,
		&i.BaseUrl,
		&i.CredentialSecretID,
		&i.Model,
		&i.Version,
	)
	return i, err
}

const upsertProjectRemediationPolicy = `-- name: UpsertProjectRemediationPolicy :one
WITH changed_policy AS (
    UPDATE projects
    SET agent_loop_mode = $1,
        agent_loop_policy_version = projects.agent_loop_policy_version + 1,
        version = projects.version + 1,
        updated_at = clock_timestamp()
    WHERE projects.id = $2
    RETURNING id, agent_loop_mode, agent_loop_policy_version
)
SELECT agent_loop_mode, agent_loop_policy_version
FROM changed_policy
`

type UpsertProjectRemediationPolicyParams struct {
	AgentLoopMode string
	ProjectID     pgtype.UUID
}

type UpsertProjectRemediationPolicyRow struct {
	AgentLoopMode          string
	AgentLoopPolicyVersion int64
}

func (q *Queries) UpsertProjectRemediationPolicy(ctx context.Context, arg UpsertProjectRemediationPolicyParams) (UpsertProjectRemediationPolicyRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectRemediationPolicy, arg.AgentLoopMode, arg.ProjectID)
	var i UpsertProjectRemediationPolicyRow
	err := row.Scan(&i.AgentLoopMode, &i.AgentLoopPolicyVersion)
	return i, err
}

const upsertProjectRepository = `-- name: UpsertProjectRepository :one
WITH changed_repository AS (
    INSERT INTO project_repositories (
        id, project_id, remote_url, scm_provider, transport, credential_secret_id,
        production_branch, deployed_commit
    ) VALUES (
        $1, $2, $3,
        $4, $5,
        $6, $7, $8
    )
    ON CONFLICT (project_id) DO UPDATE
    SET remote_url = EXCLUDED.remote_url,
        scm_provider = EXCLUDED.scm_provider,
        transport = EXCLUDED.transport,
        credential_secret_id = EXCLUDED.credential_secret_id,
        production_branch = EXCLUDED.production_branch,
        deployed_commit = EXCLUDED.deployed_commit,
        version = project_repositories.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, remote_url, scm_provider, transport, credential_secret_id,
              production_branch, deployed_commit, version
)
SELECT id, remote_url, scm_provider, transport, credential_secret_id,
       production_branch, deployed_commit, version
FROM changed_repository
`

type UpsertProjectRepositoryParams struct {
	RepositoryID        pgtype.UUID
	ProjectID           pgtype.UUID
	RemoteUrl           string
	ScmProvider         string
	RepositoryTransport string
	CredentialSecretID  pgtype.UUID
	ProductionBranch    string
	DeployedCommit      string
}

type UpsertProjectRepositoryRow struct {
	ID                 pgtype.UUID
	RemoteUrl          string
	ScmProvider        string
	Transport          string
	CredentialSecretID pgtype.UUID
	ProductionBranch   string
	DeployedCommit     string
	Version            int64
}

func (q *Queries) UpsertProjectRepository(ctx context.Context, arg UpsertProjectRepositoryParams) (UpsertProjectRepositoryRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectRepository,
		arg.RepositoryID,
		arg.ProjectID,
		arg.RemoteUrl,
		arg.ScmProvider,
		arg.RepositoryTransport,
		arg.CredentialSecretID,
		arg.ProductionBranch,
		arg.DeployedCommit,
	)
	var i UpsertProjectRepositoryRow
	err := row.Scan(
		&i.ID,
		&i.RemoteUrl,
		&i.ScmProvider,
		&i.Transport,
		&i.CredentialSecretID,
		&i.ProductionBranch,
		&i.DeployedCommit,
		&i.Version,
	)
	return i, err
}

const upsertProjectSource = `-- name: UpsertProjectSource :one
WITH changed_source AS (
    INSERT INTO project_sources (
        id, project_id, environment_id, kind, credential_secret_id, config, capabilities, enabled
    ) VALUES (
        $1, $2, $3, $4,
        $5, $6, $7, $8
    )
    ON CONFLICT (project_id) DO UPDATE
    SET environment_id = EXCLUDED.environment_id,
        kind = EXCLUDED.kind,
        credential_secret_id = EXCLUDED.credential_secret_id,
        config = EXCLUDED.config,
        capabilities = EXCLUDED.capabilities,
        enabled = EXCLUDED.enabled,
        version = project_sources.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, kind, credential_secret_id, config, capabilities, enabled, version
)
SELECT id, kind, credential_secret_id, config, capabilities, enabled, version
FROM changed_source
`

type UpsertProjectSourceParams struct {
	SourceID           pgtype.UUID
	ProjectID          pgtype.UUID
	EnvironmentID      pgtype.UUID
	SourceKind         string
	CredentialSecretID pgtype.UUID
	SourceConfig       []byte
	SourceCapabilities []string
	SourceEnabled      bool
}

type UpsertProjectSourceRow struct {
	ID                 pgtype.UUID
	Kind               string
	CredentialSecretID pgtype.UUID
	Config             []byte
	Capabilities       []string
	Enabled            bool
	Version            int64
}

func (q *Queries) UpsertProjectSource(ctx context.Context, arg UpsertProjectSourceParams) (UpsertProjectSourceRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectSource,
		arg.SourceID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.SourceKind,
		arg.CredentialSecretID,
		arg.SourceConfig,
		arg.SourceCapabilities,
		arg.SourceEnabled,
	)
	var i UpsertProjectSourceRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.CredentialSecretID,
		&i.Config,
		&i.Capabilities,
		&i.Enabled,
		&i.Version,
	)
	return i, err
}

const upsertProjectTrigger = `-- name: UpsertProjectTrigger :one
WITH changed_trigger AS (
    INSERT INTO project_triggers (
        id, project_id, environment_id, kind, signing_secret_id, config, enabled,
        ingress_token_hash, ingress_token_ciphertext, ingress_token_nonce
    ) VALUES (
        $1, $2, $3, $4,
        $5, $6, $7,
        $8, $9, $10
    )
    ON CONFLICT (project_id) DO UPDATE
    SET environment_id = EXCLUDED.environment_id,
        kind = EXCLUDED.kind,
        signing_secret_id = EXCLUDED.signing_secret_id,
        config = EXCLUDED.config,
        enabled = EXCLUDED.enabled,
        ingress_token_hash = EXCLUDED.ingress_token_hash,
        ingress_token_ciphertext = EXCLUDED.ingress_token_ciphertext,
        ingress_token_nonce = EXCLUDED.ingress_token_nonce,
        version = project_triggers.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, kind, signing_secret_id, config, enabled, version,
              ingress_token_hash, ingress_token_ciphertext, ingress_token_nonce
)
SELECT id, kind, signing_secret_id, config, enabled, version,
       ingress_token_hash, ingress_token_ciphertext, ingress_token_nonce
FROM changed_trigger
`

type UpsertProjectTriggerParams struct {
	TriggerID              pgtype.UUID
	ProjectID              pgtype.UUID
	EnvironmentID          pgtype.UUID
	TriggerKind            string
	SigningSecretID        pgtype.UUID
	TriggerConfig          []byte
	TriggerEnabled         bool
	IngressTokenHash       []byte
	IngressTokenCiphertext []byte
	IngressTokenNonce      []byte
}

type UpsertProjectTriggerRow struct {
	ID                     pgtype.UUID
	Kind                   string
	SigningSecretID        pgtype.UUID
	Config                 []byte
	Enabled                bool
	Version                int64
	IngressTokenHash       []byte
	IngressTokenCiphertext []byte
	IngressTokenNonce      []byte
}

func (q *Queries) UpsertProjectTrigger(ctx context.Context, arg UpsertProjectTriggerParams) (UpsertProjectTriggerRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectTrigger,
		arg.TriggerID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.TriggerKind,
		arg.SigningSecretID,
		arg.TriggerConfig,
		arg.TriggerEnabled,
		arg.IngressTokenHash,
		arg.IngressTokenCiphertext,
		arg.IngressTokenNonce,
	)
	var i UpsertProjectTriggerRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.SigningSecretID,
		&i.Config,
		&i.Enabled,
		&i.Version,
		&i.IngressTokenHash,
		&i.IngressTokenCiphertext,
		&i.IngressTokenNonce,
	)
	return i, err
}
