// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package projectdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
WITH created_project AS (
    INSERT INTO projects (id, project_key, name, description)
    VALUES ($1, $2, $3, $4)
    RETURNING id, project_key, name, description, version, created_at, updated_at
), created_membership AS (
    INSERT INTO project_memberships (project_id, user_id, role)
    SELECT id, $5, 'admin'
    FROM created_project
), created_audit AS (
    INSERT INTO audit_events (id, project_id, actor_user_id, action, target_type, target_id, summary, metadata)
    SELECT $6, id, $5, 'project.created', 'project', id,
           'Project created.', jsonb_build_object('projectKey', project_key)
    FROM created_project
)
SELECT id, project_key, name, description, 'admin'::text AS role, version, created_at, updated_at
FROM created_project
`

type CreateProjectParams struct {
	ProjectID   pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
	ActorUserID pgtype.UUID
	AuditID     pgtype.UUID
}

type CreateProjectRow struct {
	ID          pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
	Role        string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.ProjectID,
		arg.ProjectKey,
		arg.Name,
		arg.Description,
		arg.ActorUserID,
		arg.AuditID,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createProjectSecret = `-- name: CreateProjectSecret :one
WITH created_secret AS (
    INSERT INTO project_secrets (id, project_id, name, kind, ciphertext, nonce, key_version)
    VALUES ($1, $2, $3, $4,
            $5, $6, $7)
    RETURNING id, project_id, name, kind, key_version, version, created_at, updated_at
), created_audit AS (
    INSERT INTO audit_events (id, project_id, actor_user_id, action, target_type, target_id, summary, metadata)
    SELECT $8, project_id, $9, 'project.secret.created',
           'project_secret', id, 'Project credential created.',
           jsonb_build_object('name', name, 'kind', kind)
    FROM created_secret
)
SELECT id, project_id, name, kind, key_version, version, created_at, updated_at
FROM created_secret
`

type CreateProjectSecretParams struct {
	SecretID    pgtype.UUID
	ProjectID   pgtype.UUID
	Name        string
	Kind        string
	Ciphertext  []byte
	Nonce       []byte
	KeyVersion  int32
	AuditID     pgtype.UUID
	ActorUserID pgtype.UUID
}

type CreateProjectSecretRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Kind       string
	KeyVersion int32
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) CreateProjectSecret(ctx context.Context, arg CreateProjectSecretParams) (CreateProjectSecretRow, error) {
	row := q.db.QueryRow(ctx, createProjectSecret,
		arg.SecretID,
		arg.ProjectID,
		arg.Name,
		arg.Kind,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyVersion,
		arg.AuditID,
		arg.ActorUserID,
	)
	var i CreateProjectSecretRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.KeyVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProjectMember = `-- name: DeleteProjectMember :one
WITH target_membership AS (
    SELECT pm.user_id, u.username, pm.role
    FROM project_memberships AS pm
    JOIN users AS u ON u.id = pm.user_id
    WHERE pm.project_id = $1
      AND u.username = $2
      AND (
          pm.role <> 'admin'
          OR EXISTS (
              SELECT 1
              FROM project_memberships AS another_admin
              WHERE another_admin.project_id = pm.project_id
                AND another_admin.role = 'admin'
                AND another_admin.user_id <> pm.user_id
          )
      )
), deleted_membership AS (
    DELETE FROM project_memberships
    WHERE project_id = $1
      AND user_id = (SELECT user_id FROM target_membership)
    RETURNING user_id
), created_audit AS (
    INSERT INTO audit_events (id, project_id, actor_user_id, action, target_type, target_id, summary, metadata)
    SELECT $3, $1, $4,
           'project.member.removed', 'project_membership', deleted_membership.user_id,
           'Project member removed.', jsonb_build_object('username', target_membership.username)
    FROM deleted_membership
    JOIN target_membership ON target_membership.user_id = deleted_membership.user_id
)
SELECT target_membership.user_id, target_membership.username, target_membership.role
FROM target_membership
JOIN deleted_membership ON deleted_membership.user_id = target_membership.user_id
`

type DeleteProjectMemberParams struct {
	ProjectID   pgtype.UUID
	Username    string
	AuditID     pgtype.UUID
	ActorUserID pgtype.UUID
}

type DeleteProjectMemberRow struct {
	UserID   pgtype.UUID
	Username string
	Role     string
}

func (q *Queries) DeleteProjectMember(ctx context.Context, arg DeleteProjectMemberParams) (DeleteProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, deleteProjectMember,
		arg.ProjectID,
		arg.Username,
		arg.AuditID,
		arg.ActorUserID,
	)
	var i DeleteProjectMemberRow
	err := row.Scan(&i.UserID, &i.Username, &i.Role)
	return i, err
}

const getEnabledProjectUser = `-- name: GetEnabledProjectUser :one
SELECT id, username
FROM users
WHERE username = $1 AND enabled
`

type GetEnabledProjectUserRow struct {
	ID       pgtype.UUID
	Username string
}

func (q *Queries) GetEnabledProjectUser(ctx context.Context, username string) (GetEnabledProjectUserRow, error) {
	row := q.db.QueryRow(ctx, getEnabledProjectUser, username)
	var i GetEnabledProjectUserRow
	err := row.Scan(&i.ID, &i.Username)
	return i, err
}

const getProjectAccess = `-- name: GetProjectAccess :one
SELECT p.id, p.project_key, p.name, p.description,
       COALESCE(CASE WHEN $1::boolean THEN 'admin'::text ELSE pm.role END, 'admin')::text AS role,
       p.version, p.created_at, p.updated_at
FROM projects AS p
LEFT JOIN project_memberships AS pm
    ON pm.project_id = p.id AND pm.user_id = $2
WHERE p.project_key = $3
  AND ($1::boolean OR pm.user_id IS NOT NULL)
`

type GetProjectAccessParams struct {
	SystemAdmin bool
	UserID      pgtype.UUID
	ProjectKey  string
}

type GetProjectAccessRow struct {
	ID          pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
	Role        string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) GetProjectAccess(ctx context.Context, arg GetProjectAccessParams) (GetProjectAccessRow, error) {
	row := q.db.QueryRow(ctx, getProjectAccess, arg.SystemAdmin, arg.UserID, arg.ProjectKey)
	var i GetProjectAccessRow
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectConfiguration = `-- name: GetProjectConfiguration :one
SELECT e.id AS environment_id, e.environment_key, e.name AS environment_name, e.service,
       e.version AS environment_version,
       r.id AS repository_id, r.remote_url, r.scm_provider, r.transport,
       r.credential_secret_id AS repository_credential_secret_id,
       r.production_branch, r.deployed_commit, r.version AS repository_version,
       s.id AS source_id, s.name AS source_name, s.kind AS source_kind,
       s.credential_secret_id AS source_credential_secret_id, s.config AS source_config,
       s.capabilities AS source_capabilities, s.enabled AS source_enabled, s.version AS source_version,
       t.id AS trigger_id, t.name AS trigger_name, t.kind AS trigger_kind,
       t.signing_secret_id, t.config AS trigger_config, t.enabled AS trigger_enabled,
       t.version AS trigger_version,
       t.ingress_token_hash, t.ingress_token_ciphertext, t.ingress_token_nonce,
       l.id AS llm_id, l.provider AS llm_provider, l.base_url AS llm_base_url,
       l.credential_secret_id AS llm_credential_secret_id, l.model AS llm_model,
       l.version AS llm_version
FROM project_environments AS e
JOIN project_repositories AS r ON r.project_id = e.project_id
JOIN project_sources AS s ON s.project_id = e.project_id AND s.environment_id = e.id
JOIN project_triggers AS t ON t.project_id = e.project_id AND t.environment_id = e.id
LEFT JOIN project_llm_providers AS l ON l.project_id = e.project_id
WHERE e.project_id = $1
ORDER BY e.created_at
LIMIT 1
`

type GetProjectConfigurationRow struct {
	EnvironmentID                pgtype.UUID
	EnvironmentKey               string
	EnvironmentName              string
	Service                      *string
	EnvironmentVersion           int64
	RepositoryID                 pgtype.UUID
	RemoteUrl                    string
	ScmProvider                  string
	Transport                    string
	RepositoryCredentialSecretID pgtype.UUID
	ProductionBranch             string
	DeployedCommit               string
	RepositoryVersion            int64
	SourceID                     pgtype.UUID
	SourceName                   string
	SourceKind                   string
	SourceCredentialSecretID     pgtype.UUID
	SourceConfig                 []byte
	SourceCapabilities           []string
	SourceEnabled                bool
	SourceVersion                int64
	TriggerID                    pgtype.UUID
	TriggerName                  string
	TriggerKind                  string
	SigningSecretID              pgtype.UUID
	TriggerConfig                []byte
	TriggerEnabled               bool
	TriggerVersion               int64
	IngressTokenHash             []byte
	IngressTokenCiphertext       []byte
	IngressTokenNonce            []byte
	LlmID                        pgtype.UUID
	LlmProvider                  *string
	LlmBaseUrl                   *string
	LlmCredentialSecretID        pgtype.UUID
	LlmModel                     *string
	LlmVersion                   *int64
}

func (q *Queries) GetProjectConfiguration(ctx context.Context, projectID pgtype.UUID) (GetProjectConfigurationRow, error) {
	row := q.db.QueryRow(ctx, getProjectConfiguration, projectID)
	var i GetProjectConfigurationRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentKey,
		&i.EnvironmentName,
		&i.Service,
		&i.EnvironmentVersion,
		&i.RepositoryID,
		&i.RemoteUrl,
		&i.ScmProvider,
		&i.Transport,
		&i.RepositoryCredentialSecretID,
		&i.ProductionBranch,
		&i.DeployedCommit,
		&i.RepositoryVersion,
		&i.SourceID,
		&i.SourceName,
		&i.SourceKind,
		&i.SourceCredentialSecretID,
		&i.SourceConfig,
		&i.SourceCapabilities,
		&i.SourceEnabled,
		&i.SourceVersion,
		&i.TriggerID,
		&i.TriggerName,
		&i.TriggerKind,
		&i.SigningSecretID,
		&i.TriggerConfig,
		&i.TriggerEnabled,
		&i.TriggerVersion,
		&i.IngressTokenHash,
		&i.IngressTokenCiphertext,
		&i.IngressTokenNonce,
		&i.LlmID,
		&i.LlmProvider,
		&i.LlmBaseUrl,
		&i.LlmCredentialSecretID,
		&i.LlmModel,
		&i.LlmVersion,
	)
	return i, err
}

const getProjectMemberByUsername = `-- name: GetProjectMemberByUsername :one
SELECT u.id AS user_id, u.username, pm.role, pm.version, pm.created_at, pm.updated_at
FROM project_memberships AS pm
JOIN users AS u ON u.id = pm.user_id
WHERE pm.project_id = $1
  AND u.username = $2
`

type GetProjectMemberByUsernameParams struct {
	ProjectID pgtype.UUID
	Username  string
}

type GetProjectMemberByUsernameRow struct {
	UserID    pgtype.UUID
	Username  string
	Role      string
	Version   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) GetProjectMemberByUsername(ctx context.Context, arg GetProjectMemberByUsernameParams) (GetProjectMemberByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getProjectMemberByUsername, arg.ProjectID, arg.Username)
	var i GetProjectMemberByUsernameRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getProjectSecret = `-- name: GetProjectSecret :one
SELECT id, project_id, name, kind, ciphertext, nonce, key_version, version, created_at, updated_at
FROM project_secrets
WHERE project_id = $1 AND id = $2
`

type GetProjectSecretParams struct {
	ProjectID pgtype.UUID
	SecretID  pgtype.UUID
}

func (q *Queries) GetProjectSecret(ctx context.Context, arg GetProjectSecretParams) (ProjectSecret, error) {
	row := q.db.QueryRow(ctx, getProjectSecret, arg.ProjectID, arg.SecretID)
	var i ProjectSecret
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.Ciphertext,
		&i.Nonce,
		&i.KeyVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProjectAuditEvents = `-- name: ListProjectAuditEvents :many
SELECT id, project_id, actor_user_id, action, target_type, target_id, summary, metadata, occurred_at,
       COUNT(*) OVER() AS total_count
FROM audit_events
WHERE project_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListProjectAuditEventsParams struct {
	ProjectID   pgtype.UUID
	ResultLimit int32
}

type ListProjectAuditEventsRow struct {
	ID          pgtype.UUID
	ProjectID   pgtype.UUID
	ActorUserID pgtype.UUID
	Action      string
	TargetType  string
	TargetID    pgtype.UUID
	Summary     string
	Metadata    []byte
	OccurredAt  pgtype.Timestamptz
	TotalCount  int64
}

func (q *Queries) ListProjectAuditEvents(ctx context.Context, arg ListProjectAuditEventsParams) ([]ListProjectAuditEventsRow, error) {
	rows, err := q.db.Query(ctx, listProjectAuditEvents, arg.ProjectID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectAuditEventsRow
	for rows.Next() {
		var i ListProjectAuditEventsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.ActorUserID,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Summary,
			&i.Metadata,
			&i.OccurredAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id AS user_id, u.username, pm.role, pm.version, pm.created_at, pm.updated_at,
       COUNT(*) OVER() AS total_count
FROM project_memberships AS pm
JOIN users AS u ON u.id = pm.user_id
WHERE pm.project_id = $1
ORDER BY u.username
`

type ListProjectMembersRow struct {
	UserID     pgtype.UUID
	Username   string
	Role       string
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	TotalCount int64
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID pgtype.UUID) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.UserID,
			&i.Username,
			&i.Role,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectSecrets = `-- name: ListProjectSecrets :many
SELECT id, project_id, name, kind, key_version, version, created_at, updated_at,
       COUNT(*) OVER() AS total_count
FROM project_secrets
WHERE project_id = $1
ORDER BY name
`

type ListProjectSecretsRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Kind       string
	KeyVersion int32
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
	TotalCount int64
}

func (q *Queries) ListProjectSecrets(ctx context.Context, projectID pgtype.UUID) ([]ListProjectSecretsRow, error) {
	rows, err := q.db.Query(ctx, listProjectSecrets, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectSecretsRow
	for rows.Next() {
		var i ListProjectSecretsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Kind,
			&i.KeyVersion,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsForUser = `-- name: ListProjectsForUser :many
SELECT p.id, p.project_key, p.name, p.description,
       COALESCE(CASE WHEN $1::boolean THEN 'admin'::text ELSE pm.role END, 'admin')::text AS role,
       p.version, p.created_at, p.updated_at,
       COUNT(*) OVER() AS total_count
FROM projects AS p
LEFT JOIN project_memberships AS pm
    ON pm.project_id = p.id AND pm.user_id = $2
WHERE $1::boolean OR pm.user_id IS NOT NULL
ORDER BY p.name, p.project_key
LIMIT $3
`

type ListProjectsForUserParams struct {
	SystemAdmin bool
	UserID      pgtype.UUID
	ResultLimit int32
}

type ListProjectsForUserRow struct {
	ID          pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
	Role        string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
	TotalCount  int64
}

func (q *Queries) ListProjectsForUser(ctx context.Context, arg ListProjectsForUserParams) ([]ListProjectsForUserRow, error) {
	rows, err := q.db.Query(ctx, listProjectsForUser, arg.SystemAdmin, arg.UserID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectsForUserRow
	for rows.Next() {
		var i ListProjectsForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectKey,
			&i.Name,
			&i.Description,
			&i.Role,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupWebhookToken = `-- name: LookupWebhookToken :one
SELECT trigger.project_id, source.id AS source_id
FROM project_triggers AS trigger
JOIN project_sources AS source
    ON source.project_id = trigger.project_id
   AND source.environment_id = trigger.environment_id
WHERE trigger.ingress_token_hash = $1
  AND trigger.kind = 'signed_webhook'
  AND trigger.enabled
  AND source.enabled
`

type LookupWebhookTokenRow struct {
	ProjectID pgtype.UUID
	SourceID  pgtype.UUID
}

func (q *Queries) LookupWebhookToken(ctx context.Context, ingressTokenHash []byte) (LookupWebhookTokenRow, error) {
	row := q.db.QueryRow(ctx, lookupWebhookToken, ingressTokenHash)
	var i LookupWebhookTokenRow
	err := row.Scan(&i.ProjectID, &i.SourceID)
	return i, err
}

const updateProjectName = `-- name: UpdateProjectName :one
WITH existing_project AS (
    SELECT projects.id, projects.project_key, projects.name, projects.description, projects.version, projects.created_at
    FROM projects
    WHERE projects.id = $2
), changed_project AS (
    UPDATE projects
    SET name = $3,
        version = projects.version + 1,
        updated_at = clock_timestamp()
    WHERE projects.id = $2
    RETURNING id, project_key, name, description, version, created_at, updated_at
), synchronized_environment AS (
    UPDATE project_environments
    SET name = $3,
        version = project_environments.version + 1,
        updated_at = clock_timestamp()
    FROM existing_project
    WHERE project_environments.project_id = existing_project.id
      AND project_environments.name = existing_project.name
), created_audit AS (
    INSERT INTO audit_events (id, project_id, actor_user_id, action, target_type, target_id, summary, metadata)
    SELECT $4, changed_project.id, $5,
           'project.renamed', 'project', changed_project.id,
           'Project renamed.', jsonb_build_object('projectKey', changed_project.project_key)
    FROM changed_project
)
SELECT changed_project.id, changed_project.project_key, changed_project.name, changed_project.description,
       $1::text AS role, changed_project.version, changed_project.created_at, changed_project.updated_at
FROM changed_project
`

type UpdateProjectNameParams struct {
	Role        string
	ProjectID   pgtype.UUID
	Name        string
	AuditID     pgtype.UUID
	ActorUserID pgtype.UUID
}

type UpdateProjectNameRow struct {
	ID          pgtype.UUID
	ProjectKey  string
	Name        string
	Description string
	Role        string
	Version     int64
	CreatedAt   pgtype.Timestamptz
	UpdatedAt   pgtype.Timestamptz
}

func (q *Queries) UpdateProjectName(ctx context.Context, arg UpdateProjectNameParams) (UpdateProjectNameRow, error) {
	row := q.db.QueryRow(ctx, updateProjectName,
		arg.Role,
		arg.ProjectID,
		arg.Name,
		arg.AuditID,
		arg.ActorUserID,
	)
	var i UpdateProjectNameRow
	err := row.Scan(
		&i.ID,
		&i.ProjectKey,
		&i.Name,
		&i.Description,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProjectSecret = `-- name: UpdateProjectSecret :one
WITH changed_secret AS (
    UPDATE project_secrets
    SET name = $1,
        ciphertext = $2,
        nonce = $3,
        key_version = $4,
        version = project_secrets.version + 1,
        updated_at = clock_timestamp()
    WHERE project_secrets.project_id = $5 AND project_secrets.id = $6
    RETURNING id, project_id, name, kind, key_version, version, created_at, updated_at
), created_audit AS (
    INSERT INTO audit_events (id, project_id, actor_user_id, action, target_type, target_id, summary, metadata)
    SELECT $7, changed_secret.project_id, $8, 'project.secret.updated',
           'project_secret', changed_secret.id, 'Project credential updated.',
           jsonb_build_object('name', changed_secret.name, 'kind', changed_secret.kind, 'rotated', $9::boolean)
    FROM changed_secret
)
SELECT changed_secret.id, changed_secret.project_id, changed_secret.name, changed_secret.kind,
       changed_secret.key_version, changed_secret.version, changed_secret.created_at, changed_secret.updated_at
FROM changed_secret
`

type UpdateProjectSecretParams struct {
	Name        string
	Ciphertext  []byte
	Nonce       []byte
	KeyVersion  int32
	ProjectID   pgtype.UUID
	SecretID    pgtype.UUID
	AuditID     pgtype.UUID
	ActorUserID pgtype.UUID
	Rotated     bool
}

type UpdateProjectSecretRow struct {
	ID         pgtype.UUID
	ProjectID  pgtype.UUID
	Name       string
	Kind       string
	KeyVersion int32
	Version    int64
	CreatedAt  pgtype.Timestamptz
	UpdatedAt  pgtype.Timestamptz
}

func (q *Queries) UpdateProjectSecret(ctx context.Context, arg UpdateProjectSecretParams) (UpdateProjectSecretRow, error) {
	row := q.db.QueryRow(ctx, updateProjectSecret,
		arg.Name,
		arg.Ciphertext,
		arg.Nonce,
		arg.KeyVersion,
		arg.ProjectID,
		arg.SecretID,
		arg.AuditID,
		arg.ActorUserID,
		arg.Rotated,
	)
	var i UpdateProjectSecretRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Kind,
		&i.KeyVersion,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateWebhookToken = `-- name: UpdateWebhookToken :one
WITH changed_trigger AS (
    UPDATE project_triggers
    SET ingress_token_hash = $1,
        ingress_token_ciphertext = $2,
        ingress_token_nonce = $3,
        version = project_triggers.version + 1,
        updated_at = clock_timestamp()
    WHERE project_triggers.project_id = $4
      AND project_triggers.kind = 'signed_webhook'
    RETURNING id, project_id, version
), created_audit AS (
    INSERT INTO audit_events (id, project_id, actor_user_id, action, target_type, target_id, summary, metadata)
    SELECT $5, changed_trigger.project_id, $6,
           'project.trigger.webhook_token', 'project_trigger', changed_trigger.id,
           'Project webhook token updated.',
           jsonb_build_object('rotated', $7::boolean)
    FROM changed_trigger
)
SELECT id, version
FROM changed_trigger
`

type UpdateWebhookTokenParams struct {
	IngressTokenHash       []byte
	IngressTokenCiphertext []byte
	IngressTokenNonce      []byte
	ProjectID              pgtype.UUID
	AuditID                pgtype.UUID
	ActorUserID            pgtype.UUID
	Rotated                bool
}

type UpdateWebhookTokenRow struct {
	ID      pgtype.UUID
	Version int64
}

func (q *Queries) UpdateWebhookToken(ctx context.Context, arg UpdateWebhookTokenParams) (UpdateWebhookTokenRow, error) {
	row := q.db.QueryRow(ctx, updateWebhookToken,
		arg.IngressTokenHash,
		arg.IngressTokenCiphertext,
		arg.IngressTokenNonce,
		arg.ProjectID,
		arg.AuditID,
		arg.ActorUserID,
		arg.Rotated,
	)
	var i UpdateWebhookTokenRow
	err := row.Scan(&i.ID, &i.Version)
	return i, err
}

const upsertProjectConfiguration = `-- name: UpsertProjectConfiguration :one
WITH changed_environment AS (
    INSERT INTO project_environments (id, project_id, environment_key, name, service)
    VALUES ($1, $2, $3,
            $4, $5)
    ON CONFLICT (project_id) DO UPDATE
    SET environment_key = EXCLUDED.environment_key,
        name = EXCLUDED.name,
        service = EXCLUDED.service,
        version = project_environments.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, environment_key, name, service, version
), changed_repository AS (
    INSERT INTO project_repositories (
        id, project_id, remote_url, scm_provider, transport, credential_secret_id,
        production_branch, deployed_commit
    ) VALUES (
        $6, $2, $7,
        $8, $9,
        $10, $11,
        $12
    )
    ON CONFLICT (project_id) DO UPDATE
    SET remote_url = EXCLUDED.remote_url,
        scm_provider = EXCLUDED.scm_provider,
        transport = EXCLUDED.transport,
        credential_secret_id = EXCLUDED.credential_secret_id,
        production_branch = EXCLUDED.production_branch,
        deployed_commit = EXCLUDED.deployed_commit,
        version = project_repositories.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, remote_url, scm_provider, transport, credential_secret_id,
              production_branch, deployed_commit, version
), changed_source AS (
    INSERT INTO project_sources (
        id, project_id, environment_id, name, kind, credential_secret_id,
        config, capabilities, enabled
    )
    SELECT $13, $2, changed_environment.id,
           $14, $15, $16,
           $17, $18, $19
    FROM changed_environment
    ON CONFLICT (project_id) DO UPDATE
    SET environment_id = EXCLUDED.environment_id,
        name = EXCLUDED.name,
        kind = EXCLUDED.kind,
        credential_secret_id = EXCLUDED.credential_secret_id,
        config = EXCLUDED.config,
        capabilities = EXCLUDED.capabilities,
        enabled = EXCLUDED.enabled,
        version = project_sources.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, name, kind, credential_secret_id, config, capabilities, enabled, version
), changed_trigger AS (
    INSERT INTO project_triggers (
        id, project_id, environment_id, name, kind, signing_secret_id, config, enabled,
        ingress_token_hash, ingress_token_ciphertext, ingress_token_nonce
    )
    SELECT $20, $2, changed_environment.id,
           $21, $22, $23,
           $24, $25,
           $26, $27, $28
    FROM changed_environment
    ON CONFLICT (project_id) DO UPDATE
    SET environment_id = EXCLUDED.environment_id,
        name = EXCLUDED.name,
        kind = EXCLUDED.kind,
        signing_secret_id = EXCLUDED.signing_secret_id,
        config = EXCLUDED.config,
        enabled = EXCLUDED.enabled,
        ingress_token_hash = EXCLUDED.ingress_token_hash,
        ingress_token_ciphertext = EXCLUDED.ingress_token_ciphertext,
        ingress_token_nonce = EXCLUDED.ingress_token_nonce,
        version = project_triggers.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, name, kind, signing_secret_id, config, enabled, version,
              ingress_token_hash, ingress_token_ciphertext, ingress_token_nonce
), changed_llm AS (
    INSERT INTO project_llm_providers (
        id, project_id, provider, base_url, credential_secret_id, model
    ) VALUES (
        $29, $2, $30,
        $31, $32, $33
    )
    ON CONFLICT (project_id) DO UPDATE
    SET provider = EXCLUDED.provider,
        base_url = EXCLUDED.base_url,
        credential_secret_id = EXCLUDED.credential_secret_id,
        model = EXCLUDED.model,
        version = project_llm_providers.version + 1,
        updated_at = clock_timestamp()
    RETURNING id, provider, base_url, credential_secret_id, model, version
), created_audit AS (
    INSERT INTO audit_events (id, project_id, actor_user_id, action, target_type, target_id, summary, metadata)
    SELECT $34, $2, $35,
           'project.configuration.updated', 'project', $2,
           'Project configuration updated.',
           jsonb_build_object(
               'environmentKey', changed_environment.environment_key,
               'sourceKind', changed_source.kind,
               'triggerKind', changed_trigger.kind,
               'llmProvider', changed_llm.provider,
               'llmModel', changed_llm.model
           )
    FROM changed_environment, changed_source, changed_trigger, changed_llm
)
SELECT changed_environment.id AS environment_id,
       changed_environment.environment_key, changed_environment.name AS environment_name,
       changed_environment.service, changed_environment.version AS environment_version,
       changed_repository.id AS repository_id, changed_repository.remote_url,
       changed_repository.scm_provider, changed_repository.transport,
       changed_repository.credential_secret_id AS repository_credential_secret_id,
       changed_repository.production_branch, changed_repository.deployed_commit,
       changed_repository.version AS repository_version,
       changed_source.id AS source_id, changed_source.name AS source_name,
       changed_source.kind AS source_kind,
       changed_source.credential_secret_id AS source_credential_secret_id,
       changed_source.config AS source_config, changed_source.capabilities AS source_capabilities,
       changed_source.enabled AS source_enabled, changed_source.version AS source_version,
       changed_trigger.id AS trigger_id, changed_trigger.name AS trigger_name,
       changed_trigger.kind AS trigger_kind, changed_trigger.signing_secret_id,
       changed_trigger.config AS trigger_config, changed_trigger.enabled AS trigger_enabled,
       changed_trigger.version AS trigger_version,
       changed_trigger.ingress_token_hash, changed_trigger.ingress_token_ciphertext,
       changed_trigger.ingress_token_nonce,
       changed_llm.id AS llm_id, changed_llm.provider AS llm_provider,
       changed_llm.base_url AS llm_base_url,
       changed_llm.credential_secret_id AS llm_credential_secret_id,
       changed_llm.model AS llm_model, changed_llm.version AS llm_version
FROM changed_environment, changed_repository, changed_source, changed_trigger, changed_llm
`

type UpsertProjectConfigurationParams struct {
	EnvironmentID                pgtype.UUID
	ProjectID                    pgtype.UUID
	EnvironmentKey               string
	EnvironmentName              string
	Service                      *string
	RepositoryID                 pgtype.UUID
	RemoteUrl                    string
	ScmProvider                  string
	RepositoryTransport          string
	RepositoryCredentialSecretID pgtype.UUID
	ProductionBranch             string
	DeployedCommit               string
	SourceID                     pgtype.UUID
	SourceName                   string
	SourceKind                   string
	SourceCredentialSecretID     pgtype.UUID
	SourceConfig                 []byte
	SourceCapabilities           []string
	SourceEnabled                bool
	TriggerID                    pgtype.UUID
	TriggerName                  string
	TriggerKind                  string
	SigningSecretID              pgtype.UUID
	TriggerConfig                []byte
	TriggerEnabled               bool
	IngressTokenHash             []byte
	IngressTokenCiphertext       []byte
	IngressTokenNonce            []byte
	LlmID                        pgtype.UUID
	LlmProvider                  string
	LlmBaseUrl                   string
	LlmCredentialSecretID        pgtype.UUID
	LlmModel                     string
	AuditID                      pgtype.UUID
	ActorUserID                  pgtype.UUID
}

type UpsertProjectConfigurationRow struct {
	EnvironmentID                pgtype.UUID
	EnvironmentKey               string
	EnvironmentName              string
	Service                      *string
	EnvironmentVersion           int64
	RepositoryID                 pgtype.UUID
	RemoteUrl                    string
	ScmProvider                  string
	Transport                    string
	RepositoryCredentialSecretID pgtype.UUID
	ProductionBranch             string
	DeployedCommit               string
	RepositoryVersion            int64
	SourceID                     pgtype.UUID
	SourceName                   string
	SourceKind                   string
	SourceCredentialSecretID     pgtype.UUID
	SourceConfig                 []byte
	SourceCapabilities           []string
	SourceEnabled                bool
	SourceVersion                int64
	TriggerID                    pgtype.UUID
	TriggerName                  string
	TriggerKind                  string
	SigningSecretID              pgtype.UUID
	TriggerConfig                []byte
	TriggerEnabled               bool
	TriggerVersion               int64
	IngressTokenHash             []byte
	IngressTokenCiphertext       []byte
	IngressTokenNonce            []byte
	LlmID                        pgtype.UUID
	LlmProvider                  string
	LlmBaseUrl                   string
	LlmCredentialSecretID        pgtype.UUID
	LlmModel                     string
	LlmVersion                   int64
}

func (q *Queries) UpsertProjectConfiguration(ctx context.Context, arg UpsertProjectConfigurationParams) (UpsertProjectConfigurationRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectConfiguration,
		arg.EnvironmentID,
		arg.ProjectID,
		arg.EnvironmentKey,
		arg.EnvironmentName,
		arg.Service,
		arg.RepositoryID,
		arg.RemoteUrl,
		arg.ScmProvider,
		arg.RepositoryTransport,
		arg.RepositoryCredentialSecretID,
		arg.ProductionBranch,
		arg.DeployedCommit,
		arg.SourceID,
		arg.SourceName,
		arg.SourceKind,
		arg.SourceCredentialSecretID,
		arg.SourceConfig,
		arg.SourceCapabilities,
		arg.SourceEnabled,
		arg.TriggerID,
		arg.TriggerName,
		arg.TriggerKind,
		arg.SigningSecretID,
		arg.TriggerConfig,
		arg.TriggerEnabled,
		arg.IngressTokenHash,
		arg.IngressTokenCiphertext,
		arg.IngressTokenNonce,
		arg.LlmID,
		arg.LlmProvider,
		arg.LlmBaseUrl,
		arg.LlmCredentialSecretID,
		arg.LlmModel,
		arg.AuditID,
		arg.ActorUserID,
	)
	var i UpsertProjectConfigurationRow
	err := row.Scan(
		&i.EnvironmentID,
		&i.EnvironmentKey,
		&i.EnvironmentName,
		&i.Service,
		&i.EnvironmentVersion,
		&i.RepositoryID,
		&i.RemoteUrl,
		&i.ScmProvider,
		&i.Transport,
		&i.RepositoryCredentialSecretID,
		&i.ProductionBranch,
		&i.DeployedCommit,
		&i.RepositoryVersion,
		&i.SourceID,
		&i.SourceName,
		&i.SourceKind,
		&i.SourceCredentialSecretID,
		&i.SourceConfig,
		&i.SourceCapabilities,
		&i.SourceEnabled,
		&i.SourceVersion,
		&i.TriggerID,
		&i.TriggerName,
		&i.TriggerKind,
		&i.SigningSecretID,
		&i.TriggerConfig,
		&i.TriggerEnabled,
		&i.TriggerVersion,
		&i.IngressTokenHash,
		&i.IngressTokenCiphertext,
		&i.IngressTokenNonce,
		&i.LlmID,
		&i.LlmProvider,
		&i.LlmBaseUrl,
		&i.LlmCredentialSecretID,
		&i.LlmModel,
		&i.LlmVersion,
	)
	return i, err
}

const upsertProjectMember = `-- name: UpsertProjectMember :one
WITH target_user AS (
    SELECT id, username
    FROM users
    WHERE username = $1 AND enabled
), changed_membership AS (
    INSERT INTO project_memberships (project_id, user_id, role)
    SELECT $2, id, $3
    FROM target_user
    ON CONFLICT (project_id, user_id) DO UPDATE
    SET role = EXCLUDED.role,
        version = project_memberships.version + 1,
        updated_at = clock_timestamp()
    WHERE project_memberships.role <> 'admin'
       OR EXCLUDED.role = 'admin'
       OR EXISTS (
           SELECT 1
           FROM project_memberships AS another_admin
           WHERE another_admin.project_id = project_memberships.project_id
             AND another_admin.role = 'admin'
             AND another_admin.user_id <> project_memberships.user_id
       )
    RETURNING user_id, role, version, created_at, updated_at
), created_audit AS (
    INSERT INTO audit_events (id, project_id, actor_user_id, action, target_type, target_id, summary, metadata)
    SELECT $4, $2, $5,
           'project.member.updated', 'project_membership', changed_membership.user_id,
           'Project member updated.',
           jsonb_build_object('username', target_user.username, 'role', changed_membership.role)
    FROM changed_membership
    JOIN target_user ON target_user.id = changed_membership.user_id
)
SELECT changed_membership.user_id, target_user.username, changed_membership.role,
       changed_membership.version, changed_membership.created_at, changed_membership.updated_at
FROM changed_membership
JOIN target_user ON target_user.id = changed_membership.user_id
`

type UpsertProjectMemberParams struct {
	Username    string
	ProjectID   pgtype.UUID
	Role        string
	AuditID     pgtype.UUID
	ActorUserID pgtype.UUID
}

type UpsertProjectMemberRow struct {
	UserID    pgtype.UUID
	Username  string
	Role      string
	Version   int64
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

func (q *Queries) UpsertProjectMember(ctx context.Context, arg UpsertProjectMemberParams) (UpsertProjectMemberRow, error) {
	row := q.db.QueryRow(ctx, upsertProjectMember,
		arg.Username,
		arg.ProjectID,
		arg.Role,
		arg.AuditID,
		arg.ActorUserID,
	)
	var i UpsertProjectMemberRow
	err := row.Scan(
		&i.UserID,
		&i.Username,
		&i.Role,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
