// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package remediationdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 保存项目 Event Stream 中经过归一化的持久事件。
type Observation struct {
	// 应用生成的 UUIDv7 observation 内部标识。
	ID pgtype.UUID
	// observation 所属项目，是读取隔离的首要条件。
	ProjectID pgtype.UUID
	// 事件产生时对应的同项目 environment。
	EnvironmentID pgtype.UUID
	// 产生该事件的同项目同环境 source。
	SourceID pgtype.UUID
	// 事件的可选 service 标签；为空时可使用 environment 默认值展示。
	Service *string
	// 事件在来源系统中发生的时间。
	OccurredAt pgtype.Timestamptz
	// 归一化日志级别，取值为 debug、info、warn、error 或 critical。
	Level string
	// 归一化后的事件正文，仍受项目访问和 retention 约束。
	Message string
	// 来源提供的可选 host 标识。
	Host *string
	// 来源提供的可选 request correlation 标识。
	RequestID *string
	// 事件归一化后计算的稳定分组 key。
	Fingerprint string
	// 经过 allowlist 和大小限制的非秘密扩展属性。
	Attributes []byte
	// 事件被 FixThe 持久化时的 PostgreSQL 时钟时间。
	IngestedAt pgtype.Timestamptz
}

// 建议 diff 等产物的内容寻址引用；完整内容不写入 audit JSON，摘录有界。
type RemediationArtifact struct {
	// 应用生成的产物记录 UUID。
	ID pgtype.UUID
	// 所属 remediation run。
	RunID pgtype.UUID
	// 产物类型，例如 suggested_diff。
	ArtifactType string
	// 应用拥有的产物存储路径或逻辑引用，不是仓库远程 URL。
	ReferencePath string
	// 产物内容的稳定哈希，供后续回放校验。
	ContentHash string
	// 产物字节数，用于预算和展示，不内联完整内容。
	SizeBytes int64
	// 产物记录写入时的 PostgreSQL 时钟时间。
	CreatedAt pgtype.Timestamptz
	// 建议 unified diff 的有界摘录，最多 64KiB，供 console GET 读取；完整内容以 content_hash 寻址，禁止写入 audit_events。
	Excerpt string
}

// Append-only immutable working-memory checkpoint events; each event carries a canonical SHA-256 content hash, a monotonic per-run sequence, and the full checkpoint payload.
type RemediationCheckpointEvent struct {
	// Application-generated event UUID; events are never updated once inserted.
	ID pgtype.UUID
	// Owning remediation run; deleting the run cascades its checkpoint history.
	RunID pgtype.UUID
	// Monotonic per-run sequence assigned by the store; the latest snapshot references the newest sequence.
	Sequence int64
	// Checkpoint trigger classification such as threshold, phase_boundary, recovery, or process_shutdown; never a model trace or error body.
	TriggerReason string
	// Canonical WorkingMemoryCheckpointV1 JSON; summaries inside it never become evidence and verified facts retain their evidence IDs.
	Payload []byte
	// SHA-256 of the canonical payload; loading recomputes and rejects mismatches.
	ContentHash string
	// PostgreSQL clock time when the event was appended.
	CreatedAt pgtype.Timestamptz
}

// 一次 schema 校验后的诊断结论及其证据引用；不含原始日志、prompt 或凭据。
type RemediationDecision struct {
	// 应用生成的诊断记录 UUID。
	ID pgtype.UUID
	// 所属 remediation run。
	RunID pgtype.UUID
	// 同一 run 内诊断记录的追加序号。
	Sequence int32
	// 可修复性分类，例如 code_fixable、configuration、insufficient_evidence。
	FixabilityClass string
	// 模型给出的置信度，范围 0.00 到 1.00。
	ConfidenceScore pgtype.Numeric
	// 因果推理摘要；禁止写入原始 prompt、完整日志或凭据。
	Reasoning string
	// 该诊断写入时的 PostgreSQL 时钟时间。
	DecidedAt pgtype.Timestamptz
	// 模型给出的互相矛盾证据摘要；不含原始日志、prompt 或凭据。
	Contradictions []string
	// 模型声明仍缺失的证据标识；只存短文本，不含原始日志。
	MissingEvidence []string
	// 诊断引用的证据 ID 列表；必须能解析到已采集证据，禁止编造。
	EvidenceCitations []string
	// 给值班人的下一步建议，例如收集更多日志或人工审查。
	RecommendedNextAction string
}

// Project-authorized operational evidence collected for an incident or remediation run; credential/control material is excluded from payload by the owning adapter.
type RemediationEvidence struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	EnvironmentID pgtype.UUID
	SourceID      pgtype.UUID
	IncidentID    pgtype.UUID
	RunID         pgtype.UUID
	ObservationID pgtype.UUID
	Provider      string
	EvidenceKind  string
	// Stable connector-owned append key unique within the owning incident and run; retries stay idempotent without reassigning evidence across ownership boundaries.
	DeduplicationKey string
	// Trusted evidence classification used by the service-owned diagnosis gate, never assigned by model text.
	Classification         string
	Outcome                string
	Available              bool
	PrimaryEvidence        bool
	TemporalCorrelation    bool
	OperationalCorrelation bool
	OccurredAt             pgtype.Timestamptz
	IngestedAt             pgtype.Timestamptz
	ContentHash            string
	ByteCount              int64
	// Bounded source and provider provenance metadata without credentials, tokens, or arbitrary fetch authority.
	Provenance []byte
	// Complete bounded operational evidence JSON, including log content and original provider time fields.
	Payload   []byte
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
	// Incident lifecycle generation observed atomically when the evidence was admitted; NULL legacy rows fail closed for pre-run continuation reads.
	BaselineLifecycleGeneration *int64
	// Deployed commit observed atomically with baseline_lifecycle_generation when the evidence was admitted.
	BaselineDeployedCommit *string
}

// Service-owned evidence gate decision for one remediation run; separate from model confidence and model response text.
type RemediationEvidenceAssessment struct {
	RunID               pgtype.UUID
	ProjectID           pgtype.UUID
	IncidentID          pgtype.UUID
	ConfidenceCap       pgtype.Numeric
	EffectiveConfidence pgtype.Numeric
	PlanningEligible    bool
	Outcome             string
	Reasons             []string
	MissingEvidence     []string
	Contradictions      []string
	DirectEvidenceIds   []string
	AssessedAt          pgtype.Timestamptz
}

// Short-lived server-authoritative evidence paging capabilities; only a random token digest is stored and every offset is bound to run, evidence, content hash, and expiry.
type RemediationEvidenceReadCursor struct {
	TokenHash   []byte
	RunID       pgtype.UUID
	EvidenceID  pgtype.UUID
	ContentHash string
	ByteOffset  int64
	ExpiresAt   pgtype.Timestamptz
	CreatedAt   pgtype.Timestamptz
}

// Latest bounded projection for a resilient workspace, patch, validation, or publication effect; raw patch/output and credentials are excluded.
type RemediationLifecycleEffect struct {
	// Application-owned identity of one lifecycle effect projection.
	ID pgtype.UUID
	// Remediation attempt that owns the effect; cascade cleanup follows run lifecycle.
	RunID pgtype.UUID
	// Bounded external effect class used to select recovery behavior and idempotency scope.
	EffectKind string
	// Coordinator-generated stable key that makes retries and process restart address the same external effect.
	IdempotencyKey string
	// Latest effect state; succeeded projections are reused and cannot be replaced by a later failure.
	State string
	// Bounded logical attempt count for the effect, independent of adapter-local transport retries.
	Attempt int32
	// Immutable deployed source baseline used by workspace and publication replay.
	BaselineCommit string
	// Opaque run-owned workspace identity; no host path or engine authority is stored.
	WorkspaceID string
	// Content identity of the clean workspace tree before a patch.
	BaseTreeHash string
	// Content identity expected after a patch or verified by publication replay.
	ResultTreeHash string
	// Content-addressed patch or approved artifact reference, never the artifact body.
	ArtifactRef string
	// Hash of the referenced patch or effect artifact used for replay verification.
	ContentHash string
	// Administrator-approved validation command identity; arbitrary shell text is excluded.
	CommandID string
	// Immutable validation command version snapshotted for this run.
	CommandVersion int64
	// Whether the effect has an authoritative validation result rather than a model claim.
	ValidationKnown bool
	// Authoritative validation outcome when validation_known is true.
	ValidationPassed bool
	// Policy-approved change branch reference returned by the trusted publisher.
	BranchRef string
	// Publication target branch snapshotted before the external effect; configuration changes cannot retarget this run.
	TargetBranch string
	// Published change commit identity returned by the trusted publisher.
	CommitHash string
	// Optional provider-native draft change request identity; no merge authority.
	DraftChangeRef string
	// Optional safe compare link without embedded userinfo, tokens, or credentials.
	CompareUrl string
	// Sanitized low-cardinality recovery or terminal error code.
	ErrorCode string
	// Bounded operator-safe effect summary; raw output and model text are excluded.
	Summary string
	// Time the effect projection was first created.
	CreatedAt pgtype.Timestamptz
	// Time the latest state or safe identity projection was written.
	UpdatedAt pgtype.Timestamptz
}

// code_fixable 诊断下的候选或推荐修复计划；建议 diff 存在 artifact，不内联到本行。
type RemediationPlan struct {
	// 应用生成的计划记录 UUID。
	ID pgtype.UUID
	// 所属 remediation run。
	RunID pgtype.UUID
	// 同一 run 内计划记录的追加序号。
	Sequence int32
	// 计划的短标题，供 console 列表展示。
	Title string
	// 推荐或不推荐该计划的理由摘要。
	Rationale string
	// 变更风险分类，取值为 ordinary、high_risk 或 denied_control_plane。
	RiskClass string
	// 是否为该 run 当前推荐计划；同一 run 至多一条为真。
	IsRecommended bool
	// 计划写入时的 PostgreSQL 时钟时间。
	CreatedAt pgtype.Timestamptz
	// 模型信封中的候选计划标识，供 recommended 对齐；不是内部 UUID。
	PlanKey string
	// 该计划依赖的证据 ID 列表。
	EvidenceRefs []string
	// 计划声称会改动的仓库相对路径，不含凭据或绝对主机路径。
	AffectedFiles []string
	// 建议回滚方式的短文本；不是可执行脚本。
	RollbackStrategy string
}

// 系列内一次有界尝试的状态、预算计数和模型元数据；不含原始 prompt、响应或凭据。
type RemediationRun struct {
	// 应用生成的 run UUID，是 decision、plan、artifact 和 tool invocation 的外键目标。
	ID pgtype.UUID
	// 所属 remediation 系列；同一系列内 attempt_number 单调递增且唯一。
	SeriesID pgtype.UUID
	// 系列内的尝试序号，从 1 起；重试创建新 run，不改写终态 run。
	AttemptNumber int32
	// run 生命周期状态，例如 queued、diagnosing、diagnosis_ready_for_review、failed。
	State string
	// run 记录创建或开始推进时的 PostgreSQL 时钟时间。
	StartedAt pgtype.Timestamptz
	// run 进入终态时的时钟时间；进行中为空。
	EndedAt pgtype.Timestamptz
	// 进入终态时累计的墙钟毫秒数；进行中为空。
	ElapsedMs *int64
	// 本 run 已完成的模型调用次数，计入预算。
	ModelCalls int32
	// 提供方报告的累计输入 token；缺省为 0，不存原始请求。
	ModelTokensIn int64
	// 提供方报告的累计输出 token；缺省为 0，不存原始响应。
	ModelTokensOut int64
	// 提供方报告的累计费用（分）；可用时记录，从不保存原始请求或响应。
	ModelCostCents int64
	// 安全的提供方标识，例如 openai；不含 API key、凭据或原始载荷。
	ModelProvider string
	// 安全的模型标识，例如 gpt-5.6；不含原始请求或响应。
	ModelName string
	// 本 run 已执行的工具调用次数，计入预算。
	ToolCalls int32
	// 本 run 已读入的证据字节累计，计入预算。
	EvidenceBytes int64
	// 本 run 已读入的仓库字节累计，计入预算。
	RepositoryBytes int64
	// run 聚合的单调递增版本号，供状态迁移时执行乐观并发控制。
	Version int64
	// Direct predecessor run for a continuation attempt; NULL identifies a root attempt and prior runs remain immutable history.
	ContinuationOfRunID pgtype.UUID
	// Safe origin classification: automatic, manual, automatic_continue, or manual_continue; never a webhook body or provider message.
	TriggerReason string
	// Bounded operator or system reason for creating this continuation; contains no credentials, prompts, payloads, or unrestricted error text.
	ContinuationReason string
	// Incident and evidence context version observed when this attempt was admitted; used to require newer context for automatic continuation.
	ContextVersion int64
	// Safe terminal classification recorded by remediation; never stores a raw provider, model, connector, or database error.
	TerminalReason string
	// Service-owned eligibility marker for bounded automatic continuation; false is conservative for legacy and non-transient outcomes.
	Retryable bool
	// Project remediation policy mode snapshotted at run creation; a mid-run configuration change cannot alter semantics, and legacy remains the default so existing projects are unaffected.
	AgentLoopMode string
	// Version of the project remediation policy snapshotted by a root run and inherited unchanged by every continuation.
	AgentLoopPolicyVersion int64
	// Immutable execution constraint inherited by continuation attempts; true permits diagnosis and proposed solutions but forbids patch, validation, publication, repair, and deployment effects.
	AnalysisOnly bool
	// Time the current state was entered; NULL for legacy runs until their next state transition.
	StateEnteredAt pgtype.Timestamptz
}

// 一次事故在固定 lifecycle_generation 与 deployed_commit 下的 remediation 系列；唯一键阻止同一基线重复建根 run。
type RemediationSeries struct {
	// 应用生成的系列 UUID，是其下全部 run 的外键目标。
	ID pgtype.UUID
	// 所属事故的内部 UUIDv7，对应 incidents.id，不暴露为 INC-<number>。
	IncidentID pgtype.UUID
	// 写入系列时捕获的事故生命周期代数；与 incident 当前值一起构成系列唯一键。
	LifecycleGeneration int64
	// 写入系列时捕获的生产部署 commit；后续仓库配置变更不得改写已有系列键。
	DeployedCommit string
	// 系列首次创建时的 PostgreSQL 时钟时间。
	CreatedAt pgtype.Timestamptz
}

// Append-only audit of each model-submitted diagnosis envelope before the evidence gate, with bounded correction metadata; the accepted decision remains the review authority and raw model turns are never stored.
type RemediationSubmittedDiagnosis struct {
	// Application-generated audit row UUID; rows are never updated once inserted.
	ID pgtype.UUID
	// Owning remediation run; deleting the run cascades its submitted-diagnosis audit rows.
	RunID pgtype.UUID
	// Monotonic per-run sequence assigned by the store in append order.
	Sequence int32
	// The model-submitted fixability from the original pre-gate envelope, preserved even when the evidence gate later rejects it.
	FixabilityClass string
	// The model-submitted numeric confidence from the original pre-gate envelope.
	ConfidenceScore pgtype.Numeric
	// Bounded structured causal reasoning from the envelope; never raw provider text or conversation history.
	Reasoning string
	// Model-declared contradiction summaries from the envelope, bounded to the same limit as remediation_decision.
	Contradictions []string
	// Model-declared missing evidence identifiers from the envelope.
	MissingEvidence []string
	// Model-cited evidence ID list from the envelope; must resolve against run-owned evidence.
	EvidenceCitations []string
	// Model-recommended next action from the envelope, bounded and credential-free.
	RecommendedNextAction string
	// Bounded correction classification: empty, evidence_correction (citation metadata), or exhaustion (accepted proof).
	CorrectionKind string
	// Bounded JSON array of corrected citations as {"evidenceId","storedClassification"} pairs showing only the authoritative stored classification.
	CorrectionEvidence []byte
	// Number of correction entries recorded, so audit can show a correction occurred without storing raw model text.
	CorrectionCount int32
	// True when the submission required a correction (citation mismatch or exhaustion acceptance).
	Corrected bool
	// Service-owned evidence gate verdict: empty when no gate ran, planning_eligible, or rejected; never derived from model text.
	GateOutcome string
	// Accepted remediation_decision produced from this submission when one exists, so audit can join submitted to accepted; null when the submission was corrected without a decision.
	DecisionID pgtype.UUID
	// PostgreSQL clock time when the submitted diagnosis was recorded.
	SubmittedAt pgtype.Timestamptz
}

// 一次只读工具调用的元数据；参数已归一化，禁止保存秘密字段或原始大段输出。
type RemediationToolInvocation struct {
	// 应用生成的工具调用 UUID。
	ID pgtype.UUID
	// 所属 remediation run。
	RunID pgtype.UUID
	// 同一 run 内工具调用的追加序号。
	Sequence int32
	// 逻辑工具标识，例如 repository.read_file 或 evidence.search。
	ToolName string
	// 调用发生时的 run 阶段，例如 diagnosing。
	Phase string
	// 调用开始时的 PostgreSQL 时钟时间。
	InvokedAt pgtype.Timestamptz
	// 调用耗时毫秒数；失败或未完成时可为 NULL。
	DurationMs *int64
	// 调用结果分类，例如 ok、rejected、unavailable 或 error。
	Outcome string
	// Service-issued action reference exposed in the bounded tool observation and used to prove a capability attempt; null for historical invocations.
	OutcomeRef *string
	// Bounded persisted evidence IDs produced by this invocation; payloads and raw tool output are never stored here.
	EvidenceIds []string
	// Sanitized stable tool error code when outcome is error; never raw connector text or credentials.
	ErrorCode *string
}

// Latest working-memory snapshot per run; its sequence must be backed by a checkpoint event, and updating the snapshot is atomic with appending that event.
type RemediationWorkingMemory struct {
	// Owning remediation run; at most one snapshot per run.
	RunID pgtype.UUID
	// Sequence of the backing checkpoint event; the foreign key rejects a snapshot whose sequence has no event.
	Sequence int64
	// Incident and evidence context version observed by the checkpoint; must match the run context version.
	ContextVersion int64
	// Durable remediation_run.version observed by the checkpoint; older values require projection rebuild and future values are corrupt.
	ObservedRunVersion int64
	// Checkpoint phase such as diagnosing or planning; bounded, provider-neutral text.
	Phase string
	// SHA-256 of the canonical checkpoint payload; must equal the backing event hash.
	ContentHash string
	// PostgreSQL clock time of the latest snapshot update.
	UpdatedAt pgtype.Timestamptz
}
