// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remediation.sql

package remediationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRemediationArtifact = `-- name: CreateRemediationArtifact :one
INSERT INTO remediation_artifact (
    run_id,
    artifact_type,
    reference_path,
    content_hash,
    size_bytes,
    excerpt
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, artifact_type, reference_path, content_hash, size_bytes, created_at, excerpt
`

type CreateRemediationArtifactParams struct {
	RunID         pgtype.UUID
	ArtifactType  string
	ReferencePath string
	ContentHash   string
	SizeBytes     int64
	Excerpt       string
}

func (q *Queries) CreateRemediationArtifact(ctx context.Context, arg CreateRemediationArtifactParams) (RemediationArtifact, error) {
	row := q.db.QueryRow(ctx, createRemediationArtifact,
		arg.RunID,
		arg.ArtifactType,
		arg.ReferencePath,
		arg.ContentHash,
		arg.SizeBytes,
		arg.Excerpt,
	)
	var i RemediationArtifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArtifactType,
		&i.ReferencePath,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.Excerpt,
	)
	return i, err
}

const createRemediationCheckpointEvent = `-- name: CreateRemediationCheckpointEvent :one
INSERT INTO remediation_checkpoint_event (
    run_id,
    sequence,
    trigger_reason,
    payload,
    content_hash
) VALUES (
    $1, $2, $3,
    $4, $5
)
RETURNING id, run_id, sequence, trigger_reason, payload, content_hash, created_at
`

type CreateRemediationCheckpointEventParams struct {
	RunID         pgtype.UUID
	Sequence      int64
	TriggerReason string
	Payload       []byte
	ContentHash   string
}

func (q *Queries) CreateRemediationCheckpointEvent(ctx context.Context, arg CreateRemediationCheckpointEventParams) (RemediationCheckpointEvent, error) {
	row := q.db.QueryRow(ctx, createRemediationCheckpointEvent,
		arg.RunID,
		arg.Sequence,
		arg.TriggerReason,
		arg.Payload,
		arg.ContentHash,
	)
	var i RemediationCheckpointEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.TriggerReason,
		&i.Payload,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const createRemediationDecision = `-- name: CreateRemediationDecision :one
INSERT INTO remediation_decision (
    run_id,
    sequence,
    fixability_class,
    confidence_score,
    reasoning,
    contradictions,
    missing_evidence,
    evidence_citations,
    recommended_next_action
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, run_id, sequence, fixability_class, confidence_score, reasoning, decided_at, contradictions, missing_evidence, evidence_citations, recommended_next_action
`

type CreateRemediationDecisionParams struct {
	RunID                 pgtype.UUID
	Sequence              int32
	FixabilityClass       string
	ConfidenceScore       pgtype.Numeric
	Reasoning             string
	Contradictions        []string
	MissingEvidence       []string
	EvidenceCitations     []string
	RecommendedNextAction string
}

func (q *Queries) CreateRemediationDecision(ctx context.Context, arg CreateRemediationDecisionParams) (RemediationDecision, error) {
	row := q.db.QueryRow(ctx, createRemediationDecision,
		arg.RunID,
		arg.Sequence,
		arg.FixabilityClass,
		arg.ConfidenceScore,
		arg.Reasoning,
		arg.Contradictions,
		arg.MissingEvidence,
		arg.EvidenceCitations,
		arg.RecommendedNextAction,
	)
	var i RemediationDecision
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.FixabilityClass,
		&i.ConfidenceScore,
		&i.Reasoning,
		&i.DecidedAt,
		&i.Contradictions,
		&i.MissingEvidence,
		&i.EvidenceCitations,
		&i.RecommendedNextAction,
	)
	return i, err
}

const createRemediationEvidence = `-- name: CreateRemediationEvidence :one
INSERT INTO remediation_evidence (
    project_id, environment_id, source_id, incident_id, run_id, observation_id,
    provider, evidence_kind, deduplication_key, classification, outcome,
    available, primary_evidence, temporal_correlation, operational_correlation,
    occurred_at, content_hash, byte_count, provenance, payload,
    baseline_lifecycle_generation, baseline_deployed_commit
)
SELECT
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17,
    $18, $19, $20,
    COALESCE(series.lifecycle_generation, incident.lifecycle_generation),
    COALESCE(series.deployed_commit, incident.deployed_commit)
FROM incidents AS incident
LEFT JOIN remediation_run AS owning_run ON owning_run.id = $5
LEFT JOIN remediation_series AS series ON series.id = owning_run.series_id
WHERE incident.id = $4
  AND incident.project_id = $1
ON CONFLICT (
    project_id, incident_id, run_id, baseline_lifecycle_generation,
    baseline_deployed_commit, deduplication_key
)
DO UPDATE SET
    run_id = COALESCE(EXCLUDED.run_id, remediation_evidence.run_id),
    observation_id = COALESCE(EXCLUDED.observation_id, remediation_evidence.observation_id),
    updated_at = clock_timestamp()
RETURNING id, project_id, environment_id, source_id, incident_id, run_id, observation_id, provider, evidence_kind, deduplication_key, classification, outcome, available, primary_evidence, temporal_correlation, operational_correlation, occurred_at, ingested_at, content_hash, byte_count, provenance, payload, created_at, updated_at, baseline_lifecycle_generation, baseline_deployed_commit
`

type CreateRemediationEvidenceParams struct {
	ProjectID              pgtype.UUID
	EnvironmentID          pgtype.UUID
	SourceID               pgtype.UUID
	IncidentID             pgtype.UUID
	RunID                  pgtype.UUID
	ObservationID          pgtype.UUID
	Provider               string
	EvidenceKind           string
	DeduplicationKey       string
	Classification         string
	Outcome                string
	Available              bool
	PrimaryEvidence        bool
	TemporalCorrelation    bool
	OperationalCorrelation bool
	OccurredAt             pgtype.Timestamptz
	ContentHash            string
	ByteCount              int64
	Provenance             []byte
	Payload                []byte
}

func (q *Queries) CreateRemediationEvidence(ctx context.Context, arg CreateRemediationEvidenceParams) (RemediationEvidence, error) {
	row := q.db.QueryRow(ctx, createRemediationEvidence,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.SourceID,
		arg.IncidentID,
		arg.RunID,
		arg.ObservationID,
		arg.Provider,
		arg.EvidenceKind,
		arg.DeduplicationKey,
		arg.Classification,
		arg.Outcome,
		arg.Available,
		arg.PrimaryEvidence,
		arg.TemporalCorrelation,
		arg.OperationalCorrelation,
		arg.OccurredAt,
		arg.ContentHash,
		arg.ByteCount,
		arg.Provenance,
		arg.Payload,
	)
	var i RemediationEvidence
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentID,
		&i.RunID,
		&i.ObservationID,
		&i.Provider,
		&i.EvidenceKind,
		&i.DeduplicationKey,
		&i.Classification,
		&i.Outcome,
		&i.Available,
		&i.PrimaryEvidence,
		&i.TemporalCorrelation,
		&i.OperationalCorrelation,
		&i.OccurredAt,
		&i.IngestedAt,
		&i.ContentHash,
		&i.ByteCount,
		&i.Provenance,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaselineLifecycleGeneration,
		&i.BaselineDeployedCommit,
	)
	return i, err
}

const createRemediationEvidenceReadCursor = `-- name: CreateRemediationEvidenceReadCursor :exec
INSERT INTO remediation_evidence_read_cursor (
    token_hash, run_id, evidence_id, content_hash, byte_offset, expires_at
) VALUES (
    $1, $2, $3,
    $4, $5, $6
)
`

type CreateRemediationEvidenceReadCursorParams struct {
	TokenHash   []byte
	RunID       pgtype.UUID
	EvidenceID  pgtype.UUID
	ContentHash string
	ByteOffset  int64
	ExpiresAt   pgtype.Timestamptz
}

func (q *Queries) CreateRemediationEvidenceReadCursor(ctx context.Context, arg CreateRemediationEvidenceReadCursorParams) error {
	_, err := q.db.Exec(ctx, createRemediationEvidenceReadCursor,
		arg.TokenHash,
		arg.RunID,
		arg.EvidenceID,
		arg.ContentHash,
		arg.ByteOffset,
		arg.ExpiresAt,
	)
	return err
}

const createRemediationNextRun = `-- name: CreateRemediationNextRun :one
INSERT INTO remediation_run (
    series_id,
    attempt_number,
    state,
    continuation_of_run_id,
    trigger_reason,
    continuation_reason,
    context_version,
    analysis_only,
    agent_loop_mode,
    agent_loop_policy_version
) VALUES (
    $1, $2, 'queued',
    $3, $4,
    $5, $6,
    (SELECT analysis_only FROM remediation_run WHERE id = $3),
    (SELECT agent_loop_mode FROM remediation_run WHERE id = $3),
    (SELECT agent_loop_policy_version FROM remediation_run WHERE id = $3)
)
RETURNING id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version, continuation_of_run_id, trigger_reason, continuation_reason, context_version, terminal_reason, retryable, agent_loop_mode, agent_loop_policy_version, analysis_only
`

type CreateRemediationNextRunParams struct {
	SeriesID            pgtype.UUID
	AttemptNumber       int32
	ContinuationOfRunID pgtype.UUID
	TriggerReason       string
	ContinuationReason  string
	ContextVersion      int64
}

func (q *Queries) CreateRemediationNextRun(ctx context.Context, arg CreateRemediationNextRunParams) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, createRemediationNextRun,
		arg.SeriesID,
		arg.AttemptNumber,
		arg.ContinuationOfRunID,
		arg.TriggerReason,
		arg.ContinuationReason,
		arg.ContextVersion,
	)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
		&i.ContinuationOfRunID,
		&i.TriggerReason,
		&i.ContinuationReason,
		&i.ContextVersion,
		&i.TerminalReason,
		&i.Retryable,
		&i.AgentLoopMode,
		&i.AgentLoopPolicyVersion,
		&i.AnalysisOnly,
	)
	return i, err
}

const createRemediationPlan = `-- name: CreateRemediationPlan :one
INSERT INTO remediation_plan (
    run_id,
    sequence,
    title,
    rationale,
    risk_class,
    is_recommended,
    plan_key,
    evidence_refs,
    affected_files,
    rollback_strategy
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, run_id, sequence, title, rationale, risk_class, is_recommended, created_at, plan_key, evidence_refs, affected_files, rollback_strategy
`

type CreateRemediationPlanParams struct {
	RunID            pgtype.UUID
	Sequence         int32
	Title            string
	Rationale        string
	RiskClass        string
	IsRecommended    bool
	PlanKey          string
	EvidenceRefs     []string
	AffectedFiles    []string
	RollbackStrategy string
}

func (q *Queries) CreateRemediationPlan(ctx context.Context, arg CreateRemediationPlanParams) (RemediationPlan, error) {
	row := q.db.QueryRow(ctx, createRemediationPlan,
		arg.RunID,
		arg.Sequence,
		arg.Title,
		arg.Rationale,
		arg.RiskClass,
		arg.IsRecommended,
		arg.PlanKey,
		arg.EvidenceRefs,
		arg.AffectedFiles,
		arg.RollbackStrategy,
	)
	var i RemediationPlan
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.Title,
		&i.Rationale,
		&i.RiskClass,
		&i.IsRecommended,
		&i.CreatedAt,
		&i.PlanKey,
		&i.EvidenceRefs,
		&i.AffectedFiles,
		&i.RollbackStrategy,
	)
	return i, err
}

const createRemediationRun = `-- name: CreateRemediationRun :one
INSERT INTO remediation_run (
    series_id,
    attempt_number,
    state,
    context_version,
    trigger_reason,
    analysis_only,
    agent_loop_mode,
    agent_loop_policy_version
)
SELECT $1, $2, $3,
       $4, $5, $6,
       project.agent_loop_mode, project.agent_loop_policy_version
FROM remediation_series AS series
JOIN incidents AS incident ON incident.id = series.incident_id
JOIN projects AS project ON project.id = incident.project_id
WHERE series.id = $1
RETURNING id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version, continuation_of_run_id, trigger_reason, continuation_reason, context_version, terminal_reason, retryable, agent_loop_mode, agent_loop_policy_version, analysis_only
`

type CreateRemediationRunParams struct {
	SeriesID       pgtype.UUID
	AttemptNumber  int32
	State          string
	ContextVersion int64
	TriggerReason  string
	AnalysisOnly   bool
}

func (q *Queries) CreateRemediationRun(ctx context.Context, arg CreateRemediationRunParams) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, createRemediationRun,
		arg.SeriesID,
		arg.AttemptNumber,
		arg.State,
		arg.ContextVersion,
		arg.TriggerReason,
		arg.AnalysisOnly,
	)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
		&i.ContinuationOfRunID,
		&i.TriggerReason,
		&i.ContinuationReason,
		&i.ContextVersion,
		&i.TerminalReason,
		&i.Retryable,
		&i.AgentLoopMode,
		&i.AgentLoopPolicyVersion,
		&i.AnalysisOnly,
	)
	return i, err
}

const createRemediationSeries = `-- name: CreateRemediationSeries :one
INSERT INTO remediation_series (
    incident_id,
    lifecycle_generation,
    deployed_commit
) VALUES ($1, $2, $3)
ON CONFLICT (incident_id, lifecycle_generation, deployed_commit)
DO UPDATE SET id = remediation_series.id
RETURNING id, incident_id, lifecycle_generation, deployed_commit, created_at
`

type CreateRemediationSeriesParams struct {
	IncidentID          pgtype.UUID
	LifecycleGeneration int64
	DeployedCommit      string
}

func (q *Queries) CreateRemediationSeries(ctx context.Context, arg CreateRemediationSeriesParams) (RemediationSeries, error) {
	row := q.db.QueryRow(ctx, createRemediationSeries, arg.IncidentID, arg.LifecycleGeneration, arg.DeployedCommit)
	var i RemediationSeries
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.CreatedAt,
	)
	return i, err
}

const createRemediationSubmittedDiagnosis = `-- name: CreateRemediationSubmittedDiagnosis :one
INSERT INTO remediation_submitted_diagnosis (
    run_id,
    sequence,
    fixability_class,
    confidence_score,
    reasoning,
    contradictions,
    missing_evidence,
    evidence_citations,
    recommended_next_action,
    correction_kind,
    correction_evidence,
    correction_count,
    corrected,
    gate_outcome,
    decision_id
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
RETURNING id, run_id, sequence, fixability_class, confidence_score, reasoning, contradictions, missing_evidence, evidence_citations, recommended_next_action, correction_kind, correction_evidence, correction_count, corrected, gate_outcome, decision_id, submitted_at
`

type CreateRemediationSubmittedDiagnosisParams struct {
	RunID                 pgtype.UUID
	Sequence              int32
	FixabilityClass       string
	ConfidenceScore       pgtype.Numeric
	Reasoning             string
	Contradictions        []string
	MissingEvidence       []string
	EvidenceCitations     []string
	RecommendedNextAction string
	CorrectionKind        string
	CorrectionEvidence    []byte
	CorrectionCount       int32
	Corrected             bool
	GateOutcome           string
	DecisionID            pgtype.UUID
}

func (q *Queries) CreateRemediationSubmittedDiagnosis(ctx context.Context, arg CreateRemediationSubmittedDiagnosisParams) (RemediationSubmittedDiagnosis, error) {
	row := q.db.QueryRow(ctx, createRemediationSubmittedDiagnosis,
		arg.RunID,
		arg.Sequence,
		arg.FixabilityClass,
		arg.ConfidenceScore,
		arg.Reasoning,
		arg.Contradictions,
		arg.MissingEvidence,
		arg.EvidenceCitations,
		arg.RecommendedNextAction,
		arg.CorrectionKind,
		arg.CorrectionEvidence,
		arg.CorrectionCount,
		arg.Corrected,
		arg.GateOutcome,
		arg.DecisionID,
	)
	var i RemediationSubmittedDiagnosis
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.FixabilityClass,
		&i.ConfidenceScore,
		&i.Reasoning,
		&i.Contradictions,
		&i.MissingEvidence,
		&i.EvidenceCitations,
		&i.RecommendedNextAction,
		&i.CorrectionKind,
		&i.CorrectionEvidence,
		&i.CorrectionCount,
		&i.Corrected,
		&i.GateOutcome,
		&i.DecisionID,
		&i.SubmittedAt,
	)
	return i, err
}

const createRemediationToolInvocation = `-- name: CreateRemediationToolInvocation :one
INSERT INTO remediation_tool_invocation (
    run_id,
    sequence,
    tool_name,
    phase,
    duration_ms,
    outcome,
    outcome_ref,
    evidence_ids,
    error_code
) VALUES ($1, $2, $3, $4, $5, $6, NULLIF($7::text, ''), $8, NULLIF($9::text, ''))
RETURNING id, run_id, sequence, tool_name, phase, invoked_at, duration_ms, outcome, outcome_ref, evidence_ids, error_code
`

type CreateRemediationToolInvocationParams struct {
	RunID       pgtype.UUID
	Sequence    int32
	ToolName    string
	Phase       string
	DurationMs  *int64
	Outcome     string
	OutcomeRef  string
	EvidenceIds []string
	ErrorCode   string
}

func (q *Queries) CreateRemediationToolInvocation(ctx context.Context, arg CreateRemediationToolInvocationParams) (RemediationToolInvocation, error) {
	row := q.db.QueryRow(ctx, createRemediationToolInvocation,
		arg.RunID,
		arg.Sequence,
		arg.ToolName,
		arg.Phase,
		arg.DurationMs,
		arg.Outcome,
		arg.OutcomeRef,
		arg.EvidenceIds,
		arg.ErrorCode,
	)
	var i RemediationToolInvocation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.ToolName,
		&i.Phase,
		&i.InvokedAt,
		&i.DurationMs,
		&i.Outcome,
		&i.OutcomeRef,
		&i.EvidenceIds,
		&i.ErrorCode,
	)
	return i, err
}

const deleteExpiredRemediationEvidenceReadCursors = `-- name: DeleteExpiredRemediationEvidenceReadCursors :exec
DELETE FROM remediation_evidence_read_cursor
WHERE expires_at < clock_timestamp()
`

func (q *Queries) DeleteExpiredRemediationEvidenceReadCursors(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredRemediationEvidenceReadCursors)
	return err
}

const getLatestRemediationDecisionID = `-- name: GetLatestRemediationDecisionID :one
SELECT id FROM remediation_decision
WHERE run_id = $1
ORDER BY sequence DESC
LIMIT 1
`

func (q *Queries) GetLatestRemediationDecisionID(ctx context.Context, runID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getLatestRemediationDecisionID, runID)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getLatestRemediationObservationForIncident = `-- name: GetLatestRemediationObservationForIncident :one
SELECT observations.id, observations.project_id, observations.environment_id, observations.source_id, observations.service, observations.occurred_at, observations.level, observations.message, observations.host, observations.request_id, observations.fingerprint, observations.attributes, observations.ingested_at
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
JOIN observations
    ON observations.id = evidence.observation_id
   AND observations.project_id = evidence.project_id
WHERE evidence.incident_id = $1
  AND evidence.run_id IS NULL
  AND evidence.baseline_lifecycle_generation = incident.lifecycle_generation
  AND evidence.baseline_deployed_commit = incident.deployed_commit
  AND evidence.evidence_kind = 'normalized_alert'
ORDER BY evidence.created_at DESC, evidence.id DESC
LIMIT 1
`

func (q *Queries) GetLatestRemediationObservationForIncident(ctx context.Context, incidentID pgtype.UUID) (Observation, error) {
	row := q.db.QueryRow(ctx, getLatestRemediationObservationForIncident, incidentID)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.Service,
		&i.OccurredAt,
		&i.Level,
		&i.Message,
		&i.Host,
		&i.RequestID,
		&i.Fingerprint,
		&i.Attributes,
		&i.IngestedAt,
	)
	return i, err
}

const getLatestRemediationPlanningCheckpoint = `-- name: GetLatestRemediationPlanningCheckpoint :one
SELECT run.id, run.series_id, run.attempt_number, run.state, run.started_at, run.ended_at, run.elapsed_ms, run.model_calls, run.model_tokens_in, run.model_tokens_out, run.model_cost_cents, run.model_provider, run.model_name, run.tool_calls, run.evidence_bytes, run.repository_bytes, run.version, run.continuation_of_run_id, run.trigger_reason, run.continuation_reason, run.context_version, run.terminal_reason, run.retryable, run.agent_loop_mode, run.agent_loop_policy_version, run.analysis_only
FROM remediation_run AS run
WHERE run.series_id = $1
  AND run.context_version = $2
  AND run.attempt_number <= $3
  AND (
      SELECT decision.fixability_class
      FROM remediation_decision AS decision
      WHERE decision.run_id = run.id
      ORDER BY decision.sequence DESC
      LIMIT 1
  ) = 'code_fixable'
ORDER BY run.attempt_number DESC
LIMIT 1
`

type GetLatestRemediationPlanningCheckpointParams struct {
	SeriesID             pgtype.UUID
	ContextVersion       int64
	ThroughAttemptNumber int32
}

func (q *Queries) GetLatestRemediationPlanningCheckpoint(ctx context.Context, arg GetLatestRemediationPlanningCheckpointParams) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, getLatestRemediationPlanningCheckpoint, arg.SeriesID, arg.ContextVersion, arg.ThroughAttemptNumber)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
		&i.ContinuationOfRunID,
		&i.TriggerReason,
		&i.ContinuationReason,
		&i.ContextVersion,
		&i.TerminalReason,
		&i.Retryable,
		&i.AgentLoopMode,
		&i.AgentLoopPolicyVersion,
		&i.AnalysisOnly,
	)
	return i, err
}

const getRemediationArtifactsByRunID = `-- name: GetRemediationArtifactsByRunID :many
SELECT id, run_id, artifact_type, reference_path, content_hash, size_bytes, created_at, excerpt FROM remediation_artifact
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetRemediationArtifactsByRunID(ctx context.Context, runID pgtype.UUID) ([]RemediationArtifact, error) {
	rows, err := q.db.Query(ctx, getRemediationArtifactsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationArtifact
	for rows.Next() {
		var i RemediationArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ArtifactType,
			&i.ReferencePath,
			&i.ContentHash,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.Excerpt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationCheckpointEvent = `-- name: GetRemediationCheckpointEvent :one
SELECT id, run_id, sequence, trigger_reason, payload, content_hash, created_at FROM remediation_checkpoint_event
WHERE run_id = $1 AND sequence = $2
`

type GetRemediationCheckpointEventParams struct {
	RunID    pgtype.UUID
	Sequence int64
}

func (q *Queries) GetRemediationCheckpointEvent(ctx context.Context, arg GetRemediationCheckpointEventParams) (RemediationCheckpointEvent, error) {
	row := q.db.QueryRow(ctx, getRemediationCheckpointEvent, arg.RunID, arg.Sequence)
	var i RemediationCheckpointEvent
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.TriggerReason,
		&i.Payload,
		&i.ContentHash,
		&i.CreatedAt,
	)
	return i, err
}

const getRemediationCheckpointLatestSequence = `-- name: GetRemediationCheckpointLatestSequence :one
SELECT COALESCE(MAX(sequence), 0)::bigint AS sequence
FROM remediation_checkpoint_event
WHERE run_id = $1
`

func (q *Queries) GetRemediationCheckpointLatestSequence(ctx context.Context, runID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getRemediationCheckpointLatestSequence, runID)
	var sequence int64
	err := row.Scan(&sequence)
	return sequence, err
}

const getRemediationDecisionsByRunID = `-- name: GetRemediationDecisionsByRunID :many
SELECT id, run_id, sequence, fixability_class, confidence_score, reasoning, decided_at, contradictions, missing_evidence, evidence_citations, recommended_next_action FROM remediation_decision
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) GetRemediationDecisionsByRunID(ctx context.Context, runID pgtype.UUID) ([]RemediationDecision, error) {
	rows, err := q.db.Query(ctx, getRemediationDecisionsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationDecision
	for rows.Next() {
		var i RemediationDecision
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.FixabilityClass,
			&i.ConfidenceScore,
			&i.Reasoning,
			&i.DecidedAt,
			&i.Contradictions,
			&i.MissingEvidence,
			&i.EvidenceCitations,
			&i.RecommendedNextAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationEvidenceForRun = `-- name: GetRemediationEvidenceForRun :one
SELECT evidence.id, evidence.project_id, evidence.environment_id, evidence.source_id, evidence.incident_id, evidence.run_id, evidence.observation_id, evidence.provider, evidence.evidence_kind, evidence.deduplication_key, evidence.classification, evidence.outcome, evidence.available, evidence.primary_evidence, evidence.temporal_correlation, evidence.operational_correlation, evidence.occurred_at, evidence.ingested_at, evidence.content_hash, evidence.byte_count, evidence.provenance, evidence.payload, evidence.created_at, evidence.updated_at, evidence.baseline_lifecycle_generation, evidence.baseline_deployed_commit
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
JOIN remediation_run AS run
    ON run.id = $1
JOIN remediation_series AS series
    ON series.id = run.series_id AND series.incident_id = incident.id
WHERE evidence.id = $2
  AND ((evidence.run_id IS NULL
        AND evidence.baseline_lifecycle_generation = series.lifecycle_generation
        AND evidence.baseline_deployed_commit = series.deployed_commit)
       OR EXISTS (
           SELECT 1 FROM remediation_run AS evidence_run
           WHERE evidence_run.id = evidence.run_id
             AND evidence_run.series_id = series.id
             AND evidence_run.attempt_number <= run.attempt_number
       ))
`

type GetRemediationEvidenceForRunParams struct {
	RunID      pgtype.UUID
	EvidenceID pgtype.UUID
}

func (q *Queries) GetRemediationEvidenceForRun(ctx context.Context, arg GetRemediationEvidenceForRunParams) (RemediationEvidence, error) {
	row := q.db.QueryRow(ctx, getRemediationEvidenceForRun, arg.RunID, arg.EvidenceID)
	var i RemediationEvidence
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentID,
		&i.RunID,
		&i.ObservationID,
		&i.Provider,
		&i.EvidenceKind,
		&i.DeduplicationKey,
		&i.Classification,
		&i.Outcome,
		&i.Available,
		&i.PrimaryEvidence,
		&i.TemporalCorrelation,
		&i.OperationalCorrelation,
		&i.OccurredAt,
		&i.IngestedAt,
		&i.ContentHash,
		&i.ByteCount,
		&i.Provenance,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaselineLifecycleGeneration,
		&i.BaselineDeployedCommit,
	)
	return i, err
}

const getRemediationEvidencePage = `-- name: GetRemediationEvidencePage :one
SELECT evidence.id, evidence.project_id, evidence.environment_id, evidence.source_id, evidence.incident_id, evidence.run_id, evidence.observation_id, evidence.provider, evidence.evidence_kind, evidence.deduplication_key, evidence.classification, evidence.outcome, evidence.available, evidence.primary_evidence, evidence.temporal_correlation, evidence.operational_correlation, evidence.occurred_at, evidence.ingested_at, evidence.content_hash, evidence.byte_count, evidence.provenance, evidence.payload, evidence.created_at, evidence.updated_at, evidence.baseline_lifecycle_generation, evidence.baseline_deployed_commit, COALESCE(evidence_run.attempt_number, 0) AS source_attempt
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
JOIN remediation_run AS run
    ON run.id = $1
JOIN remediation_series AS series
    ON series.id = run.series_id AND series.incident_id = incident.id
LEFT JOIN remediation_run AS evidence_run
    ON evidence_run.id = evidence.run_id
WHERE evidence.id = $2
  AND ((evidence.run_id IS NULL
        AND evidence.baseline_lifecycle_generation = series.lifecycle_generation
        AND evidence.baseline_deployed_commit = series.deployed_commit)
       OR EXISTS (
           SELECT 1 FROM remediation_run AS series_run
           WHERE series_run.id = evidence.run_id
             AND series_run.series_id = series.id
             AND series_run.attempt_number <= run.attempt_number
       ))
`

type GetRemediationEvidencePageParams struct {
	RunID      pgtype.UUID
	EvidenceID pgtype.UUID
}

type GetRemediationEvidencePageRow struct {
	ID                          pgtype.UUID
	ProjectID                   pgtype.UUID
	EnvironmentID               pgtype.UUID
	SourceID                    pgtype.UUID
	IncidentID                  pgtype.UUID
	RunID                       pgtype.UUID
	ObservationID               pgtype.UUID
	Provider                    string
	EvidenceKind                string
	DeduplicationKey            string
	Classification              string
	Outcome                     string
	Available                   bool
	PrimaryEvidence             bool
	TemporalCorrelation         bool
	OperationalCorrelation      bool
	OccurredAt                  pgtype.Timestamptz
	IngestedAt                  pgtype.Timestamptz
	ContentHash                 string
	ByteCount                   int64
	Provenance                  []byte
	Payload                     []byte
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
	BaselineLifecycleGeneration *int64
	BaselineDeployedCommit      *string
	SourceAttempt               int32
}

func (q *Queries) GetRemediationEvidencePage(ctx context.Context, arg GetRemediationEvidencePageParams) (GetRemediationEvidencePageRow, error) {
	row := q.db.QueryRow(ctx, getRemediationEvidencePage, arg.RunID, arg.EvidenceID)
	var i GetRemediationEvidencePageRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentID,
		&i.RunID,
		&i.ObservationID,
		&i.Provider,
		&i.EvidenceKind,
		&i.DeduplicationKey,
		&i.Classification,
		&i.Outcome,
		&i.Available,
		&i.PrimaryEvidence,
		&i.TemporalCorrelation,
		&i.OperationalCorrelation,
		&i.OccurredAt,
		&i.IngestedAt,
		&i.ContentHash,
		&i.ByteCount,
		&i.Provenance,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.BaselineLifecycleGeneration,
		&i.BaselineDeployedCommit,
		&i.SourceAttempt,
	)
	return i, err
}

const getRemediationEvidenceReadCursor = `-- name: GetRemediationEvidenceReadCursor :one
SELECT token_hash, run_id, evidence_id, content_hash, byte_offset, expires_at, created_at FROM remediation_evidence_read_cursor
WHERE token_hash = $1
  AND run_id = $2
  AND evidence_id = $3
  AND content_hash = $4
`

type GetRemediationEvidenceReadCursorParams struct {
	TokenHash   []byte
	RunID       pgtype.UUID
	EvidenceID  pgtype.UUID
	ContentHash string
}

func (q *Queries) GetRemediationEvidenceReadCursor(ctx context.Context, arg GetRemediationEvidenceReadCursorParams) (RemediationEvidenceReadCursor, error) {
	row := q.db.QueryRow(ctx, getRemediationEvidenceReadCursor,
		arg.TokenHash,
		arg.RunID,
		arg.EvidenceID,
		arg.ContentHash,
	)
	var i RemediationEvidenceReadCursor
	err := row.Scan(
		&i.TokenHash,
		&i.RunID,
		&i.EvidenceID,
		&i.ContentHash,
		&i.ByteOffset,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}

const getRemediationLifecycleEffect = `-- name: GetRemediationLifecycleEffect :one
SELECT id, run_id, effect_kind, idempotency_key, state, attempt, baseline_commit, workspace_id, base_tree_hash, result_tree_hash, artifact_ref, content_hash, command_id, command_version, validation_known, validation_passed, branch_ref, target_branch, commit_hash, draft_change_ref, compare_url, error_code, summary, created_at, updated_at FROM remediation_lifecycle_effect
WHERE run_id = $1
  AND effect_kind = $2
  AND idempotency_key = $3
`

type GetRemediationLifecycleEffectParams struct {
	RunID          pgtype.UUID
	EffectKind     string
	IdempotencyKey string
}

func (q *Queries) GetRemediationLifecycleEffect(ctx context.Context, arg GetRemediationLifecycleEffectParams) (RemediationLifecycleEffect, error) {
	row := q.db.QueryRow(ctx, getRemediationLifecycleEffect, arg.RunID, arg.EffectKind, arg.IdempotencyKey)
	var i RemediationLifecycleEffect
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.EffectKind,
		&i.IdempotencyKey,
		&i.State,
		&i.Attempt,
		&i.BaselineCommit,
		&i.WorkspaceID,
		&i.BaseTreeHash,
		&i.ResultTreeHash,
		&i.ArtifactRef,
		&i.ContentHash,
		&i.CommandID,
		&i.CommandVersion,
		&i.ValidationKnown,
		&i.ValidationPassed,
		&i.BranchRef,
		&i.TargetBranch,
		&i.CommitHash,
		&i.DraftChangeRef,
		&i.CompareUrl,
		&i.ErrorCode,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRemediationPlansByRunID = `-- name: GetRemediationPlansByRunID :many
SELECT id, run_id, sequence, title, rationale, risk_class, is_recommended, created_at, plan_key, evidence_refs, affected_files, rollback_strategy FROM remediation_plan
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) GetRemediationPlansByRunID(ctx context.Context, runID pgtype.UUID) ([]RemediationPlan, error) {
	rows, err := q.db.Query(ctx, getRemediationPlansByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationPlan
	for rows.Next() {
		var i RemediationPlan
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.Title,
			&i.Rationale,
			&i.RiskClass,
			&i.IsRecommended,
			&i.CreatedAt,
			&i.PlanKey,
			&i.EvidenceRefs,
			&i.AffectedFiles,
			&i.RollbackStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationRun = `-- name: GetRemediationRun :one
SELECT id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version, continuation_of_run_id, trigger_reason, continuation_reason, context_version, terminal_reason, retryable, agent_loop_mode, agent_loop_policy_version, analysis_only FROM remediation_run WHERE id = $1
`

func (q *Queries) GetRemediationRun(ctx context.Context, id pgtype.UUID) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, getRemediationRun, id)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
		&i.ContinuationOfRunID,
		&i.TriggerReason,
		&i.ContinuationReason,
		&i.ContextVersion,
		&i.TerminalReason,
		&i.Retryable,
		&i.AgentLoopMode,
		&i.AgentLoopPolicyVersion,
		&i.AnalysisOnly,
	)
	return i, err
}

const getRemediationRunProject = `-- name: GetRemediationRunProject :one
SELECT incidents.project_id
FROM remediation_run
JOIN remediation_series ON remediation_series.id = remediation_run.series_id
JOIN incidents ON incidents.id = remediation_series.incident_id
WHERE remediation_run.id = $1
`

func (q *Queries) GetRemediationRunProject(ctx context.Context, runID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRemediationRunProject, runID)
	var project_id pgtype.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const getRemediationRunsBySeriesID = `-- name: GetRemediationRunsBySeriesID :many
SELECT id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version, continuation_of_run_id, trigger_reason, continuation_reason, context_version, terminal_reason, retryable, agent_loop_mode, agent_loop_policy_version, analysis_only FROM remediation_run
WHERE series_id = $1
ORDER BY attempt_number ASC
`

func (q *Queries) GetRemediationRunsBySeriesID(ctx context.Context, seriesID pgtype.UUID) ([]RemediationRun, error) {
	rows, err := q.db.Query(ctx, getRemediationRunsBySeriesID, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationRun
	for rows.Next() {
		var i RemediationRun
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.AttemptNumber,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.ElapsedMs,
			&i.ModelCalls,
			&i.ModelTokensIn,
			&i.ModelTokensOut,
			&i.ModelCostCents,
			&i.ModelProvider,
			&i.ModelName,
			&i.ToolCalls,
			&i.EvidenceBytes,
			&i.RepositoryBytes,
			&i.Version,
			&i.ContinuationOfRunID,
			&i.TriggerReason,
			&i.ContinuationReason,
			&i.ContextVersion,
			&i.TerminalReason,
			&i.Retryable,
			&i.AgentLoopMode,
			&i.AgentLoopPolicyVersion,
			&i.AnalysisOnly,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationSeries = `-- name: GetRemediationSeries :one
SELECT id, incident_id, lifecycle_generation, deployed_commit, created_at FROM remediation_series
WHERE incident_id = $1 AND lifecycle_generation = $2 AND deployed_commit = $3
`

type GetRemediationSeriesParams struct {
	IncidentID          pgtype.UUID
	LifecycleGeneration int64
	DeployedCommit      string
}

func (q *Queries) GetRemediationSeries(ctx context.Context, arg GetRemediationSeriesParams) (RemediationSeries, error) {
	row := q.db.QueryRow(ctx, getRemediationSeries, arg.IncidentID, arg.LifecycleGeneration, arg.DeployedCommit)
	var i RemediationSeries
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.CreatedAt,
	)
	return i, err
}

const getRemediationSeriesByID = `-- name: GetRemediationSeriesByID :one
SELECT id, incident_id, lifecycle_generation, deployed_commit, created_at FROM remediation_series WHERE id = $1
`

func (q *Queries) GetRemediationSeriesByID(ctx context.Context, id pgtype.UUID) (RemediationSeries, error) {
	row := q.db.QueryRow(ctx, getRemediationSeriesByID, id)
	var i RemediationSeries
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.CreatedAt,
	)
	return i, err
}

const getRemediationSubmittedDiagnosesByRunID = `-- name: GetRemediationSubmittedDiagnosesByRunID :many
SELECT id, run_id, sequence, fixability_class, confidence_score, reasoning, contradictions, missing_evidence, evidence_citations, recommended_next_action, correction_kind, correction_evidence, correction_count, corrected, gate_outcome, decision_id, submitted_at FROM remediation_submitted_diagnosis
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) GetRemediationSubmittedDiagnosesByRunID(ctx context.Context, runID pgtype.UUID) ([]RemediationSubmittedDiagnosis, error) {
	rows, err := q.db.Query(ctx, getRemediationSubmittedDiagnosesByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationSubmittedDiagnosis
	for rows.Next() {
		var i RemediationSubmittedDiagnosis
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.FixabilityClass,
			&i.ConfidenceScore,
			&i.Reasoning,
			&i.Contradictions,
			&i.MissingEvidence,
			&i.EvidenceCitations,
			&i.RecommendedNextAction,
			&i.CorrectionKind,
			&i.CorrectionEvidence,
			&i.CorrectionCount,
			&i.Corrected,
			&i.GateOutcome,
			&i.DecisionID,
			&i.SubmittedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationToolInvocationsByRunID = `-- name: GetRemediationToolInvocationsByRunID :many
SELECT id, run_id, sequence, tool_name, phase, invoked_at, duration_ms, outcome, outcome_ref, evidence_ids, error_code FROM remediation_tool_invocation
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) GetRemediationToolInvocationsByRunID(ctx context.Context, runID pgtype.UUID) ([]RemediationToolInvocation, error) {
	rows, err := q.db.Query(ctx, getRemediationToolInvocationsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationToolInvocation
	for rows.Next() {
		var i RemediationToolInvocation
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.ToolName,
			&i.Phase,
			&i.InvokedAt,
			&i.DurationMs,
			&i.Outcome,
			&i.OutcomeRef,
			&i.EvidenceIds,
			&i.ErrorCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationToolPolicy = `-- name: GetRemediationToolPolicy :one
SELECT project_id, source_id, version, policy_hash, entries
FROM remediation_tool_policy
WHERE project_id = $1 AND source_id = $2
`

type GetRemediationToolPolicyParams struct {
	ProjectID pgtype.UUID
	SourceID  pgtype.UUID
}

type GetRemediationToolPolicyRow struct {
	ProjectID  pgtype.UUID
	SourceID   pgtype.UUID
	Version    int64
	PolicyHash string
	Entries    []byte
}

func (q *Queries) GetRemediationToolPolicy(ctx context.Context, arg GetRemediationToolPolicyParams) (GetRemediationToolPolicyRow, error) {
	row := q.db.QueryRow(ctx, getRemediationToolPolicy, arg.ProjectID, arg.SourceID)
	var i GetRemediationToolPolicyRow
	err := row.Scan(
		&i.ProjectID,
		&i.SourceID,
		&i.Version,
		&i.PolicyHash,
		&i.Entries,
	)
	return i, err
}

const getRemediationWorkingMemory = `-- name: GetRemediationWorkingMemory :one
SELECT run_id, sequence, context_version, observed_run_version, phase, content_hash, updated_at FROM remediation_working_memory WHERE run_id = $1
`

func (q *Queries) GetRemediationWorkingMemory(ctx context.Context, runID pgtype.UUID) (RemediationWorkingMemory, error) {
	row := q.db.QueryRow(ctx, getRemediationWorkingMemory, runID)
	var i RemediationWorkingMemory
	err := row.Scan(
		&i.RunID,
		&i.Sequence,
		&i.ContextVersion,
		&i.ObservedRunVersion,
		&i.Phase,
		&i.ContentHash,
		&i.UpdatedAt,
	)
	return i, err
}

const incrementRunCounters = `-- name: IncrementRunCounters :one
UPDATE remediation_run
SET model_calls = model_calls + $2,
    model_tokens_in = model_tokens_in + $3,
    model_tokens_out = model_tokens_out + $4,
    model_cost_cents = model_cost_cents + $5,
    model_provider = CASE
        WHEN length($6::text) > 0 THEN $6::text
        ELSE model_provider
    END,
    model_name = CASE
        WHEN length($7::text) > 0 THEN $7::text
        ELSE model_name
    END,
    tool_calls = tool_calls + $8,
    evidence_bytes = evidence_bytes + $9,
    repository_bytes = repository_bytes + $10,
    version = version + 1
WHERE id = $1
RETURNING id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version, continuation_of_run_id, trigger_reason, continuation_reason, context_version, terminal_reason, retryable, agent_loop_mode, agent_loop_policy_version, analysis_only
`

type IncrementRunCountersParams struct {
	ID              pgtype.UUID
	ModelCalls      int32
	ModelTokensIn   int64
	ModelTokensOut  int64
	ModelCostCents  int64
	ModelProvider   string
	ModelName       string
	ToolCalls       int32
	EvidenceBytes   int64
	RepositoryBytes int64
}

func (q *Queries) IncrementRunCounters(ctx context.Context, arg IncrementRunCountersParams) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, incrementRunCounters,
		arg.ID,
		arg.ModelCalls,
		arg.ModelTokensIn,
		arg.ModelTokensOut,
		arg.ModelCostCents,
		arg.ModelProvider,
		arg.ModelName,
		arg.ToolCalls,
		arg.EvidenceBytes,
		arg.RepositoryBytes,
	)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
		&i.ContinuationOfRunID,
		&i.TriggerReason,
		&i.ContinuationReason,
		&i.ContextVersion,
		&i.TerminalReason,
		&i.Retryable,
		&i.AgentLoopMode,
		&i.AgentLoopPolicyVersion,
		&i.AnalysisOnly,
	)
	return i, err
}

const listContinuationEvidenceIndex = `-- name: ListContinuationEvidenceIndex :many
SELECT evidence.id, evidence.evidence_kind, evidence.provider, evidence.classification,
       evidence.content_hash, COALESCE(evidence_run.attempt_number, 0) AS source_attempt
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
JOIN remediation_series AS series
    ON series.id = $1 AND series.incident_id = incident.id
LEFT JOIN remediation_run AS evidence_run
    ON evidence_run.id = evidence.run_id
WHERE evidence.evidence_kind <> 'runtime'
  AND ((evidence.run_id IS NULL
        AND evidence.baseline_lifecycle_generation = series.lifecycle_generation
        AND evidence.baseline_deployed_commit = series.deployed_commit)
       OR EXISTS (
           SELECT 1 FROM remediation_run AS series_run
           WHERE series_run.id = evidence.run_id
             AND series_run.series_id = series.id
             AND series_run.attempt_number <= $2
       ))
ORDER BY evidence.created_at ASC, evidence.id ASC
LIMIT $3
`

type ListContinuationEvidenceIndexParams struct {
	SeriesID             pgtype.UUID
	ThroughAttemptNumber int32
	ResultLimit          int32
}

type ListContinuationEvidenceIndexRow struct {
	ID             pgtype.UUID
	EvidenceKind   string
	Provider       string
	Classification string
	ContentHash    string
	SourceAttempt  int32
}

func (q *Queries) ListContinuationEvidenceIndex(ctx context.Context, arg ListContinuationEvidenceIndexParams) ([]ListContinuationEvidenceIndexRow, error) {
	rows, err := q.db.Query(ctx, listContinuationEvidenceIndex, arg.SeriesID, arg.ThroughAttemptNumber, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListContinuationEvidenceIndexRow
	for rows.Next() {
		var i ListContinuationEvidenceIndexRow
		if err := rows.Scan(
			&i.ID,
			&i.EvidenceKind,
			&i.Provider,
			&i.Classification,
			&i.ContentHash,
			&i.SourceAttempt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listContinuationRuntimeEvidence = `-- name: ListContinuationRuntimeEvidence :many
SELECT evidence.id, evidence.project_id, evidence.environment_id, evidence.source_id, evidence.incident_id, evidence.run_id, evidence.observation_id, evidence.provider, evidence.evidence_kind, evidence.deduplication_key, evidence.classification, evidence.outcome, evidence.available, evidence.primary_evidence, evidence.temporal_correlation, evidence.operational_correlation, evidence.occurred_at, evidence.ingested_at, evidence.content_hash, evidence.byte_count, evidence.provenance, evidence.payload, evidence.created_at, evidence.updated_at, evidence.baseline_lifecycle_generation, evidence.baseline_deployed_commit
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
JOIN remediation_series AS series
    ON series.id = $1 AND series.incident_id = incident.id
WHERE evidence.evidence_kind = 'runtime'
  AND evidence.run_id IS NOT NULL
  AND EXISTS (
      SELECT 1 FROM remediation_run AS evidence_run
      WHERE evidence_run.id = evidence.run_id
        AND evidence_run.series_id = series.id
        AND evidence_run.attempt_number <= $2
  )
ORDER BY evidence.created_at ASC, evidence.id ASC
LIMIT $3
`

type ListContinuationRuntimeEvidenceParams struct {
	SeriesID             pgtype.UUID
	ThroughAttemptNumber int32
	ResultLimit          int32
}

func (q *Queries) ListContinuationRuntimeEvidence(ctx context.Context, arg ListContinuationRuntimeEvidenceParams) ([]RemediationEvidence, error) {
	rows, err := q.db.Query(ctx, listContinuationRuntimeEvidence, arg.SeriesID, arg.ThroughAttemptNumber, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationEvidence
	for rows.Next() {
		var i RemediationEvidence
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SourceID,
			&i.IncidentID,
			&i.RunID,
			&i.ObservationID,
			&i.Provider,
			&i.EvidenceKind,
			&i.DeduplicationKey,
			&i.Classification,
			&i.Outcome,
			&i.Available,
			&i.PrimaryEvidence,
			&i.TemporalCorrelation,
			&i.OperationalCorrelation,
			&i.OccurredAt,
			&i.IngestedAt,
			&i.ContentHash,
			&i.ByteCount,
			&i.Provenance,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaselineLifecycleGeneration,
			&i.BaselineDeployedCommit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemediationCheckpointEvents = `-- name: ListRemediationCheckpointEvents :many
SELECT id, run_id, sequence, trigger_reason, payload, content_hash, created_at FROM remediation_checkpoint_event
WHERE run_id = $1
ORDER BY sequence DESC
LIMIT $2
`

type ListRemediationCheckpointEventsParams struct {
	RunID       pgtype.UUID
	ResultLimit int32
}

func (q *Queries) ListRemediationCheckpointEvents(ctx context.Context, arg ListRemediationCheckpointEventsParams) ([]RemediationCheckpointEvent, error) {
	rows, err := q.db.Query(ctx, listRemediationCheckpointEvents, arg.RunID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationCheckpointEvent
	for rows.Next() {
		var i RemediationCheckpointEvent
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.TriggerReason,
			&i.Payload,
			&i.ContentHash,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemediationEvidenceForObservation = `-- name: ListRemediationEvidenceForObservation :many
SELECT evidence.id, evidence.project_id, evidence.environment_id, evidence.source_id, evidence.incident_id, evidence.run_id, evidence.observation_id, evidence.provider, evidence.evidence_kind, evidence.deduplication_key, evidence.classification, evidence.outcome, evidence.available, evidence.primary_evidence, evidence.temporal_correlation, evidence.operational_correlation, evidence.occurred_at, evidence.ingested_at, evidence.content_hash, evidence.byte_count, evidence.provenance, evidence.payload, evidence.created_at, evidence.updated_at, evidence.baseline_lifecycle_generation, evidence.baseline_deployed_commit
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
WHERE evidence.incident_id = $1
  AND evidence.observation_id = $2
  AND evidence.run_id IS NULL
ORDER BY
    CASE WHEN evidence.provider = 'tencent_cls'
        AND evidence.evidence_kind = 'provider_detail'
        AND evidence.classification = 'direct_fault'
        AND evidence.available
        AND evidence.outcome = 'success'
        AND evidence.provenance->>'adapter' = 'tencent_cls'
        AND evidence.provenance->>'detail_capability_validated' = 'true'
        AND evidence.provenance->>'detail_resolution' = 'validated_provider_detail_get_alert_detail'
        THEN 0 ELSE 1 END,
    evidence.created_at ASC, evidence.id ASC
LIMIT $3
`

type ListRemediationEvidenceForObservationParams struct {
	IncidentID    pgtype.UUID
	ObservationID pgtype.UUID
	ResultLimit   int32
}

func (q *Queries) ListRemediationEvidenceForObservation(ctx context.Context, arg ListRemediationEvidenceForObservationParams) ([]RemediationEvidence, error) {
	rows, err := q.db.Query(ctx, listRemediationEvidenceForObservation, arg.IncidentID, arg.ObservationID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationEvidence
	for rows.Next() {
		var i RemediationEvidence
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SourceID,
			&i.IncidentID,
			&i.RunID,
			&i.ObservationID,
			&i.Provider,
			&i.EvidenceKind,
			&i.DeduplicationKey,
			&i.Classification,
			&i.Outcome,
			&i.Available,
			&i.PrimaryEvidence,
			&i.TemporalCorrelation,
			&i.OperationalCorrelation,
			&i.OccurredAt,
			&i.IngestedAt,
			&i.ContentHash,
			&i.ByteCount,
			&i.Provenance,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaselineLifecycleGeneration,
			&i.BaselineDeployedCommit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemediationEvidenceForRun = `-- name: ListRemediationEvidenceForRun :many
SELECT evidence.id, evidence.project_id, evidence.environment_id, evidence.source_id, evidence.incident_id, evidence.run_id, evidence.observation_id, evidence.provider, evidence.evidence_kind, evidence.deduplication_key, evidence.classification, evidence.outcome, evidence.available, evidence.primary_evidence, evidence.temporal_correlation, evidence.operational_correlation, evidence.occurred_at, evidence.ingested_at, evidence.content_hash, evidence.byte_count, evidence.provenance, evidence.payload, evidence.created_at, evidence.updated_at, evidence.baseline_lifecycle_generation, evidence.baseline_deployed_commit
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
JOIN remediation_run AS run
    ON run.id = $1
JOIN remediation_series AS series
    ON series.id = run.series_id AND series.incident_id = incident.id
WHERE ((evidence.run_id IS NULL
        AND evidence.baseline_lifecycle_generation = series.lifecycle_generation
        AND evidence.baseline_deployed_commit = series.deployed_commit)
       OR EXISTS (
           SELECT 1 FROM remediation_run AS evidence_run
           WHERE evidence_run.id = evidence.run_id
             AND evidence_run.series_id = series.id
             AND evidence_run.attempt_number <= run.attempt_number
       ))
ORDER BY evidence.created_at ASC, evidence.id ASC
LIMIT $2
`

type ListRemediationEvidenceForRunParams struct {
	RunID       pgtype.UUID
	ResultLimit int32
}

func (q *Queries) ListRemediationEvidenceForRun(ctx context.Context, arg ListRemediationEvidenceForRunParams) ([]RemediationEvidence, error) {
	rows, err := q.db.Query(ctx, listRemediationEvidenceForRun, arg.RunID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationEvidence
	for rows.Next() {
		var i RemediationEvidence
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SourceID,
			&i.IncidentID,
			&i.RunID,
			&i.ObservationID,
			&i.Provider,
			&i.EvidenceKind,
			&i.DeduplicationKey,
			&i.Classification,
			&i.Outcome,
			&i.Available,
			&i.PrimaryEvidence,
			&i.TemporalCorrelation,
			&i.OperationalCorrelation,
			&i.OccurredAt,
			&i.IngestedAt,
			&i.ContentHash,
			&i.ByteCount,
			&i.Provenance,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.BaselineLifecycleGeneration,
			&i.BaselineDeployedCommit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemediationLifecycleEffects = `-- name: ListRemediationLifecycleEffects :many
SELECT id, run_id, effect_kind, idempotency_key, state, attempt, baseline_commit, workspace_id, base_tree_hash, result_tree_hash, artifact_ref, content_hash, command_id, command_version, validation_known, validation_passed, branch_ref, target_branch, commit_hash, draft_change_ref, compare_url, error_code, summary, created_at, updated_at FROM remediation_lifecycle_effect
WHERE run_id = $1
ORDER BY updated_at ASC, id ASC
`

func (q *Queries) ListRemediationLifecycleEffects(ctx context.Context, runID pgtype.UUID) ([]RemediationLifecycleEffect, error) {
	rows, err := q.db.Query(ctx, listRemediationLifecycleEffects, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationLifecycleEffect
	for rows.Next() {
		var i RemediationLifecycleEffect
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.EffectKind,
			&i.IdempotencyKey,
			&i.State,
			&i.Attempt,
			&i.BaselineCommit,
			&i.WorkspaceID,
			&i.BaseTreeHash,
			&i.ResultTreeHash,
			&i.ArtifactRef,
			&i.ContentHash,
			&i.CommandID,
			&i.CommandVersion,
			&i.ValidationKnown,
			&i.ValidationPassed,
			&i.BranchRef,
			&i.TargetBranch,
			&i.CommitHash,
			&i.DraftChangeRef,
			&i.CompareUrl,
			&i.ErrorCode,
			&i.Summary,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockRemediationIncidentContextVersion = `-- name: LockRemediationIncidentContextVersion :one
SELECT version FROM incidents WHERE id = $1 FOR SHARE
`

func (q *Queries) LockRemediationIncidentContextVersion(ctx context.Context, id pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, lockRemediationIncidentContextVersion, id)
	var version int64
	err := row.Scan(&version)
	return version, err
}

const lockRemediationSeriesForRun = `-- name: LockRemediationSeriesForRun :one
SELECT series.id, series.incident_id, series.lifecycle_generation, series.deployed_commit, series.created_at
FROM remediation_series AS series
JOIN remediation_run AS run ON run.series_id = series.id
WHERE run.id = $1
FOR UPDATE OF series
`

func (q *Queries) LockRemediationSeriesForRun(ctx context.Context, runID pgtype.UUID) (RemediationSeries, error) {
	row := q.db.QueryRow(ctx, lockRemediationSeriesForRun, runID)
	var i RemediationSeries
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.CreatedAt,
	)
	return i, err
}

const updateRemediationRunState = `-- name: UpdateRemediationRunState :one
UPDATE remediation_run
SET state = $2,
    ended_at = CASE WHEN $3::boolean THEN now() ELSE NULL END,
    elapsed_ms = CASE WHEN $3::boolean THEN EXTRACT(EPOCH FROM (now() - started_at)) * 1000 ELSE NULL END,
    terminal_reason = CASE WHEN $3::boolean THEN $5::text ELSE '' END,
    retryable = CASE WHEN $3::boolean THEN $6::boolean ELSE false END,
    version = version + 1
WHERE id = $1 AND version = $4
RETURNING id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version, continuation_of_run_id, trigger_reason, continuation_reason, context_version, terminal_reason, retryable, agent_loop_mode, agent_loop_policy_version, analysis_only
`

type UpdateRemediationRunStateParams struct {
	ID             pgtype.UUID
	State          string
	Column3        bool
	Version        int64
	TerminalReason string
	Retryable      bool
}

func (q *Queries) UpdateRemediationRunState(ctx context.Context, arg UpdateRemediationRunStateParams) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, updateRemediationRunState,
		arg.ID,
		arg.State,
		arg.Column3,
		arg.Version,
		arg.TerminalReason,
		arg.Retryable,
	)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
		&i.ContinuationOfRunID,
		&i.TriggerReason,
		&i.ContinuationReason,
		&i.ContextVersion,
		&i.TerminalReason,
		&i.Retryable,
		&i.AgentLoopMode,
		&i.AgentLoopPolicyVersion,
		&i.AnalysisOnly,
	)
	return i, err
}

const upsertRemediationEvidenceAssessment = `-- name: UpsertRemediationEvidenceAssessment :one
INSERT INTO remediation_evidence_assessment (
    run_id, project_id, incident_id, confidence_cap, effective_confidence,
    planning_eligible, outcome, reasons, missing_evidence, contradictions,
    direct_evidence_ids
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
ON CONFLICT (run_id)
DO UPDATE SET
    confidence_cap = EXCLUDED.confidence_cap,
    effective_confidence = EXCLUDED.effective_confidence,
    planning_eligible = EXCLUDED.planning_eligible,
    outcome = EXCLUDED.outcome,
    reasons = EXCLUDED.reasons,
    missing_evidence = EXCLUDED.missing_evidence,
    contradictions = EXCLUDED.contradictions,
    direct_evidence_ids = EXCLUDED.direct_evidence_ids,
    assessed_at = clock_timestamp()
RETURNING run_id, project_id, incident_id, confidence_cap, effective_confidence, planning_eligible, outcome, reasons, missing_evidence, contradictions, direct_evidence_ids, assessed_at
`

type UpsertRemediationEvidenceAssessmentParams struct {
	RunID               pgtype.UUID
	ProjectID           pgtype.UUID
	IncidentID          pgtype.UUID
	ConfidenceCap       pgtype.Numeric
	EffectiveConfidence pgtype.Numeric
	PlanningEligible    bool
	Outcome             string
	Reasons             []string
	MissingEvidence     []string
	Contradictions      []string
	DirectEvidenceIds   []string
}

func (q *Queries) UpsertRemediationEvidenceAssessment(ctx context.Context, arg UpsertRemediationEvidenceAssessmentParams) (RemediationEvidenceAssessment, error) {
	row := q.db.QueryRow(ctx, upsertRemediationEvidenceAssessment,
		arg.RunID,
		arg.ProjectID,
		arg.IncidentID,
		arg.ConfidenceCap,
		arg.EffectiveConfidence,
		arg.PlanningEligible,
		arg.Outcome,
		arg.Reasons,
		arg.MissingEvidence,
		arg.Contradictions,
		arg.DirectEvidenceIds,
	)
	var i RemediationEvidenceAssessment
	err := row.Scan(
		&i.RunID,
		&i.ProjectID,
		&i.IncidentID,
		&i.ConfidenceCap,
		&i.EffectiveConfidence,
		&i.PlanningEligible,
		&i.Outcome,
		&i.Reasons,
		&i.MissingEvidence,
		&i.Contradictions,
		&i.DirectEvidenceIds,
		&i.AssessedAt,
	)
	return i, err
}

const upsertRemediationLifecycleEffect = `-- name: UpsertRemediationLifecycleEffect :one
INSERT INTO remediation_lifecycle_effect (
    run_id, effect_kind, idempotency_key, state, attempt, baseline_commit,
    workspace_id, base_tree_hash, result_tree_hash, artifact_ref, content_hash,
    command_id, command_version, validation_known, validation_passed, branch_ref, target_branch,
    commit_hash, draft_change_ref, compare_url, error_code, summary
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7,
    $8, $9, $10,
    $11, $12, $13,
    $14, $15, $16, $17,
    $18, $19, $20,
    $21, $22
)
ON CONFLICT (run_id, effect_kind, idempotency_key)
DO UPDATE SET
    state = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.state ELSE EXCLUDED.state END,
    attempt = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.attempt ELSE EXCLUDED.attempt END,
    baseline_commit = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.baseline_commit ELSE EXCLUDED.baseline_commit END,
    workspace_id = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.workspace_id ELSE EXCLUDED.workspace_id END,
    base_tree_hash = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.base_tree_hash ELSE EXCLUDED.base_tree_hash END,
    result_tree_hash = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.result_tree_hash ELSE EXCLUDED.result_tree_hash END,
    artifact_ref = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.artifact_ref ELSE EXCLUDED.artifact_ref END,
    content_hash = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.content_hash ELSE EXCLUDED.content_hash END,
    command_id = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.command_id ELSE EXCLUDED.command_id END,
    command_version = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.command_version ELSE EXCLUDED.command_version END,
    validation_known = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.validation_known ELSE EXCLUDED.validation_known END,
    validation_passed = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.validation_passed ELSE EXCLUDED.validation_passed END,
    branch_ref = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.branch_ref ELSE EXCLUDED.branch_ref END,
    target_branch = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.target_branch ELSE EXCLUDED.target_branch END,
    commit_hash = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.commit_hash ELSE EXCLUDED.commit_hash END,
    draft_change_ref = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.draft_change_ref ELSE EXCLUDED.draft_change_ref END,
    compare_url = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.compare_url ELSE EXCLUDED.compare_url END,
    error_code = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.error_code ELSE EXCLUDED.error_code END,
    summary = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.summary ELSE EXCLUDED.summary END,
    updated_at = CASE WHEN remediation_lifecycle_effect.state = 'succeeded'
        THEN remediation_lifecycle_effect.updated_at ELSE clock_timestamp() END
RETURNING id, run_id, effect_kind, idempotency_key, state, attempt, baseline_commit, workspace_id, base_tree_hash, result_tree_hash, artifact_ref, content_hash, command_id, command_version, validation_known, validation_passed, branch_ref, target_branch, commit_hash, draft_change_ref, compare_url, error_code, summary, created_at, updated_at
`

type UpsertRemediationLifecycleEffectParams struct {
	RunID            pgtype.UUID
	EffectKind       string
	IdempotencyKey   string
	State            string
	Attempt          int32
	BaselineCommit   string
	WorkspaceID      string
	BaseTreeHash     string
	ResultTreeHash   string
	ArtifactRef      string
	ContentHash      string
	CommandID        string
	CommandVersion   int64
	ValidationKnown  bool
	ValidationPassed bool
	BranchRef        string
	TargetBranch     string
	CommitHash       string
	DraftChangeRef   string
	CompareUrl       string
	ErrorCode        string
	Summary          string
}

func (q *Queries) UpsertRemediationLifecycleEffect(ctx context.Context, arg UpsertRemediationLifecycleEffectParams) (RemediationLifecycleEffect, error) {
	row := q.db.QueryRow(ctx, upsertRemediationLifecycleEffect,
		arg.RunID,
		arg.EffectKind,
		arg.IdempotencyKey,
		arg.State,
		arg.Attempt,
		arg.BaselineCommit,
		arg.WorkspaceID,
		arg.BaseTreeHash,
		arg.ResultTreeHash,
		arg.ArtifactRef,
		arg.ContentHash,
		arg.CommandID,
		arg.CommandVersion,
		arg.ValidationKnown,
		arg.ValidationPassed,
		arg.BranchRef,
		arg.TargetBranch,
		arg.CommitHash,
		arg.DraftChangeRef,
		arg.CompareUrl,
		arg.ErrorCode,
		arg.Summary,
	)
	var i RemediationLifecycleEffect
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.EffectKind,
		&i.IdempotencyKey,
		&i.State,
		&i.Attempt,
		&i.BaselineCommit,
		&i.WorkspaceID,
		&i.BaseTreeHash,
		&i.ResultTreeHash,
		&i.ArtifactRef,
		&i.ContentHash,
		&i.CommandID,
		&i.CommandVersion,
		&i.ValidationKnown,
		&i.ValidationPassed,
		&i.BranchRef,
		&i.TargetBranch,
		&i.CommitHash,
		&i.DraftChangeRef,
		&i.CompareUrl,
		&i.ErrorCode,
		&i.Summary,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertRemediationWorkingMemory = `-- name: UpsertRemediationWorkingMemory :one
INSERT INTO remediation_working_memory (
    run_id,
    sequence,
    context_version,
    observed_run_version,
    phase,
    content_hash
) VALUES (
    $1, $2, $3,
    $4,
    $5, $6
)
ON CONFLICT (run_id)
DO UPDATE SET
    sequence = EXCLUDED.sequence,
    context_version = EXCLUDED.context_version,
    observed_run_version = EXCLUDED.observed_run_version,
    phase = EXCLUDED.phase,
    content_hash = EXCLUDED.content_hash,
    updated_at = clock_timestamp()
RETURNING run_id, sequence, context_version, observed_run_version, phase, content_hash, updated_at
`

type UpsertRemediationWorkingMemoryParams struct {
	RunID              pgtype.UUID
	Sequence           int64
	ContextVersion     int64
	ObservedRunVersion int64
	Phase              string
	ContentHash        string
}

func (q *Queries) UpsertRemediationWorkingMemory(ctx context.Context, arg UpsertRemediationWorkingMemoryParams) (RemediationWorkingMemory, error) {
	row := q.db.QueryRow(ctx, upsertRemediationWorkingMemory,
		arg.RunID,
		arg.Sequence,
		arg.ContextVersion,
		arg.ObservedRunVersion,
		arg.Phase,
		arg.ContentHash,
	)
	var i RemediationWorkingMemory
	err := row.Scan(
		&i.RunID,
		&i.Sequence,
		&i.ContextVersion,
		&i.ObservedRunVersion,
		&i.Phase,
		&i.ContentHash,
		&i.UpdatedAt,
	)
	return i, err
}
