// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: remediation.sql

package remediationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRemediationArtifact = `-- name: CreateRemediationArtifact :one
INSERT INTO remediation_artifact (
    run_id,
    artifact_type,
    reference_path,
    content_hash,
    size_bytes,
    excerpt
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, artifact_type, reference_path, content_hash, size_bytes, created_at, excerpt
`

type CreateRemediationArtifactParams struct {
	RunID         pgtype.UUID
	ArtifactType  string
	ReferencePath string
	ContentHash   string
	SizeBytes     int64
	Excerpt       string
}

func (q *Queries) CreateRemediationArtifact(ctx context.Context, arg CreateRemediationArtifactParams) (RemediationArtifact, error) {
	row := q.db.QueryRow(ctx, createRemediationArtifact,
		arg.RunID,
		arg.ArtifactType,
		arg.ReferencePath,
		arg.ContentHash,
		arg.SizeBytes,
		arg.Excerpt,
	)
	var i RemediationArtifact
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.ArtifactType,
		&i.ReferencePath,
		&i.ContentHash,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.Excerpt,
	)
	return i, err
}

const createRemediationAuditEvent = `-- name: CreateRemediationAuditEvent :execrows
INSERT INTO audit_events (
    id, project_id, actor_user_id, action, target_type, target_id, summary, metadata
)
SELECT
    $1,
    incidents.project_id,
    NULL,
    $2,
    'remediation_run',
    remediation_run.id,
    $3,
    $4::jsonb
FROM remediation_run
JOIN remediation_series ON remediation_series.id = remediation_run.series_id
JOIN incidents ON incidents.id = remediation_series.incident_id
WHERE remediation_run.id = $5
`

type CreateRemediationAuditEventParams struct {
	AuditID  pgtype.UUID
	Action   string
	Summary  string
	Metadata []byte
	RunID    pgtype.UUID
}

func (q *Queries) CreateRemediationAuditEvent(ctx context.Context, arg CreateRemediationAuditEventParams) (int64, error) {
	result, err := q.db.Exec(ctx, createRemediationAuditEvent,
		arg.AuditID,
		arg.Action,
		arg.Summary,
		arg.Metadata,
		arg.RunID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createRemediationDecision = `-- name: CreateRemediationDecision :one
INSERT INTO remediation_decision (
    run_id,
    sequence,
    fixability_class,
    confidence_score,
    reasoning,
    contradictions,
    missing_evidence,
    evidence_citations,
    recommended_next_action
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, run_id, sequence, fixability_class, confidence_score, reasoning, decided_at, contradictions, missing_evidence, evidence_citations, recommended_next_action
`

type CreateRemediationDecisionParams struct {
	RunID                 pgtype.UUID
	Sequence              int32
	FixabilityClass       string
	ConfidenceScore       pgtype.Numeric
	Reasoning             string
	Contradictions        []string
	MissingEvidence       []string
	EvidenceCitations     []string
	RecommendedNextAction string
}

func (q *Queries) CreateRemediationDecision(ctx context.Context, arg CreateRemediationDecisionParams) (RemediationDecision, error) {
	row := q.db.QueryRow(ctx, createRemediationDecision,
		arg.RunID,
		arg.Sequence,
		arg.FixabilityClass,
		arg.ConfidenceScore,
		arg.Reasoning,
		arg.Contradictions,
		arg.MissingEvidence,
		arg.EvidenceCitations,
		arg.RecommendedNextAction,
	)
	var i RemediationDecision
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.FixabilityClass,
		&i.ConfidenceScore,
		&i.Reasoning,
		&i.DecidedAt,
		&i.Contradictions,
		&i.MissingEvidence,
		&i.EvidenceCitations,
		&i.RecommendedNextAction,
	)
	return i, err
}

const createRemediationEvidence = `-- name: CreateRemediationEvidence :one
INSERT INTO remediation_evidence (
    project_id, environment_id, source_id, incident_id, run_id, observation_id,
    provider, evidence_kind, deduplication_key, classification, outcome,
    available, primary_evidence, temporal_correlation, operational_correlation,
    occurred_at, content_hash, byte_count, provenance, payload
) VALUES (
    $1, $2, $3, $4,
    $5, $6, $7, $8,
    $9, $10, $11,
    $12, $13, $14,
    $15, $16, $17,
    $18, $19, $20
)
ON CONFLICT (project_id, deduplication_key)
DO UPDATE SET
    run_id = COALESCE(EXCLUDED.run_id, remediation_evidence.run_id),
    observation_id = COALESCE(EXCLUDED.observation_id, remediation_evidence.observation_id),
    updated_at = clock_timestamp()
RETURNING id, project_id, environment_id, source_id, incident_id, run_id, observation_id, provider, evidence_kind, deduplication_key, classification, outcome, available, primary_evidence, temporal_correlation, operational_correlation, occurred_at, ingested_at, content_hash, byte_count, provenance, payload, created_at, updated_at
`

type CreateRemediationEvidenceParams struct {
	ProjectID              pgtype.UUID
	EnvironmentID          pgtype.UUID
	SourceID               pgtype.UUID
	IncidentID             pgtype.UUID
	RunID                  pgtype.UUID
	ObservationID          pgtype.UUID
	Provider               string
	EvidenceKind           string
	DeduplicationKey       string
	Classification         string
	Outcome                string
	Available              bool
	PrimaryEvidence        bool
	TemporalCorrelation    bool
	OperationalCorrelation bool
	OccurredAt             pgtype.Timestamptz
	ContentHash            string
	ByteCount              int64
	Provenance             []byte
	Payload                []byte
}

func (q *Queries) CreateRemediationEvidence(ctx context.Context, arg CreateRemediationEvidenceParams) (RemediationEvidence, error) {
	row := q.db.QueryRow(ctx, createRemediationEvidence,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.SourceID,
		arg.IncidentID,
		arg.RunID,
		arg.ObservationID,
		arg.Provider,
		arg.EvidenceKind,
		arg.DeduplicationKey,
		arg.Classification,
		arg.Outcome,
		arg.Available,
		arg.PrimaryEvidence,
		arg.TemporalCorrelation,
		arg.OperationalCorrelation,
		arg.OccurredAt,
		arg.ContentHash,
		arg.ByteCount,
		arg.Provenance,
		arg.Payload,
	)
	var i RemediationEvidence
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentID,
		&i.RunID,
		&i.ObservationID,
		&i.Provider,
		&i.EvidenceKind,
		&i.DeduplicationKey,
		&i.Classification,
		&i.Outcome,
		&i.Available,
		&i.PrimaryEvidence,
		&i.TemporalCorrelation,
		&i.OperationalCorrelation,
		&i.OccurredAt,
		&i.IngestedAt,
		&i.ContentHash,
		&i.ByteCount,
		&i.Provenance,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createRemediationPlan = `-- name: CreateRemediationPlan :one
INSERT INTO remediation_plan (
    run_id,
    sequence,
    title,
    rationale,
    risk_class,
    is_recommended,
    plan_key,
    evidence_refs,
    affected_files,
    rollback_strategy
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, run_id, sequence, title, rationale, risk_class, is_recommended, created_at, plan_key, evidence_refs, affected_files, rollback_strategy
`

type CreateRemediationPlanParams struct {
	RunID            pgtype.UUID
	Sequence         int32
	Title            string
	Rationale        string
	RiskClass        string
	IsRecommended    bool
	PlanKey          string
	EvidenceRefs     []string
	AffectedFiles    []string
	RollbackStrategy string
}

func (q *Queries) CreateRemediationPlan(ctx context.Context, arg CreateRemediationPlanParams) (RemediationPlan, error) {
	row := q.db.QueryRow(ctx, createRemediationPlan,
		arg.RunID,
		arg.Sequence,
		arg.Title,
		arg.Rationale,
		arg.RiskClass,
		arg.IsRecommended,
		arg.PlanKey,
		arg.EvidenceRefs,
		arg.AffectedFiles,
		arg.RollbackStrategy,
	)
	var i RemediationPlan
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.Title,
		&i.Rationale,
		&i.RiskClass,
		&i.IsRecommended,
		&i.CreatedAt,
		&i.PlanKey,
		&i.EvidenceRefs,
		&i.AffectedFiles,
		&i.RollbackStrategy,
	)
	return i, err
}

const createRemediationRun = `-- name: CreateRemediationRun :one
INSERT INTO remediation_run (
    series_id,
    attempt_number,
    state
) VALUES ($1, $2, $3)
RETURNING id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version
`

type CreateRemediationRunParams struct {
	SeriesID      pgtype.UUID
	AttemptNumber int32
	State         string
}

func (q *Queries) CreateRemediationRun(ctx context.Context, arg CreateRemediationRunParams) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, createRemediationRun, arg.SeriesID, arg.AttemptNumber, arg.State)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
	)
	return i, err
}

const createRemediationSeries = `-- name: CreateRemediationSeries :one
INSERT INTO remediation_series (
    incident_id,
    lifecycle_generation,
    deployed_commit
) VALUES ($1, $2, $3)
ON CONFLICT (incident_id, lifecycle_generation, deployed_commit)
DO UPDATE SET id = remediation_series.id
RETURNING id, incident_id, lifecycle_generation, deployed_commit, created_at
`

type CreateRemediationSeriesParams struct {
	IncidentID          pgtype.UUID
	LifecycleGeneration int64
	DeployedCommit      string
}

func (q *Queries) CreateRemediationSeries(ctx context.Context, arg CreateRemediationSeriesParams) (RemediationSeries, error) {
	row := q.db.QueryRow(ctx, createRemediationSeries, arg.IncidentID, arg.LifecycleGeneration, arg.DeployedCommit)
	var i RemediationSeries
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.CreatedAt,
	)
	return i, err
}

const createRemediationToolInvocation = `-- name: CreateRemediationToolInvocation :one
INSERT INTO remediation_tool_invocation (
    run_id,
    sequence,
    tool_name,
    phase,
    duration_ms,
    outcome
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, run_id, sequence, tool_name, phase, invoked_at, duration_ms, outcome
`

type CreateRemediationToolInvocationParams struct {
	RunID      pgtype.UUID
	Sequence   int32
	ToolName   string
	Phase      string
	DurationMs *int64
	Outcome    string
}

func (q *Queries) CreateRemediationToolInvocation(ctx context.Context, arg CreateRemediationToolInvocationParams) (RemediationToolInvocation, error) {
	row := q.db.QueryRow(ctx, createRemediationToolInvocation,
		arg.RunID,
		arg.Sequence,
		arg.ToolName,
		arg.Phase,
		arg.DurationMs,
		arg.Outcome,
	)
	var i RemediationToolInvocation
	err := row.Scan(
		&i.ID,
		&i.RunID,
		&i.Sequence,
		&i.ToolName,
		&i.Phase,
		&i.InvokedAt,
		&i.DurationMs,
		&i.Outcome,
	)
	return i, err
}

const getLatestRemediationObservationForIncident = `-- name: GetLatestRemediationObservationForIncident :one
SELECT observations.id, observations.project_id, observations.environment_id, observations.source_id, observations.service, observations.occurred_at, observations.level, observations.message, observations.host, observations.request_id, observations.fingerprint, observations.attributes, observations.ingested_at
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
JOIN observations
    ON observations.id = evidence.observation_id
   AND observations.project_id = evidence.project_id
WHERE evidence.incident_id = $1
  AND evidence.run_id IS NULL
  AND evidence.evidence_kind = 'normalized_alert'
ORDER BY evidence.created_at DESC, evidence.id DESC
LIMIT 1
`

func (q *Queries) GetLatestRemediationObservationForIncident(ctx context.Context, incidentID pgtype.UUID) (Observation, error) {
	row := q.db.QueryRow(ctx, getLatestRemediationObservationForIncident, incidentID)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.Service,
		&i.OccurredAt,
		&i.Level,
		&i.Message,
		&i.Host,
		&i.RequestID,
		&i.Fingerprint,
		&i.Attributes,
		&i.IngestedAt,
	)
	return i, err
}

const getRemediationArtifactsByRunID = `-- name: GetRemediationArtifactsByRunID :many
SELECT id, run_id, artifact_type, reference_path, content_hash, size_bytes, created_at, excerpt FROM remediation_artifact
WHERE run_id = $1
ORDER BY created_at ASC
`

func (q *Queries) GetRemediationArtifactsByRunID(ctx context.Context, runID pgtype.UUID) ([]RemediationArtifact, error) {
	rows, err := q.db.Query(ctx, getRemediationArtifactsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationArtifact
	for rows.Next() {
		var i RemediationArtifact
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.ArtifactType,
			&i.ReferencePath,
			&i.ContentHash,
			&i.SizeBytes,
			&i.CreatedAt,
			&i.Excerpt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationDecisionsByRunID = `-- name: GetRemediationDecisionsByRunID :many
SELECT id, run_id, sequence, fixability_class, confidence_score, reasoning, decided_at, contradictions, missing_evidence, evidence_citations, recommended_next_action FROM remediation_decision
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) GetRemediationDecisionsByRunID(ctx context.Context, runID pgtype.UUID) ([]RemediationDecision, error) {
	rows, err := q.db.Query(ctx, getRemediationDecisionsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationDecision
	for rows.Next() {
		var i RemediationDecision
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.FixabilityClass,
			&i.ConfidenceScore,
			&i.Reasoning,
			&i.DecidedAt,
			&i.Contradictions,
			&i.MissingEvidence,
			&i.EvidenceCitations,
			&i.RecommendedNextAction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationEvidenceForRun = `-- name: GetRemediationEvidenceForRun :one
SELECT evidence.id, evidence.project_id, evidence.environment_id, evidence.source_id, evidence.incident_id, evidence.run_id, evidence.observation_id, evidence.provider, evidence.evidence_kind, evidence.deduplication_key, evidence.classification, evidence.outcome, evidence.available, evidence.primary_evidence, evidence.temporal_correlation, evidence.operational_correlation, evidence.occurred_at, evidence.ingested_at, evidence.content_hash, evidence.byte_count, evidence.provenance, evidence.payload, evidence.created_at, evidence.updated_at
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
JOIN remediation_run AS run
    ON run.id = $1
JOIN remediation_series AS series
    ON series.id = run.series_id AND series.incident_id = incident.id
WHERE evidence.id = $2
  AND (evidence.run_id IS NULL OR evidence.run_id = run.id)
`

type GetRemediationEvidenceForRunParams struct {
	RunID      pgtype.UUID
	EvidenceID pgtype.UUID
}

func (q *Queries) GetRemediationEvidenceForRun(ctx context.Context, arg GetRemediationEvidenceForRunParams) (RemediationEvidence, error) {
	row := q.db.QueryRow(ctx, getRemediationEvidenceForRun, arg.RunID, arg.EvidenceID)
	var i RemediationEvidence
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentID,
		&i.RunID,
		&i.ObservationID,
		&i.Provider,
		&i.EvidenceKind,
		&i.DeduplicationKey,
		&i.Classification,
		&i.Outcome,
		&i.Available,
		&i.PrimaryEvidence,
		&i.TemporalCorrelation,
		&i.OperationalCorrelation,
		&i.OccurredAt,
		&i.IngestedAt,
		&i.ContentHash,
		&i.ByteCount,
		&i.Provenance,
		&i.Payload,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRemediationPlansByRunID = `-- name: GetRemediationPlansByRunID :many
SELECT id, run_id, sequence, title, rationale, risk_class, is_recommended, created_at, plan_key, evidence_refs, affected_files, rollback_strategy FROM remediation_plan
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) GetRemediationPlansByRunID(ctx context.Context, runID pgtype.UUID) ([]RemediationPlan, error) {
	rows, err := q.db.Query(ctx, getRemediationPlansByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationPlan
	for rows.Next() {
		var i RemediationPlan
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.Title,
			&i.Rationale,
			&i.RiskClass,
			&i.IsRecommended,
			&i.CreatedAt,
			&i.PlanKey,
			&i.EvidenceRefs,
			&i.AffectedFiles,
			&i.RollbackStrategy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationRun = `-- name: GetRemediationRun :one
SELECT id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version FROM remediation_run WHERE id = $1
`

func (q *Queries) GetRemediationRun(ctx context.Context, id pgtype.UUID) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, getRemediationRun, id)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
	)
	return i, err
}

const getRemediationRunProject = `-- name: GetRemediationRunProject :one
SELECT incidents.project_id
FROM remediation_run
JOIN remediation_series ON remediation_series.id = remediation_run.series_id
JOIN incidents ON incidents.id = remediation_series.incident_id
WHERE remediation_run.id = $1
`

func (q *Queries) GetRemediationRunProject(ctx context.Context, runID pgtype.UUID) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRemediationRunProject, runID)
	var project_id pgtype.UUID
	err := row.Scan(&project_id)
	return project_id, err
}

const getRemediationRunsBySeriesID = `-- name: GetRemediationRunsBySeriesID :many
SELECT id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version FROM remediation_run
WHERE series_id = $1
ORDER BY attempt_number ASC
`

func (q *Queries) GetRemediationRunsBySeriesID(ctx context.Context, seriesID pgtype.UUID) ([]RemediationRun, error) {
	rows, err := q.db.Query(ctx, getRemediationRunsBySeriesID, seriesID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationRun
	for rows.Next() {
		var i RemediationRun
		if err := rows.Scan(
			&i.ID,
			&i.SeriesID,
			&i.AttemptNumber,
			&i.State,
			&i.StartedAt,
			&i.EndedAt,
			&i.ElapsedMs,
			&i.ModelCalls,
			&i.ModelTokensIn,
			&i.ModelTokensOut,
			&i.ModelCostCents,
			&i.ModelProvider,
			&i.ModelName,
			&i.ToolCalls,
			&i.EvidenceBytes,
			&i.RepositoryBytes,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationSeries = `-- name: GetRemediationSeries :one
SELECT id, incident_id, lifecycle_generation, deployed_commit, created_at FROM remediation_series
WHERE incident_id = $1 AND lifecycle_generation = $2 AND deployed_commit = $3
`

type GetRemediationSeriesParams struct {
	IncidentID          pgtype.UUID
	LifecycleGeneration int64
	DeployedCommit      string
}

func (q *Queries) GetRemediationSeries(ctx context.Context, arg GetRemediationSeriesParams) (RemediationSeries, error) {
	row := q.db.QueryRow(ctx, getRemediationSeries, arg.IncidentID, arg.LifecycleGeneration, arg.DeployedCommit)
	var i RemediationSeries
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.CreatedAt,
	)
	return i, err
}

const getRemediationSeriesByID = `-- name: GetRemediationSeriesByID :one
SELECT id, incident_id, lifecycle_generation, deployed_commit, created_at FROM remediation_series WHERE id = $1
`

func (q *Queries) GetRemediationSeriesByID(ctx context.Context, id pgtype.UUID) (RemediationSeries, error) {
	row := q.db.QueryRow(ctx, getRemediationSeriesByID, id)
	var i RemediationSeries
	err := row.Scan(
		&i.ID,
		&i.IncidentID,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.CreatedAt,
	)
	return i, err
}

const getRemediationToolInvocationsByRunID = `-- name: GetRemediationToolInvocationsByRunID :many
SELECT id, run_id, sequence, tool_name, phase, invoked_at, duration_ms, outcome FROM remediation_tool_invocation
WHERE run_id = $1
ORDER BY sequence ASC
`

func (q *Queries) GetRemediationToolInvocationsByRunID(ctx context.Context, runID pgtype.UUID) ([]RemediationToolInvocation, error) {
	rows, err := q.db.Query(ctx, getRemediationToolInvocationsByRunID, runID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationToolInvocation
	for rows.Next() {
		var i RemediationToolInvocation
		if err := rows.Scan(
			&i.ID,
			&i.RunID,
			&i.Sequence,
			&i.ToolName,
			&i.Phase,
			&i.InvokedAt,
			&i.DurationMs,
			&i.Outcome,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRemediationToolPolicy = `-- name: GetRemediationToolPolicy :one
SELECT project_id, source_id, version, policy_hash, entries
FROM remediation_tool_policy
WHERE project_id = $1 AND source_id = $2
`

type GetRemediationToolPolicyParams struct {
	ProjectID pgtype.UUID
	SourceID  pgtype.UUID
}

type GetRemediationToolPolicyRow struct {
	ProjectID  pgtype.UUID
	SourceID   pgtype.UUID
	Version    int64
	PolicyHash string
	Entries    []byte
}

func (q *Queries) GetRemediationToolPolicy(ctx context.Context, arg GetRemediationToolPolicyParams) (GetRemediationToolPolicyRow, error) {
	row := q.db.QueryRow(ctx, getRemediationToolPolicy, arg.ProjectID, arg.SourceID)
	var i GetRemediationToolPolicyRow
	err := row.Scan(
		&i.ProjectID,
		&i.SourceID,
		&i.Version,
		&i.PolicyHash,
		&i.Entries,
	)
	return i, err
}

const incrementRunCounters = `-- name: IncrementRunCounters :one
UPDATE remediation_run
SET model_calls = model_calls + $2,
    model_tokens_in = model_tokens_in + $3,
    model_tokens_out = model_tokens_out + $4,
    model_cost_cents = model_cost_cents + $5,
    model_provider = CASE
        WHEN length($6::text) > 0 THEN $6::text
        ELSE model_provider
    END,
    model_name = CASE
        WHEN length($7::text) > 0 THEN $7::text
        ELSE model_name
    END,
    tool_calls = tool_calls + $8,
    evidence_bytes = evidence_bytes + $9,
    repository_bytes = repository_bytes + $10,
    version = version + 1
WHERE id = $1
RETURNING id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version
`

type IncrementRunCountersParams struct {
	ID              pgtype.UUID
	ModelCalls      int32
	ModelTokensIn   int64
	ModelTokensOut  int64
	ModelCostCents  int64
	ModelProvider   string
	ModelName       string
	ToolCalls       int32
	EvidenceBytes   int64
	RepositoryBytes int64
}

func (q *Queries) IncrementRunCounters(ctx context.Context, arg IncrementRunCountersParams) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, incrementRunCounters,
		arg.ID,
		arg.ModelCalls,
		arg.ModelTokensIn,
		arg.ModelTokensOut,
		arg.ModelCostCents,
		arg.ModelProvider,
		arg.ModelName,
		arg.ToolCalls,
		arg.EvidenceBytes,
		arg.RepositoryBytes,
	)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
	)
	return i, err
}

const listRemediationEvidenceForObservation = `-- name: ListRemediationEvidenceForObservation :many
SELECT evidence.id, evidence.project_id, evidence.environment_id, evidence.source_id, evidence.incident_id, evidence.run_id, evidence.observation_id, evidence.provider, evidence.evidence_kind, evidence.deduplication_key, evidence.classification, evidence.outcome, evidence.available, evidence.primary_evidence, evidence.temporal_correlation, evidence.operational_correlation, evidence.occurred_at, evidence.ingested_at, evidence.content_hash, evidence.byte_count, evidence.provenance, evidence.payload, evidence.created_at, evidence.updated_at
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
WHERE evidence.incident_id = $1
  AND evidence.observation_id = $2
  AND evidence.run_id IS NULL
ORDER BY evidence.created_at ASC, evidence.id ASC
LIMIT $3
`

type ListRemediationEvidenceForObservationParams struct {
	IncidentID    pgtype.UUID
	ObservationID pgtype.UUID
	ResultLimit   int32
}

func (q *Queries) ListRemediationEvidenceForObservation(ctx context.Context, arg ListRemediationEvidenceForObservationParams) ([]RemediationEvidence, error) {
	rows, err := q.db.Query(ctx, listRemediationEvidenceForObservation, arg.IncidentID, arg.ObservationID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationEvidence
	for rows.Next() {
		var i RemediationEvidence
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SourceID,
			&i.IncidentID,
			&i.RunID,
			&i.ObservationID,
			&i.Provider,
			&i.EvidenceKind,
			&i.DeduplicationKey,
			&i.Classification,
			&i.Outcome,
			&i.Available,
			&i.PrimaryEvidence,
			&i.TemporalCorrelation,
			&i.OperationalCorrelation,
			&i.OccurredAt,
			&i.IngestedAt,
			&i.ContentHash,
			&i.ByteCount,
			&i.Provenance,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRemediationEvidenceForRun = `-- name: ListRemediationEvidenceForRun :many
SELECT evidence.id, evidence.project_id, evidence.environment_id, evidence.source_id, evidence.incident_id, evidence.run_id, evidence.observation_id, evidence.provider, evidence.evidence_kind, evidence.deduplication_key, evidence.classification, evidence.outcome, evidence.available, evidence.primary_evidence, evidence.temporal_correlation, evidence.operational_correlation, evidence.occurred_at, evidence.ingested_at, evidence.content_hash, evidence.byte_count, evidence.provenance, evidence.payload, evidence.created_at, evidence.updated_at
FROM remediation_evidence AS evidence
JOIN incidents AS incident
    ON incident.id = evidence.incident_id AND incident.project_id = evidence.project_id
JOIN remediation_run AS run
    ON run.id = $1
JOIN remediation_series AS series
    ON series.id = run.series_id AND series.incident_id = incident.id
WHERE evidence.run_id IS NULL OR evidence.run_id = run.id
ORDER BY evidence.created_at ASC, evidence.id ASC
LIMIT $2
`

type ListRemediationEvidenceForRunParams struct {
	RunID       pgtype.UUID
	ResultLimit int32
}

func (q *Queries) ListRemediationEvidenceForRun(ctx context.Context, arg ListRemediationEvidenceForRunParams) ([]RemediationEvidence, error) {
	rows, err := q.db.Query(ctx, listRemediationEvidenceForRun, arg.RunID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RemediationEvidence
	for rows.Next() {
		var i RemediationEvidence
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SourceID,
			&i.IncidentID,
			&i.RunID,
			&i.ObservationID,
			&i.Provider,
			&i.EvidenceKind,
			&i.DeduplicationKey,
			&i.Classification,
			&i.Outcome,
			&i.Available,
			&i.PrimaryEvidence,
			&i.TemporalCorrelation,
			&i.OperationalCorrelation,
			&i.OccurredAt,
			&i.IngestedAt,
			&i.ContentHash,
			&i.ByteCount,
			&i.Provenance,
			&i.Payload,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateRemediationRunState = `-- name: UpdateRemediationRunState :one
UPDATE remediation_run
SET state = $2,
    ended_at = CASE WHEN $3::boolean THEN now() ELSE ended_at END,
    elapsed_ms = CASE WHEN $3::boolean THEN EXTRACT(EPOCH FROM (now() - started_at)) * 1000 ELSE elapsed_ms END,
    version = version + 1
WHERE id = $1 AND version = $4
RETURNING id, series_id, attempt_number, state, started_at, ended_at, elapsed_ms, model_calls, model_tokens_in, model_tokens_out, model_cost_cents, model_provider, model_name, tool_calls, evidence_bytes, repository_bytes, version
`

type UpdateRemediationRunStateParams struct {
	ID      pgtype.UUID
	State   string
	Column3 bool
	Version int64
}

func (q *Queries) UpdateRemediationRunState(ctx context.Context, arg UpdateRemediationRunStateParams) (RemediationRun, error) {
	row := q.db.QueryRow(ctx, updateRemediationRunState,
		arg.ID,
		arg.State,
		arg.Column3,
		arg.Version,
	)
	var i RemediationRun
	err := row.Scan(
		&i.ID,
		&i.SeriesID,
		&i.AttemptNumber,
		&i.State,
		&i.StartedAt,
		&i.EndedAt,
		&i.ElapsedMs,
		&i.ModelCalls,
		&i.ModelTokensIn,
		&i.ModelTokensOut,
		&i.ModelCostCents,
		&i.ModelProvider,
		&i.ModelName,
		&i.ToolCalls,
		&i.EvidenceBytes,
		&i.RepositoryBytes,
		&i.Version,
	)
	return i, err
}

const upsertRemediationEvidenceAssessment = `-- name: UpsertRemediationEvidenceAssessment :one
INSERT INTO remediation_evidence_assessment (
    run_id, project_id, incident_id, confidence_cap, effective_confidence,
    planning_eligible, outcome, reasons, missing_evidence, contradictions,
    direct_evidence_ids
) VALUES (
    $1, $2, $3,
    $4, $5, $6,
    $7, $8, $9,
    $10, $11
)
ON CONFLICT (run_id)
DO UPDATE SET
    confidence_cap = EXCLUDED.confidence_cap,
    effective_confidence = EXCLUDED.effective_confidence,
    planning_eligible = EXCLUDED.planning_eligible,
    outcome = EXCLUDED.outcome,
    reasons = EXCLUDED.reasons,
    missing_evidence = EXCLUDED.missing_evidence,
    contradictions = EXCLUDED.contradictions,
    direct_evidence_ids = EXCLUDED.direct_evidence_ids,
    assessed_at = clock_timestamp()
RETURNING run_id, project_id, incident_id, confidence_cap, effective_confidence, planning_eligible, outcome, reasons, missing_evidence, contradictions, direct_evidence_ids, assessed_at
`

type UpsertRemediationEvidenceAssessmentParams struct {
	RunID               pgtype.UUID
	ProjectID           pgtype.UUID
	IncidentID          pgtype.UUID
	ConfidenceCap       pgtype.Numeric
	EffectiveConfidence pgtype.Numeric
	PlanningEligible    bool
	Outcome             string
	Reasons             []string
	MissingEvidence     []string
	Contradictions      []string
	DirectEvidenceIds   []string
}

func (q *Queries) UpsertRemediationEvidenceAssessment(ctx context.Context, arg UpsertRemediationEvidenceAssessmentParams) (RemediationEvidenceAssessment, error) {
	row := q.db.QueryRow(ctx, upsertRemediationEvidenceAssessment,
		arg.RunID,
		arg.ProjectID,
		arg.IncidentID,
		arg.ConfidenceCap,
		arg.EffectiveConfidence,
		arg.PlanningEligible,
		arg.Outcome,
		arg.Reasons,
		arg.MissingEvidence,
		arg.Contradictions,
		arg.DirectEvidenceIds,
	)
	var i RemediationEvidenceAssessment
	err := row.Scan(
		&i.RunID,
		&i.ProjectID,
		&i.IncidentID,
		&i.ConfidenceCap,
		&i.EffectiveConfidence,
		&i.PlanningEligible,
		&i.Outcome,
		&i.Reasons,
		&i.MissingEvidence,
		&i.Contradictions,
		&i.DirectEvidenceIds,
		&i.AssessedAt,
	)
	return i, err
}
