// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package observationdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 保存项目 Event Stream 中经过归一化的持久事件。
type Observation struct {
	// 应用生成的 UUIDv7 observation 内部标识。
	ID pgtype.UUID
	// observation 所属项目，是读取隔离的首要条件。
	ProjectID pgtype.UUID
	// 事件产生时对应的同项目 environment。
	EnvironmentID pgtype.UUID
	// 产生该事件的同项目同环境 source。
	SourceID pgtype.UUID
	// 事件的可选 service 标签；为空时可使用 environment 默认值展示。
	Service *string
	// 事件在来源系统中发生的时间。
	OccurredAt pgtype.Timestamptz
	// 归一化日志级别，取值为 debug、info、warn、error 或 critical。
	Level string
	// 归一化后的事件正文，仍受项目访问和 retention 约束。
	Message string
	// 来源提供的可选 host 标识。
	Host *string
	// 来源提供的可选 request correlation 标识。
	RequestID *string
	// 事件归一化后计算的稳定分组 key。
	Fingerprint string
	// 经过 allowlist 和大小限制的非秘密扩展属性。
	Attributes []byte
	// 事件被 FixThe 持久化时的 PostgreSQL 时钟时间。
	IngestedAt pgtype.Timestamptz
}
