// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package observationdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createObservation = `-- name: CreateObservation :one
INSERT INTO observations (
    id, project_id, environment_id, source_id, service, occurred_at, level,
    message, host, request_id, fingerprint, attributes
)
VALUES (
    $1, $2, $3,
    $4, $5, $6, $7,
    $8, $9, $10, $11,
    $12
)
RETURNING id, project_id, environment_id, source_id, service, occurred_at, level,
          message, host, request_id, fingerprint, attributes, ingested_at
`

type CreateObservationParams struct {
	ObservationID pgtype.UUID
	ProjectID     pgtype.UUID
	EnvironmentID pgtype.UUID
	SourceID      pgtype.UUID
	Service       *string
	OccurredAt    pgtype.Timestamptz
	Level         string
	Message       string
	Host          *string
	RequestID     *string
	Fingerprint   string
	Attributes    []byte
}

func (q *Queries) CreateObservation(ctx context.Context, arg CreateObservationParams) (Observation, error) {
	row := q.db.QueryRow(ctx, createObservation,
		arg.ObservationID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.SourceID,
		arg.Service,
		arg.OccurredAt,
		arg.Level,
		arg.Message,
		arg.Host,
		arg.RequestID,
		arg.Fingerprint,
		arg.Attributes,
	)
	var i Observation
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.Service,
		&i.OccurredAt,
		&i.Level,
		&i.Message,
		&i.Host,
		&i.RequestID,
		&i.Fingerprint,
		&i.Attributes,
		&i.IngestedAt,
	)
	return i, err
}

const getObservationSourceScope = `-- name: GetObservationSourceScope :one
SELECT source.environment_id, environment.service
FROM project_sources AS source
JOIN project_environments AS environment
    ON environment.project_id = source.project_id AND environment.id = source.environment_id
WHERE source.project_id = $1
  AND source.id = $2
  AND source.enabled
`

type GetObservationSourceScopeParams struct {
	ProjectID pgtype.UUID
	SourceID  pgtype.UUID
}

type GetObservationSourceScopeRow struct {
	EnvironmentID pgtype.UUID
	Service       *string
}

func (q *Queries) GetObservationSourceScope(ctx context.Context, arg GetObservationSourceScopeParams) (GetObservationSourceScopeRow, error) {
	row := q.db.QueryRow(ctx, getObservationSourceScope, arg.ProjectID, arg.SourceID)
	var i GetObservationSourceScopeRow
	err := row.Scan(&i.EnvironmentID, &i.Service)
	return i, err
}

const listObservations = `-- name: ListObservations :many
SELECT id, project_id, environment_id, source_id, service, occurred_at, level,
       message, host, request_id, fingerprint, attributes, ingested_at,
       COUNT(*) OVER() AS total_count
FROM observations
WHERE project_id = $1
ORDER BY occurred_at DESC, id DESC
LIMIT $2
`

type ListObservationsParams struct {
	ProjectID   pgtype.UUID
	ResultLimit int32
}

type ListObservationsRow struct {
	ID            pgtype.UUID
	ProjectID     pgtype.UUID
	EnvironmentID pgtype.UUID
	SourceID      pgtype.UUID
	Service       *string
	OccurredAt    pgtype.Timestamptz
	Level         string
	Message       string
	Host          *string
	RequestID     *string
	Fingerprint   string
	Attributes    []byte
	IngestedAt    pgtype.Timestamptz
	TotalCount    int64
}

func (q *Queries) ListObservations(ctx context.Context, arg ListObservationsParams) ([]ListObservationsRow, error) {
	rows, err := q.db.Query(ctx, listObservations, arg.ProjectID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListObservationsRow
	for rows.Next() {
		var i ListObservationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SourceID,
			&i.Service,
			&i.OccurredAt,
			&i.Level,
			&i.Message,
			&i.Host,
			&i.RequestID,
			&i.Fingerprint,
			&i.Attributes,
			&i.IngestedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
