-- Lock 风险：创建全新的 users、incidents 表和索引，不改写已有业务数据；
-- 应在依赖这些表的 API binary 发布前执行。
-- Transaction：runner 在同一 transaction 中执行本文件并记录 checksum；任一
-- constraint 或 index 失败都会回滚全部 schema 变更。
-- 兼容性：当前 schema 尚未正式发布；若本地数据库执行过已撤回的 outbox 版
-- 000002 migration，必须重建该开发数据库。
-- Rollback：users 包含 credential hash，incidents 包含业务状态，因此不提供自动
-- down migration；修正使用新的 forward migration。

CREATE TABLE users (
    id uuid PRIMARY KEY,
    username text NOT NULL,
    password_hash text NOT NULL,
    role text NOT NULL,
    enabled boolean NOT NULL DEFAULT true,
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT users_id_uuidv7 CHECK (get_byte(uuid_send(id), 6) >> 4 = 7),
    CONSTRAINT users_username_format CHECK (username ~ '^[a-z][a-z0-9._-]{2,63}$'),
    CONSTRAINT users_password_hash_bounded CHECK (char_length(password_hash) BETWEEN 20 AND 255),
    CONSTRAINT users_role_known CHECK (role IN ('admin', 'operator', 'viewer')),
    CONSTRAINT users_version_positive CHECK (version > 0),
    CONSTRAINT users_updated_after_created CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX users_username_unique_idx ON users (username);

CREATE TABLE incidents (
    id uuid PRIMARY KEY,
    incident_number bigint GENERATED BY DEFAULT AS IDENTITY (START WITH 2049) NOT NULL,
    title text NOT NULL,
    fingerprint text NOT NULL,
    status text NOT NULL DEFAULT 'Open',
    priority text NOT NULL DEFAULT 'Info',
    source text NOT NULL,
    first_seen timestamptz NOT NULL DEFAULT clock_timestamp(),
    last_seen timestamptz NOT NULL DEFAULT clock_timestamp(),
    occurrence_count bigint NOT NULL DEFAULT 1,
    host_count bigint NOT NULL DEFAULT 1,
    muted boolean NOT NULL DEFAULT false,
    notification_summary text NOT NULL DEFAULT 'Lifecycle default',
    version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT incidents_id_uuidv7 CHECK (get_byte(uuid_send(id), 6) >> 4 = 7),
    CONSTRAINT incidents_number_positive CHECK (incident_number > 0),
    CONSTRAINT incidents_title_bounded CHECK (char_length(title) BETWEEN 1 AND 240),
    CONSTRAINT incidents_fingerprint_bounded CHECK (char_length(fingerprint) BETWEEN 1 AND 255),
    CONSTRAINT incidents_status_known CHECK (status IN ('Open', 'Recovered', 'Closed')),
    CONSTRAINT incidents_priority_known CHECK (priority IN ('Info', 'P2', 'P1')),
    CONSTRAINT incidents_source_bounded CHECK (char_length(source) BETWEEN 1 AND 128),
    CONSTRAINT incidents_seen_ordered CHECK (last_seen >= first_seen),
    CONSTRAINT incidents_occurrence_count_positive CHECK (occurrence_count > 0),
    CONSTRAINT incidents_host_count_positive CHECK (host_count > 0),
    CONSTRAINT incidents_host_count_bounded CHECK (host_count <= occurrence_count),
    CONSTRAINT incidents_notification_bounded CHECK (char_length(notification_summary) BETWEEN 1 AND 160),
    CONSTRAINT incidents_version_positive CHECK (version > 0),
    CONSTRAINT incidents_updated_after_created CHECK (updated_at >= created_at)
);

CREATE UNIQUE INDEX incidents_number_unique_idx ON incidents (incident_number);
CREATE UNIQUE INDEX incidents_fingerprint_unique_idx ON incidents (fingerprint);
CREATE INDEX incidents_list_idx ON incidents (last_seen DESC, incident_number DESC);
