// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package migratedb

import (
	"context"
)

const ensureMigrationHistory = `-- name: EnsureMigrationHistory :exec
CREATE TABLE IF NOT EXISTS fixthe_schema_migrations (
    version bigint PRIMARY KEY,
    name text NOT NULL,
    checksum text NOT NULL,
    applied_at timestamptz NOT NULL DEFAULT clock_timestamp(),
    CONSTRAINT fixthe_schema_migrations_version_positive CHECK (version > 0),
    CONSTRAINT fixthe_schema_migrations_name_not_empty CHECK (length(name) > 0),
    CONSTRAINT fixthe_schema_migrations_checksum_sha256 CHECK (checksum ~ '^[0-9a-f]{64}$')
)
`

func (q *Queries) EnsureMigrationHistory(ctx context.Context) error {
	_, err := q.db.Exec(ctx, ensureMigrationHistory)
	return err
}

const listAppliedMigrations = `-- name: ListAppliedMigrations :many
SELECT version, checksum
FROM fixthe_schema_migrations
ORDER BY version
`

type ListAppliedMigrationsRow struct {
	Version  int64
	Checksum string
}

func (q *Queries) ListAppliedMigrations(ctx context.Context) ([]ListAppliedMigrationsRow, error) {
	rows, err := q.db.Query(ctx, listAppliedMigrations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAppliedMigrationsRow
	for rows.Next() {
		var i ListAppliedMigrationsRow
		if err := rows.Scan(&i.Version, &i.Checksum); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordAppliedMigration = `-- name: RecordAppliedMigration :exec
INSERT INTO fixthe_schema_migrations (version, name, checksum)
VALUES ($1, $2, $3)
`

type RecordAppliedMigrationParams struct {
	Version  int64
	Name     string
	Checksum string
}

func (q *Queries) RecordAppliedMigration(ctx context.Context, arg RecordAppliedMigrationParams) error {
	_, err := q.db.Exec(ctx, recordAppliedMigration, arg.Version, arg.Name, arg.Checksum)
	return err
}

const releaseMigrationLock = `-- name: ReleaseMigrationLock :one
SELECT pg_advisory_unlock($1)
`

func (q *Queries) ReleaseMigrationLock(ctx context.Context, pgAdvisoryUnlock int64) (bool, error) {
	row := q.db.QueryRow(ctx, releaseMigrationLock, pgAdvisoryUnlock)
	var pg_advisory_unlock bool
	err := row.Scan(&pg_advisory_unlock)
	return pg_advisory_unlock, err
}

const tryAcquireMigrationLock = `-- name: TryAcquireMigrationLock :one
SELECT pg_try_advisory_lock($1)
`

func (q *Queries) TryAcquireMigrationLock(ctx context.Context, pgTryAdvisoryLock int64) (bool, error) {
	row := q.db.QueryRow(ctx, tryAcquireMigrationLock, pgTryAdvisoryLock)
	var pg_try_advisory_lock bool
	err := row.Scan(&pg_try_advisory_lock)
	return pg_try_advisory_lock, err
}
