// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package authdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 保存可登录 FixThe 的本地用户身份、credential 摘要和授权角色。
type User struct {
	// 应用生成的 UUIDv7 用户内部标识，不作为登录凭据。
	ID pgtype.UUID
	// 规范化后的唯一登录名，仅允许小写字母开头及受限字符。
	Username string
	// 密码的自适应单向 hash；属于敏感 credential，不得存储明文或写入日志。
	PasswordHash string
	// 授权角色，取值为 admin、operator 或 viewer。
	Role string
	// 账户是否允许认证；false 表示账户已停用。
	Enabled bool
	// 用户聚合的单调递增版本号，供更新时执行乐观并发控制。
	Version int64
	// 用户记录首次创建时的 PostgreSQL 时钟时间。
	CreatedAt pgtype.Timestamptz
	// 用户记录最近一次持久化变更时的 PostgreSQL 时钟时间。
	UpdatedAt pgtype.Timestamptz
}
