// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package incidentdb

import (
	"github.com/jackc/pgx/v5/pgtype"
)

// 保存按稳定 fingerprint 聚合后的事故当前状态和列表摘要。
type Incident struct {
	// 应用生成的 UUIDv7 事故内部标识，不作为面向用户的事故编号。
	ID pgtype.UUID
	// PostgreSQL identity 生成的唯一递增事故编号，展示时可格式化为 INC-<number>。
	IncidentNumber int64
	// 供事故列表和详情页展示的简短问题标题。
	Title string
	// 归一化事件计算出的稳定去重键；相同 fingerprint 的事件聚合到同一事故。
	Fingerprint string
	// 事故当前生命周期状态，取值为 Open、Recovered 或 Closed。
	Status string
	// 事故当前优先级，取值为 Info、P2 或 P1。
	Priority string
	// 首次创建该事故的事件来源稳定标识。
	Source string
	// 该 fingerprint 在当前事故中首次被观测到的时间。
	FirstSeen pgtype.Timestamptz
	// 该 fingerprint 在当前事故中最近一次被观测到的时间，也是默认列表排序依据。
	LastSeen pgtype.Timestamptz
	// 聚合到当前事故的事件总数，首次创建时为 1。
	OccurrenceCount int64
	// 当前事故所影响的去重 host 数量，不得大于 occurrence_count。
	HostCount int64
	// 是否静默当前事故的对外通知；静默不影响事件接收、聚合或生命周期更新。
	Muted bool
	// 当前生效通知策略的简短可读摘要，用于事故界面展示。
	NotificationSummary string
	// 事故聚合的单调递增版本号，供更新时执行乐观并发控制。
	Version int64
	// 事故记录首次创建时的 PostgreSQL 时钟时间。
	CreatedAt pgtype.Timestamptz
	// 事故记录最近一次持久化变更时的 PostgreSQL 时钟时间。
	UpdatedAt pgtype.Timestamptz
}
