// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package incidentdb

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIncident = `-- name: CreateIncident :one
WITH created_incident AS (
    INSERT INTO incidents (
        id, project_id, environment_id, source_id, title, fingerprint, status,
        priority, source, first_seen, last_seen, occurrence_count, host_count,
        muted, notification_summary, lifecycle_generation, deployed_commit
    ) VALUES (
        $1, $2, $3,
        $4, $5, $6, $7,
        $8, $9, $10, $11,
        $12, $13, $14,
        $15, $16, $17
    )
    RETURNING id, project_id, environment_id, source_id, incident_number, title,
              fingerprint, status, priority, source, first_seen, last_seen,
              occurrence_count, host_count, muted, notification_summary,
              lifecycle_generation, deployed_commit, version, created_at, updated_at
), created_audit AS (
    INSERT INTO audit_events (
        id, project_id, actor_user_id, action, target_type, target_id, summary, metadata
    )
    SELECT $18, project_id, $19, 'incident.created',
           'incident', id, 'Incident created.',
           jsonb_build_object('incidentNumber', incident_number, 'status', status)
    FROM created_incident
)
SELECT id, project_id, environment_id, source_id, incident_number, title,
       fingerprint, status, priority, source, first_seen, last_seen,
       occurrence_count, host_count, muted, notification_summary,
       lifecycle_generation, deployed_commit, version, created_at, updated_at
FROM created_incident
`

type CreateIncidentParams struct {
	IncidentID          pgtype.UUID
	ProjectID           pgtype.UUID
	EnvironmentID       pgtype.UUID
	SourceID            pgtype.UUID
	Title               string
	Fingerprint         string
	Status              string
	Priority            string
	Source              string
	FirstSeen           pgtype.Timestamptz
	LastSeen            pgtype.Timestamptz
	OccurrenceCount     int64
	HostCount           int64
	Muted               bool
	NotificationSummary string
	LifecycleGeneration int64
	DeployedCommit      string
	AuditID             pgtype.UUID
	ActorUserID         pgtype.UUID
}

type CreateIncidentRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	EnvironmentID       pgtype.UUID
	SourceID            pgtype.UUID
	IncidentNumber      int64
	Title               string
	Fingerprint         string
	Status              string
	Priority            string
	Source              string
	FirstSeen           pgtype.Timestamptz
	LastSeen            pgtype.Timestamptz
	OccurrenceCount     int64
	HostCount           int64
	Muted               bool
	NotificationSummary string
	LifecycleGeneration int64
	DeployedCommit      string
	Version             int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) CreateIncident(ctx context.Context, arg CreateIncidentParams) (CreateIncidentRow, error) {
	row := q.db.QueryRow(ctx, createIncident,
		arg.IncidentID,
		arg.ProjectID,
		arg.EnvironmentID,
		arg.SourceID,
		arg.Title,
		arg.Fingerprint,
		arg.Status,
		arg.Priority,
		arg.Source,
		arg.FirstSeen,
		arg.LastSeen,
		arg.OccurrenceCount,
		arg.HostCount,
		arg.Muted,
		arg.NotificationSummary,
		arg.LifecycleGeneration,
		arg.DeployedCommit,
		arg.AuditID,
		arg.ActorUserID,
	)
	var i CreateIncidentRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentNumber,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.HostCount,
		&i.Muted,
		&i.NotificationSummary,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentByFingerprint = `-- name: GetIncidentByFingerprint :one
SELECT id, project_id, environment_id, source_id, incident_number, title,
       fingerprint, status, priority, source, first_seen, last_seen,
       occurrence_count, host_count, muted, notification_summary,
       lifecycle_generation, deployed_commit, version, created_at, updated_at
FROM incidents
WHERE project_id = $1
  AND fingerprint = $2
`

type GetIncidentByFingerprintParams struct {
	ProjectID   pgtype.UUID
	Fingerprint string
}

type GetIncidentByFingerprintRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	EnvironmentID       pgtype.UUID
	SourceID            pgtype.UUID
	IncidentNumber      int64
	Title               string
	Fingerprint         string
	Status              string
	Priority            string
	Source              string
	FirstSeen           pgtype.Timestamptz
	LastSeen            pgtype.Timestamptz
	OccurrenceCount     int64
	HostCount           int64
	Muted               bool
	NotificationSummary string
	LifecycleGeneration int64
	DeployedCommit      string
	Version             int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetIncidentByFingerprint(ctx context.Context, arg GetIncidentByFingerprintParams) (GetIncidentByFingerprintRow, error) {
	row := q.db.QueryRow(ctx, getIncidentByFingerprint, arg.ProjectID, arg.Fingerprint)
	var i GetIncidentByFingerprintRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentNumber,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.HostCount,
		&i.Muted,
		&i.NotificationSummary,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentByGlobalNumber = `-- name: GetIncidentByGlobalNumber :one
SELECT id, project_id, environment_id, source_id, incident_number, title,
       fingerprint, status, priority, source, first_seen, last_seen,
       occurrence_count, host_count, muted, notification_summary,
       lifecycle_generation, deployed_commit, version, created_at, updated_at
FROM incidents
WHERE incident_number = $1
`

type GetIncidentByGlobalNumberRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	EnvironmentID       pgtype.UUID
	SourceID            pgtype.UUID
	IncidentNumber      int64
	Title               string
	Fingerprint         string
	Status              string
	Priority            string
	Source              string
	FirstSeen           pgtype.Timestamptz
	LastSeen            pgtype.Timestamptz
	OccurrenceCount     int64
	HostCount           int64
	Muted               bool
	NotificationSummary string
	LifecycleGeneration int64
	DeployedCommit      string
	Version             int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetIncidentByGlobalNumber(ctx context.Context, incidentNumber int64) (GetIncidentByGlobalNumberRow, error) {
	row := q.db.QueryRow(ctx, getIncidentByGlobalNumber, incidentNumber)
	var i GetIncidentByGlobalNumberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentNumber,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.HostCount,
		&i.Muted,
		&i.NotificationSummary,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentByID = `-- name: GetIncidentByID :one
SELECT id, project_id, environment_id, source_id, incident_number, title,
       fingerprint, status, priority, source, first_seen, last_seen,
       occurrence_count, host_count, muted, notification_summary,
       lifecycle_generation, deployed_commit, version, created_at, updated_at
FROM incidents
WHERE id = $1
`

type GetIncidentByIDRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	EnvironmentID       pgtype.UUID
	SourceID            pgtype.UUID
	IncidentNumber      int64
	Title               string
	Fingerprint         string
	Status              string
	Priority            string
	Source              string
	FirstSeen           pgtype.Timestamptz
	LastSeen            pgtype.Timestamptz
	OccurrenceCount     int64
	HostCount           int64
	Muted               bool
	NotificationSummary string
	LifecycleGeneration int64
	DeployedCommit      string
	Version             int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetIncidentByID(ctx context.Context, incidentID pgtype.UUID) (GetIncidentByIDRow, error) {
	row := q.db.QueryRow(ctx, getIncidentByID, incidentID)
	var i GetIncidentByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentNumber,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.HostCount,
		&i.Muted,
		&i.NotificationSummary,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentByNumber = `-- name: GetIncidentByNumber :one
SELECT id, project_id, environment_id, source_id, incident_number, title,
       fingerprint, status, priority, source, first_seen, last_seen,
       occurrence_count, host_count, muted, notification_summary,
       lifecycle_generation, deployed_commit, version, created_at, updated_at
FROM incidents
WHERE project_id = $1
  AND incident_number = $2
`

type GetIncidentByNumberParams struct {
	ProjectID      pgtype.UUID
	IncidentNumber int64
}

type GetIncidentByNumberRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	EnvironmentID       pgtype.UUID
	SourceID            pgtype.UUID
	IncidentNumber      int64
	Title               string
	Fingerprint         string
	Status              string
	Priority            string
	Source              string
	FirstSeen           pgtype.Timestamptz
	LastSeen            pgtype.Timestamptz
	OccurrenceCount     int64
	HostCount           int64
	Muted               bool
	NotificationSummary string
	LifecycleGeneration int64
	DeployedCommit      string
	Version             int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) GetIncidentByNumber(ctx context.Context, arg GetIncidentByNumberParams) (GetIncidentByNumberRow, error) {
	row := q.db.QueryRow(ctx, getIncidentByNumber, arg.ProjectID, arg.IncidentNumber)
	var i GetIncidentByNumberRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentNumber,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.HostCount,
		&i.Muted,
		&i.NotificationSummary,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getIncidentSourceScope = `-- name: GetIncidentSourceScope :one
SELECT source.environment_id, source.kind AS source
FROM project_sources AS source
WHERE source.project_id = $1
  AND source.id = $2
  AND source.enabled
`

type GetIncidentSourceScopeParams struct {
	ProjectID pgtype.UUID
	SourceID  pgtype.UUID
}

type GetIncidentSourceScopeRow struct {
	EnvironmentID pgtype.UUID
	Source        string
}

func (q *Queries) GetIncidentSourceScope(ctx context.Context, arg GetIncidentSourceScopeParams) (GetIncidentSourceScopeRow, error) {
	row := q.db.QueryRow(ctx, getIncidentSourceScope, arg.ProjectID, arg.SourceID)
	var i GetIncidentSourceScopeRow
	err := row.Scan(&i.EnvironmentID, &i.Source)
	return i, err
}

const listIncidents = `-- name: ListIncidents :many
SELECT id, project_id, environment_id, source_id, incident_number, title,
       fingerprint, status, priority, source, first_seen, last_seen,
       occurrence_count, host_count, muted, notification_summary,
       lifecycle_generation, deployed_commit, version, created_at, updated_at,
       COUNT(*) OVER() AS total_count
FROM incidents
WHERE project_id = $1
ORDER BY last_seen DESC, incident_number DESC
LIMIT $2
`

type ListIncidentsParams struct {
	ProjectID   pgtype.UUID
	ResultLimit int32
}

type ListIncidentsRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	EnvironmentID       pgtype.UUID
	SourceID            pgtype.UUID
	IncidentNumber      int64
	Title               string
	Fingerprint         string
	Status              string
	Priority            string
	Source              string
	FirstSeen           pgtype.Timestamptz
	LastSeen            pgtype.Timestamptz
	OccurrenceCount     int64
	HostCount           int64
	Muted               bool
	NotificationSummary string
	LifecycleGeneration int64
	DeployedCommit      string
	Version             int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
	TotalCount          int64
}

func (q *Queries) ListIncidents(ctx context.Context, arg ListIncidentsParams) ([]ListIncidentsRow, error) {
	rows, err := q.db.Query(ctx, listIncidents, arg.ProjectID, arg.ResultLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIncidentsRow
	for rows.Next() {
		var i ListIncidentsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.EnvironmentID,
			&i.SourceID,
			&i.IncidentNumber,
			&i.Title,
			&i.Fingerprint,
			&i.Status,
			&i.Priority,
			&i.Source,
			&i.FirstSeen,
			&i.LastSeen,
			&i.OccurrenceCount,
			&i.HostCount,
			&i.Muted,
			&i.NotificationSummary,
			&i.LifecycleGeneration,
			&i.DeployedCommit,
			&i.Version,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordIncidentOccurrence = `-- name: RecordIncidentOccurrence :one
WITH changed_incident AS (
    UPDATE incidents AS incident
    SET last_seen = GREATEST(incident.last_seen, $1),
        occurrence_count = incident.occurrence_count + 1,
        version = incident.version + 1,
        updated_at = clock_timestamp()
    WHERE incident.project_id = $2
      AND incident.fingerprint = $3
      AND incident.status = 'Open'
    RETURNING incident.id, incident.project_id, incident.environment_id,
              incident.source_id, incident.incident_number, incident.title,
              incident.fingerprint, incident.status, incident.priority,
              incident.source, incident.first_seen, incident.last_seen,
              incident.occurrence_count, incident.host_count, incident.muted,
              incident.notification_summary, incident.lifecycle_generation,
              incident.deployed_commit, incident.version,
              incident.created_at, incident.updated_at
), created_audit AS (
    INSERT INTO audit_events (
        id, project_id, actor_user_id, action, target_type, target_id, summary, metadata
    )
    SELECT $4, project_id, $5,
           'incident.occurrence.recorded', 'incident', id,
           'Incident occurrence recorded.',
           jsonb_build_object('incidentNumber', incident_number, 'status', status)
    FROM changed_incident
)
SELECT id, project_id, environment_id, source_id, incident_number, title,
       fingerprint, status, priority, source, first_seen, last_seen,
       occurrence_count, host_count, muted, notification_summary,
       lifecycle_generation, deployed_commit, version, created_at, updated_at
FROM changed_incident
`

type RecordIncidentOccurrenceParams struct {
	LastSeen    pgtype.Timestamptz
	ProjectID   pgtype.UUID
	Fingerprint string
	AuditID     pgtype.UUID
	ActorUserID pgtype.UUID
}

type RecordIncidentOccurrenceRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	EnvironmentID       pgtype.UUID
	SourceID            pgtype.UUID
	IncidentNumber      int64
	Title               string
	Fingerprint         string
	Status              string
	Priority            string
	Source              string
	FirstSeen           pgtype.Timestamptz
	LastSeen            pgtype.Timestamptz
	OccurrenceCount     int64
	HostCount           int64
	Muted               bool
	NotificationSummary string
	LifecycleGeneration int64
	DeployedCommit      string
	Version             int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) RecordIncidentOccurrence(ctx context.Context, arg RecordIncidentOccurrenceParams) (RecordIncidentOccurrenceRow, error) {
	row := q.db.QueryRow(ctx, recordIncidentOccurrence,
		arg.LastSeen,
		arg.ProjectID,
		arg.Fingerprint,
		arg.AuditID,
		arg.ActorUserID,
	)
	var i RecordIncidentOccurrenceRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentNumber,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.HostCount,
		&i.Muted,
		&i.NotificationSummary,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateIncidentStatus = `-- name: UpdateIncidentStatus :one
WITH changed_incident AS (
    UPDATE incidents AS incident
    SET status = $1,
        lifecycle_generation = $2,
        deployed_commit = $3,
        version = incident.version + 1,
        updated_at = clock_timestamp()
    WHERE incident.project_id = $4
      AND incident.incident_number = $5
    RETURNING incident.id, incident.project_id, incident.environment_id,
              incident.source_id, incident.incident_number, incident.title,
              incident.fingerprint, incident.status, incident.priority,
              incident.source, incident.first_seen, incident.last_seen,
              incident.occurrence_count, incident.host_count, incident.muted,
              incident.notification_summary, incident.lifecycle_generation,
              incident.deployed_commit, incident.version,
              incident.created_at, incident.updated_at
), created_audit AS (
    INSERT INTO audit_events (
        id, project_id, actor_user_id, action, target_type, target_id, summary, metadata
    )
    SELECT $6, project_id, $7, 'incident.status.updated',
           'incident', id, 'Incident status updated.',
           jsonb_build_object('incidentNumber', incident_number, 'status', status)
    FROM changed_incident
)
SELECT id, project_id, environment_id, source_id, incident_number, title,
       fingerprint, status, priority, source, first_seen, last_seen,
       occurrence_count, host_count, muted, notification_summary,
       lifecycle_generation, deployed_commit, version, created_at, updated_at
FROM changed_incident
`

type UpdateIncidentStatusParams struct {
	Status              string
	LifecycleGeneration int64
	DeployedCommit      string
	ProjectID           pgtype.UUID
	IncidentNumber      int64
	AuditID             pgtype.UUID
	ActorUserID         pgtype.UUID
}

type UpdateIncidentStatusRow struct {
	ID                  pgtype.UUID
	ProjectID           pgtype.UUID
	EnvironmentID       pgtype.UUID
	SourceID            pgtype.UUID
	IncidentNumber      int64
	Title               string
	Fingerprint         string
	Status              string
	Priority            string
	Source              string
	FirstSeen           pgtype.Timestamptz
	LastSeen            pgtype.Timestamptz
	OccurrenceCount     int64
	HostCount           int64
	Muted               bool
	NotificationSummary string
	LifecycleGeneration int64
	DeployedCommit      string
	Version             int64
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

func (q *Queries) UpdateIncidentStatus(ctx context.Context, arg UpdateIncidentStatusParams) (UpdateIncidentStatusRow, error) {
	row := q.db.QueryRow(ctx, updateIncidentStatus,
		arg.Status,
		arg.LifecycleGeneration,
		arg.DeployedCommit,
		arg.ProjectID,
		arg.IncidentNumber,
		arg.AuditID,
		arg.ActorUserID,
	)
	var i UpdateIncidentStatusRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.EnvironmentID,
		&i.SourceID,
		&i.IncidentNumber,
		&i.Title,
		&i.Fingerprint,
		&i.Status,
		&i.Priority,
		&i.Source,
		&i.FirstSeen,
		&i.LastSeen,
		&i.OccurrenceCount,
		&i.HostCount,
		&i.Muted,
		&i.NotificationSummary,
		&i.LifecycleGeneration,
		&i.DeployedCommit,
		&i.Version,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
